/* Curio service worker — offline-first for a fully static app.
   Releasing a change: bump CACHE *and* the ?v= asset versions here and in
   index.html. Install fetches with cache:"reload" so the HTTP cache can
   never pin a stale asset into a new SW cache. */
const CACHE = "qpio-v103";
// Not a versioned asset: the page's week of daily questions, read by the
// periodicsync handler at the bottom of this file. Survives every release.
const NUDGE_CACHE = "qpio-nudge";
// Cross-origin photographs (upload.wikimedia.org thumbnails from the app's own
// curated maps). The CEO, 2026-08-17: "the refreshing speed for the images in
// the app is a bit slow" — and again rejecting v81: "too slow on the before
// you travel section". The root cause: every photo was a cold third-party
// fetch on every view — the generic handler below only caches `basic`
// (same-origin) responses, so these were never cached at all. Cache-first
// here, in its own bounded store: URLs are immutable thumbnails, so a hit is
// always the right bytes, and the cap keeps storage honest on a phone.
const IMG_CACHE = "qpio-img-v1";
const IMG_CACHE_MAX = 160;
// THE FLAGS TRAVEL WITH THE APP. CEO, 21 Sep 2026: "when off line the flags
// don't appear, the flags should be pre-loaded in the app." The photograph
// store above keeps a picture once it has been SEEN, so a flag never met online
// was never there offline — and "Which country's flag is this?" with no flag is
// not a question. Every flag the bank shows now has a copy under img/flags/,
// listed below by curio-hq/tools/bundle_flags.js and fetched on install into
// its own store. The store is keyed by content (each file name carries a hash
// of its bytes), so a release never downloads the flags again and a changed
// flag arrives under a new name.
// The same store also carries the city packs' pictures (img/cities/), chosen
// and licence-checked one per city, so the travel cards are never blank —
// online or off (CEO, 21 Sep 2026: "there is no images on the travel city
// sections").
const FLAG_CACHE = "qpio-pictures";
// FLAGS:begin — generated by curio-hq/tools/bundle_flags.js; 84 flags, 1680 KB; 18 city pictures, 3312 KB
const FLAGS = [
  "./img/flags/Ancient_mapuche_flag.23ee6812.png",
  "./img/flags/Australian_Aboriginal_Flag.4b602662.png",
  "./img/flags/Flag_of_Albania.68486f66.png",
  "./img/flags/Flag_of_Argentina.cb6bd6a7.png",
  "./img/flags/Flag_of_Australia__converted.717a8226.png",
  "./img/flags/Flag_of_Bangladesh.cee0eea9.png",
  "./img/flags/Flag_of_Belgium.0e644a47.png",
  "./img/flags/Flag_of_Bhutan.4b07b573.png",
  "./img/flags/Flag_of_Botswana.c1b8b111.png",
  "./img/flags/Flag_of_Brazil.84214e96.png",
  "./img/flags/Flag_of_Cambodia.92226809.png",
  "./img/flags/Flag_of_Canada__Pantone.af473fda.png",
  "./img/flags/Flag_of_Chile.554f4c06.png",
  "./img/flags/Flag_of_Colombia.72b18829.png",
  "./img/flags/Flag_of_Cuba.5158a1c8.png",
  "./img/flags/Flag_of_Egypt.85c5c657.png",
  "./img/flags/Flag_of_Ethiopia.10b89e6d.png",
  "./img/flags/Flag_of_Fiji.522b7de0.png",
  "./img/flags/Flag_of_Finland.e1cc1b41.png",
  "./img/flags/Flag_of_France.7c622659.png",
  "./img/flags/Flag_of_Germany.d59f118c.png",
  "./img/flags/Flag_of_Ghana.ebce2f43.png",
  "./img/flags/Flag_of_Greece.5b17886d.png",
  "./img/flags/Flag_of_Iceland.f3f9400a.png",
  "./img/flags/Flag_of_India.69074216.png",
  "./img/flags/Flag_of_Indonesia.af360f4a.png",
  "./img/flags/Flag_of_Iran.da7aac6d.png",
  "./img/flags/Flag_of_Ireland.f6d287fd.png",
  "./img/flags/Flag_of_Israel.f981443e.png",
  "./img/flags/Flag_of_Italy.13fa8049.png",
  "./img/flags/Flag_of_Jamaica.d3cbc706.png",
  "./img/flags/Flag_of_Japan.4ab4211b.png",
  "./img/flags/Flag_of_Jordan.4d4cfaa5.png",
  "./img/flags/Flag_of_Kazakhstan.c0a8a19c.png",
  "./img/flags/Flag_of_Kenya.9e2d4228.png",
  "./img/flags/Flag_of_Lebanon.9f1a6eb8.png",
  "./img/flags/Flag_of_Lesotho.2271b409.png",
  "./img/flags/Flag_of_Mali.8be31aea.png",
  "./img/flags/Flag_of_Mexico.8f4cede5.png",
  "./img/flags/Flag_of_Mongolia.ed257545.png",
  "./img/flags/Flag_of_Morocco.4b03abf7.png",
  "./img/flags/Flag_of_Mozambique.a10b9d3c.png",
  "./img/flags/Flag_of_Namibia.337f2911.png",
  "./img/flags/Flag_of_Nepal.9fca1ad9.png",
  "./img/flags/Flag_of_New_Zealand.d07ac0be.png",
  "./img/flags/Flag_of_Nigeria.cb4c1c43.png",
  "./img/flags/Flag_of_Norway.12534fe8.png",
  "./img/flags/Flag_of_Papua_New_Guinea.3b9f3438.png",
  "./img/flags/Flag_of_Peru.65fa9868.png",
  "./img/flags/Flag_of_Poland.09610ad1.png",
  "./img/flags/Flag_of_Portugal.38d64dec.png",
  "./img/flags/Flag_of_Portugal__official.f9672ae7.png",
  "./img/flags/Flag_of_Qatar.071c7156.png",
  "./img/flags/Flag_of_Romania.e8e0dd1f.png",
  "./img/flags/Flag_of_Rwanda.5904ecb7.png",
  "./img/flags/Flag_of_Saudi_Arabia.55495f36.png",
  "./img/flags/Flag_of_Senegal.d7dfcab6.png",
  "./img/flags/Flag_of_Siam__1855.6f84a3d3.png",
  "./img/flags/Flag_of_Singapore.0eabf3f7.png",
  "./img/flags/Flag_of_South_Africa.6f1528ab.png",
  "./img/flags/Flag_of_South_Korea.f6556e9c.png",
  "./img/flags/Flag_of_Spain.008afcbb.png",
  "./img/flags/Flag_of_Sri_Lanka.e959185d.png",
  "./img/flags/Flag_of_Sweden.4dcae170.png",
  "./img/flags/Flag_of_Switzerland.23993ee3.png",
  "./img/flags/Flag_of_Switzerland__Pantone.27846832.png",
  "./img/flags/Flag_of_Tanzania.9704dd47.png",
  "./img/flags/Flag_of_Thailand.8e9793f3.png",
  "./img/flags/Flag_of_Thailand__Ayutthaya_period.de2cf560.png",
  "./img/flags/Flag_of_Turkey.1b0cec03.png",
  "./img/flags/Flag_of_Ukraine.2331ad1b.png",
  "./img/flags/Flag_of_Uruguay.9b95886a.png",
  "./img/flags/Flag_of_Uzbekistan.90652437.png",
  "./img/flags/Flag_of_Vatican_City__2023_present.31b2cdf1.png",
  "./img/flags/Flag_of_Vietnam.54194e78.png",
  "./img/flags/Flag_of_the_Kingdom_of_Kongo_according_to_Giovanni_Cavazzi_da_Montecuccolo.e454132b.png",
  "./img/flags/Flag_of_the_Kingdom_of_Spain.681569c2.png",
  "./img/flags/Flag_of_the_Netherlands.0b9be6c3.png",
  "./img/flags/Flag_of_the_Ottoman_Empire__1844_1922.0108cc56.png",
  "./img/flags/Flag_of_the_Philippines.0d8ca898.png",
  "./img/flags/Flag_of_the_United_Arab_Emirates.1cf5ecd1.png",
  "./img/flags/Flag_used_in_the_east_coast_of_Tanzania_according_to_a_Portuguese_1576_map.770217f8.png",
  "./img/flags/Merina_Kingdom_flag.caae0819.png",
  "./img/flags/Naval_flag_of_Majapahit_Kingdom.70fcbd9f.png",
  "./img/cities/addis_ababa.d39e034b.jpg",
  "./img/cities/amman.1d4d0333.jpg",
  "./img/cities/athens.2c5fbb3a.jpg",
  "./img/cities/bangkok.9e5dac10.jpg",
  "./img/cities/buenos_aires.58a408f8.jpg",
  "./img/cities/cairo.fd6c7501.jpg",
  "./img/cities/cusco.a7a1194f.jpg",
  "./img/cities/hanoi.028419d0.jpg",
  "./img/cities/istanbul.c1a5f2c0.jpg",
  "./img/cities/kyoto.79d7dd10.jpg",
  "./img/cities/lagos.f08dea45.jpg",
  "./img/cities/marrakech.08dd10ae.jpg",
  "./img/cities/mexico_city.97ce6976.jpg",
  "./img/cities/muscat.51bbe1be.jpg",
  "./img/cities/rome.07c926be.jpg",
  "./img/cities/salvador.96623d15.jpg",
  "./img/cities/samarkand.92ebd88e.jpg",
  "./img/cities/tbilisi.1bb00f0f.jpg"
];
// FLAGS:end
const ASSETS = [
  "./",
  "./index.html",
  "./src/styles.css?v=103",
  "./brand/qpio-mark-96.png?v=103",
  "./brand/icons/qpio-icon-96.png?v=103",
  "./brand/qpio-lockup-header.png?v=103",
  "./src/i18n.js?v=103",
  "./src/questions.fr.js?v=103",
  "./src/qid.legacy.js?v=103",
  "./src/content.version.js?v=103",
  "./src/measure.js?v=103",
  "./src/truthlab.fr.js?v=103",
  "./src/app.js?v=103",
  "./src/questions.js?v=103",
  "./src/truthlab.js?v=103",
  "./src/citypacks.js?v=103",
  "./src/citypacks.fr.js?v=103",
  "./src/entities.fr.js?v=103",
  "./src/entities.img.js?v=103",
  "./src/flags.js?v=103",
  "./src/entities.meta.js?v=103",
  "./src/country.js?v=103",
  "./src/links.read.js?v=103",
  "./src/golinks.js?v=103",
  "./src/doors.js?v=103",
  "./src/hooks.js?v=103",
  "./src/gymart.js?v=103",
  "./src/braingym.js?v=103",
  "./src/watch.chosen.js?v=103",
  "./src/doors.chosen.js?v=103",
  "./src/doors.bank.js?v=103",
  "./src/watch.empty.js?v=103",
  "./src/hooks.q.js?v=103",
  "./src/discovery.js?v=103",
  "./src/daily.overrides.js?v=103",
  "./src/resources.js?v=103",
  "./src/intelligence.js?v=103",
  "./src/intelligence.corpus.js?v=103",
  "./src/preload.js?v=103",
  "./manifest.webmanifest",
  "./brand/icons/qpio-icon-192.png",
  "./brand/icons/qpio-icon-512.png",
  "./brand/icons/qpio-icon-512-maskable.png",
  "./icons/apple-touch-icon.png",
  "./icons/favicon-32.png"
];

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => Promise.all(ASSETS.map((u) => c.add(new Request(u, { cache: "reload" })))))
      .then(() => preloadFlags())
      .then(() => self.skipWaiting())
  );
});

// Every flag, once. A copy already held is not fetched again. A copy that
// cannot be fetched right now does not block the release — the shell and the
// banks above are the release; the fetch handler keeps that flag the first
// time it is asked for, and the next activate tries again.
// Only a picture is kept. The edge answers a path it does not have with the
// app's own index.html and a 200 (single-page-application handling), and a
// page stored under a flag's name would be served as that flag for ever —
// so what comes back must SAY it is an image before it is stored.
function isPicture(res) {
  return !!(res && res.status === 200 && /^image\//.test(res.headers.get("content-type") || ""));
}
async function preloadFlags() {
  const c = await caches.open(FLAG_CACHE);
  return Promise.allSettled(FLAGS.map(async (u) => {
    if (await c.match(u)) return;
    const res = await fetch(new Request(u, { cache: "reload" }));
    if (!isPicture(res)) throw new Error("not a picture: " + u);
    await c.put(u, res);
  }));
}

// Sweep last release's asset caches — but NOT the nudge queue, which is not a
// versioned asset and would otherwise be wiped on every release, silently
// killing the daily notification the first time we shipped anything. The
// image cache survives too: it is content-keyed, not version-keyed. So does
// the flag store, which is tidied instead: a copy the current list no longer
// names goes. Anything the install could not fetch is tried once more — but
// NOT inside waitUntil: while a worker is activating the browser holds every
// request from its pages until activate settles, and a retry that waits on the
// network would freeze the app for exactly as long as the network is slow.
self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys
        .filter((k) => k !== CACHE && k !== NUDGE_CACHE && k !== IMG_CACHE && k !== FLAG_CACHE)
        .map((k) => caches.delete(k)))
    ).then(() => tidyFlags()).then(() => self.clients.claim())
  );
  preloadFlags().catch(() => {});          // best effort, off the critical path
});

async function tidyFlags() {
  const c = await caches.open(FLAG_CACHE);
  const want = new Set(FLAGS.map((u) => new URL(u, self.location.href).href));
  const keys = await c.keys();
  await Promise.all(keys.filter((r) => !want.has(r.url)).map((r) => c.delete(r)));
}

// THE STALE-VERSION BUG, fixed 2026-08-09.
//
// This was cache-first for EVERYTHING, including the page shell. index.html is
// the one file with no ?v= on it, so a returning visitor always rendered
// yesterday's HTML — which then asked for yesterday's ?v= assets, which were
// still cached, so the whole app stayed a version behind. Reinstalling did not
// help: the cache belongs to the origin, not to the installed icon.
//
// The shell is now NETWORK-FIRST: always fetch the newest HTML, fall back to
// cache only when genuinely offline. Versioned assets stay cache-first, which
// is safe precisely because their URL changes when their content does.
function isShell(req) {
  if (req.mode === "navigate") return true;
  const u = new URL(req.url);
  return u.pathname.endsWith("/") || u.pathname.endsWith("/index.html");
}

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;

  // Gate 5 door instrument: never intercept, never cache, never fall back.
  // Two defects this guard closes (GATE-5-DOOR-INSTRUMENT.md §2.5): the
  // generic handler below caches AND re-fetches — caches.put() ignores
  // Cache-Control: no-store, and the re-fetch would count the denominator
  // once per RENDER instead of once per device-day — and a /go/ tap is a
  // navigation, so isShell() would answer a failed tap with index.html.
  // Returning without respondWith lets the browser make the request itself.
  // (/doors/ and /go/ must also stay absent from the ASSETS precache above.)
  const p = new URL(req.url).pathname;
  if (p.startsWith("/go/") || p.startsWith("/doors/")) return;

  // A demo video (v103): never through a cache. A browser asks for a video in
  // byte ranges, and a whole file from the cache answering a range request stops
  // it playing on an iPhone. It is fetched only when a routine shows it.
  if (/\.mp4$/.test(p)) return;

  // A bundled flag: from its own store, which install filled. A miss (the
  // install could not fetch that one) is fetched and kept, so it is there next
  // time — including with no network. A request carrying a query string is a
  // probe (the acceptance suite asks "does THIS build serve the file?"): it
  // goes straight to the network and is stored nowhere.
  if (/\/img\/(flags|cities)\//.test(p) && new URL(req.url).origin === self.location.origin) {
    if (new URL(req.url).search) { e.respondWith(fetch(req)); return; }
    e.respondWith((async () => {
      const c = await caches.open(FLAG_CACHE);
      const hit = await c.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (isPicture(res)) c.put(req, res.clone());
      return res;
    })());
    return;
  }

  // The photograph store (issue #1). A plain <img> fetch is no-cors, so most
  // of these arrive as opaque responses — expected and cacheable here; a
  // network failure rejects and simply renders no image, exactly as before.
  if (new URL(req.url).host === "upload.wikimedia.org") {
    e.respondWith((async () => {
      const c = await caches.open(IMG_CACHE);
      const hit = await c.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (res && (res.status === 200 || res.type === "opaque")) {
        const copy = res.clone();
        c.put(req, copy).then(() => {
          // Bounded: past the cap, the oldest entries go first.
          c.keys().then((keys) => {
            for (let i = 0; i < keys.length - IMG_CACHE_MAX; i++) c.delete(keys[i]);
          });
        });
      }
      return res;
    })());
    return;
  }

  if (isShell(req)) {
    e.respondWith(
      fetch(req, { cache: "no-store" })
        .then((res) => {
          if (res && res.status === 200) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put("./index.html", copy));
          }
          return res;
        })
        .catch(() => caches.match("./index.html").then((hit) => hit || caches.match("./")))
    );
    return;
  }

  e.respondWith(
    caches.match(req).then((hit) => {
      const net = fetch(req)
        .then((res) => {
          if (res && res.status === 200 && res.type === "basic") {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => hit);
      return hit || net;
    })
  );
});

// THE DAILY QUESTION, DELIVERED WITHOUT A SERVER.
//
// Chrome on Android wakes an installed PWA's service worker on a schedule it
// chooses — roughly daily, and only for a site the reader genuinely uses. That
// is the only way to reach a closed phone with no backend and no push service.
// It does not exist on iOS or on desktop Safari/Firefox, where the question can
// only arrive while Qpio is open. See app.js registerPeriodicNudge().
//
// The worker has no localStorage and no question bank, so the page leaves it a
// week of questions in its own cache: { on, days: { "2026-08-10": {q, done} } }.
// Nothing here decides anything — it reads what the page already knew.
const NUDGE_URL = "./nudge-queue.json";

async function nudgeToday() {
  const c = await caches.open(NUDGE_CACHE);
  const hit = await c.match(NUDGE_URL);
  if (!hit) return;
  const data = await hit.json().catch(() => null);
  if (!data || !data.on || !data.days) return;

  const n = new Date();
  // The reader picked a delivery hour. The browser wakes this worker on its
  // own schedule, so the contract is "from HH:00", never "at HH:00" — before
  // the chosen hour we simply decline and wait for the next wake.
  if (typeof data.hour === "number" && n.getHours() < data.hour) return;
  const key = n.getFullYear() + "-" +
    String(n.getMonth() + 1).padStart(2, "0") + "-" +
    String(n.getDate()).padStart(2, "0");
  const day = data.days[key];
  if (!day || day.done || day.sent) return;

  await self.registration.showNotification("Qpio", {
    body: day.q,                                 // the question itself, not a reminder to play
    tag: "qpio-daily-" + key,
    badge: "icons/favicon-32.png",
    icon: "brand/icons/qpio-icon-192.png",
    data: { url: "./#daily" }
  });

  // Marked here rather than by the page: the page may not open for days, and
  // the same question must not arrive twice.
  day.sent = true;
  await c.put(NUDGE_URL, new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" }
  }));
}

self.addEventListener("periodicsync", (e) => {
  if (e.tag === "qpio-daily") e.waitUntil(nudgeToday());
});

// Tapping the question lands the reader INSIDE the daily challenge — the Hanzi
// pattern the CEO asked for: the notification is the first question, the tap
// is the way to answer it. An already-open tab is navigated to #daily, not
// merely focused — focusing alone left the reader wherever they last were.
self.addEventListener("notificationclick", (e) => {
  e.notification.close();
  const target = (e.notification.data && e.notification.data.url) || "./#daily";
  e.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((list) => {
      for (const c of list) {
        if ("navigate" in c && "focus" in c) {
          return c.navigate(target).then((cl) => (cl || c).focus()).catch(() => c.focus());
        }
        if ("focus" in c) return c.focus();
      }
      return self.clients.openWindow(target);
    })
  );
});
