// Curio "Fact or Fake?" statement bank.
// Each: s (statement), truth (true = real, false = fake), explain (correction
// or context — names the misinformation trick for fakes), src (citation URL),
// cat (feeds the Brain Map), kids (kid-suitable flag).
// v1 set is editor-verified (famous, unambiguous misconceptions and truths);
// the agent pipeline will expand it with fact-checked additions later.
window.CURIO_STATEMENTS = [
  // ---- FAKES (common misconceptions) ----
  { s: "Humans only use 10% of their brains.", truth: false, cat: "Science", kids: true,
    explain: "Fake. Brain scans show we use virtually all of it, just not all at once. The myth spreads because it sounds hopeful — a hidden reserve of 'untapped potential'.",
    src: "https://en.wikipedia.org/wiki/Ten_percent_of_the_brain_myth" },
  { s: "Bats are blind.", truth: false, cat: "Nature", kids: true,
    explain: "Fake. All bats can see; many also 'see' with echolocation. The phrase 'blind as a bat' turned a catchy saying into a believed fact.",
    src: "https://en.wikipedia.org/wiki/Bat" },
  { s: "Vikings wore helmets with horns on them.", truth: false, cat: "History", kids: true,
    explain: "Fake. No horned Viking helmet has ever been found. The image was invented for an 1876 opera and stuck — a myth born from art, not history.",
    src: "https://en.wikipedia.org/wiki/Horned_helmet" },
  { s: "A goldfish has a memory of only a few seconds.", truth: false, cat: "Nature", kids: true,
    explain: "Fake. Goldfish remember things for months and can learn routines. The myth survives by being repeated so often it feels obviously true.",
    src: "https://en.wikipedia.org/wiki/Goldfish" },
  { s: "Napoleon Bonaparte was unusually short.", truth: false, cat: "History", kids: false,
    explain: "Fake. He was about average height for his era (~1.68 m). British wartime cartoons mocked him as tiny, and French vs. English inches confused the record.",
    src: "https://en.wikipedia.org/wiki/Napoleon" },
  { s: "Lightning never strikes the same place twice.", truth: false, cat: "Science", kids: true,
    explain: "Fake. Tall spots get hit repeatedly — the Empire State Building is struck about 20–25 times a year. A comforting proverb mistaken for physics.",
    src: "https://en.wikipedia.org/wiki/Lightning" },
  { s: "Cut an earthworm in half and you get two living worms.", truth: false, cat: "Nature", kids: true,
    explain: "Fake. At best the head end may survive and regrow a tail; the tail end dies. A schoolyard myth that oversimplifies how regeneration works.",
    src: "https://en.wikipedia.org/wiki/Earthworm" },
  { s: "Albert Einstein failed mathematics at school.", truth: false, cat: "Science", kids: false,
    explain: "Fake. Einstein excelled at maths and mastered calculus by 15. The myth is popular because it flatters anyone struggling — 'even Einstein failed'.",
    src: "https://en.wikipedia.org/wiki/Albert_Einstein" },

  // ---- REALS (surprising but true) ----
  { s: "An octopus has three hearts and blue blood.", truth: true, cat: "Nature", kids: true,
    explain: "Real. Two hearts pump blood to the gills, one to the body, and a copper-based pigment makes the blood blue instead of red.",
    src: "https://en.wikipedia.org/wiki/Octopus" },
  { s: "Honey can still be edible after thousands of years.", truth: true, cat: "Nature", kids: true,
    explain: "Real. Its low moisture and natural acidity block microbes — honey found sealed in ancient Egyptian tombs was reportedly still good to eat.",
    src: "https://en.wikipedia.org/wiki/Honey" },
  { s: "Oxford University is older than the Aztec Empire.", truth: true, cat: "History", kids: false,
    explain: "Real. Teaching at Oxford began by around 1096; the Aztecs founded Tenochtitlan in 1325. Europe's oldest English-speaking university predates the Aztec capital.",
    src: "https://en.wikipedia.org/wiki/University_of_Oxford" },
  { s: "A day on Venus lasts longer than a year on Venus.", truth: true, cat: "Science", kids: false,
    explain: "Real. Venus spins so slowly that one rotation takes 243 Earth days, while it orbits the Sun in about 225 — the day outlasts the year.",
    src: "https://en.wikipedia.org/wiki/Venus" },
  { s: "Africa is the only continent in all four hemispheres.", truth: true, cat: "Geography", kids: true,
    explain: "Real. The equator and the prime meridian both cross Africa, placing parts of it in the northern, southern, eastern and western hemispheres at once.",
    src: "https://en.wikipedia.org/wiki/Africa" },
  { s: "A banana is botanically a berry, but a strawberry is not.", truth: true, cat: "Nature", kids: true,
    explain: "Real. Botanically a berry grows from one flower with seeds inside — that fits bananas. A strawberry forms from many ovaries, so it isn't a true berry.",
    src: "https://en.wikipedia.org/wiki/Berry_(botany)" },
  { s: "Sound travels faster through water than through air.", truth: true, cat: "Science", kids: true,
    explain: "Real. Sound moves about four times faster in water (~1,480 m/s) than in air (~343 m/s), because water's tightly packed molecules pass the vibration along quicker.",
    src: "https://en.wikipedia.org/wiki/Speed_of_sound" },
  { s: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.", truth: true, cat: "History", kids: false,
    explain: "Real. The Great Pyramid rose around 2560 BCE, Cleopatra around 30 BCE, and Apollo 11 in 1969 — she sits nearer our era than the pyramid's.",
    src: "https://en.wikipedia.org/wiki/Cleopatra" },
];
