/* The daily ledger the app ships (src/daily.ledger.js, generated by curio-hq
 * tools/daily_ledger.js): every named question exists in the bank, five different
 * ones a day, and none returns within minGapDays - before the day the record says
 * the rule breaks for want of questions. A release that ships a stale ledger (a
 * withdrawn question on a coming day) fails here instead of falling back quietly.
 * Run: node tools/daily_ledger.test.js   (also part of npm test) */
const fs = require('fs'), path = require('path'), vm = require('vm');
const box = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '..', 'src', 'questions.js'), 'utf8'), box);
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '..', 'src', 'daily.ledger.js'), 'utf8'), box);
const bank = Object.values(box.window).find(v => Array.isArray(v) && v.length > 100 && v[0] && v[0].id);
const ids = new Set((bank || []).map(q => q.id));
const L = box.window.CURIO_DAILY_LEDGER;
let fail = 0; const t = (ok, what) => { if (!ok) { fail++; console.log('FAIL ' + what); } };
t(ids.size > 0, 'the bank loads');
t(L && L.minGapDays >= 365, 'the ledger names its rule (min ' + (L && L.minGapDays) + ' days)');
for (const mode of ['adult', 'kids']) {
  const days = (L && L[mode]) || {}, last = {}; let rep = 0;
  for (const d of Object.keys(days).sort()) {
    const five = String(days[d]).split(',');
    t(five.length === 5 && new Set(five).size === 5, mode + ' ' + d + ': five different questions');
    five.forEach(id => t(ids.has(id), mode + ' ' + d + ': ' + id + ' is in the bank'));
    const n = Date.parse(d) / 864e5, stop = L.breaks && L.breaks[mode];
    for (const id of five) { if ((!stop || d < stop) && last[id] !== undefined && n - last[id] < L.minGapDays) rep++; last[id] = n; }
  }
  t(rep === 0, mode + ': no question returns within ' + L.minGapDays + ' days (' + rep + ' found)');
}
if (fail) { console.log('daily ledger: ' + fail + ' failed'); process.exit(1); }
console.log('daily ledger: all checks passed');
