/* WHICH RELEASE OF THE QUESTION BANK A READER WAS SERVED.
 *
 * CEO, 6 September 2026: "Track separately: app_version — platform/features/code
 * release; content_version / bank version — question/content release."
 *
 * They are genuinely different things and conflating them would quietly ruin
 * per-question measurement. The app can ship three times in a week without a
 * single question changing, and the bank can change without a line of code
 * moving. More importantly: the daily rotation is seeded partly by HOW MANY
 * questions are in the bank, so publishing one new question re-deals the entire
 * deck. Two stretches of a question's history either side of that are different
 * experiments, and without a content version nobody would ever see the join.
 *
 * The version is derived from the bank itself rather than typed, so it cannot
 * be forgotten and cannot disagree with what shipped: a short hash of every
 * question id, revision and translation revision, plus the row count.
 *
 *   node tools/stamp_content_version.js            write src/content.version.js
 *   node tools/stamp_content_version.js --check    verify it matches the bank
 */

'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const APP = path.resolve(__dirname, '..');
const OUT = path.join(APP, 'src', 'content.version.js');
const CHECK = process.argv.includes('--check');

global.window = {};
require(path.join(APP, 'src', 'questions.js'));
require(path.join(APP, 'src', 'questions.fr.js'));
const EN = global.window.CURIO_QUESTIONS || [];
const FR = global.window.CURIO_QUESTIONS_FR || [];

if (!EN.length) {
  console.error('  content version: the English bank is empty');
  process.exit(2);
}

/* The row COUNT is in the hash on purpose. It is what the rotation is seeded
 * with, so a change in it is a change in which five questions each day gets -
 * the single most important thing a content version has to capture. */
const material = [
  'n=' + EN.length,
  EN.map(q => q.id + ':' + (q.qrev || 1)).join(','),
  FR.map(q => q.id + ':' + (q.lrev || 1)).join(','),
].join('|');

const hash = crypto.createHash('sha256').update(material).digest('hex').slice(0, 8);
const version = EN.length + '-' + hash;

const body = `// © 2026 Qpio. GENERATED by tools/stamp_content_version.js — do not edit by hand.
//
// WHICH RELEASE OF THE QUESTION BANK THIS BUILD SERVES.
//
// Not the app version: the app can ship three times in a week without a
// question changing, and the bank can change without a line of code moving.
// It matters because the daily rotation is seeded partly by how many questions
// are in the bank — publishing one new question re-deals the whole deck — so
// two stretches of a question's history either side of a bank change are
// different experiments, and this is what makes the join visible.
//
// Derived from the bank itself: the row count, plus a hash of every question id
// with its revision and its translation's revision.
window.CURIO_CONTENT_VERSION = "${version}";
`;

if (CHECK) {
  const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  const m = /CURIO_CONTENT_VERSION = "([^"]+)"/.exec(have);
  if (!m) { console.error('  content version: src/content.version.js is missing or unreadable'); process.exit(1); }
  if (m[1] !== version) {
    console.error('  content version: stamped ' + m[1] + ' but the bank is ' + version +
      ' — run node tools/stamp_content_version.js');
    process.exit(1);
  }
  console.log('  content version: ' + version + ' matches the bank');
  process.exit(0);
}

fs.writeFileSync(OUT, body, 'utf8');
console.log('  content version: ' + version + '  (' + EN.length + ' questions)');
