// © 2026 Qpio. GENERATED by tools/stamp_content_version.js — do not edit by hand.
//
// WHICH RELEASE OF THE QUESTION BANK THIS BUILD SERVES.
//
// Not the app version: the app can ship three times in a week without a
// question changing, and the bank can change without a line of code moving.
// It matters because the daily rotation is seeded partly by how many questions
// are in the bank — publishing one new question re-deals the whole deck — so
// two stretches of a question's history either side of a bank change are
// different experiments, and this is what makes the join visible.
//
// Derived from the bank itself: the row count, plus a hash of every question id
// with its revision and its translation's revision.
window.CURIO_CONTENT_VERSION = "1968-748a2c0f";
