// © 2026 Qpio. All rights reserved. Not covered by the MIT LICENSE.
// Terms of use: /CONTENT-LICENCE.md · Machine use reserved: /ai.txt
//
// GENERATED — do not hand-edit. Rebuild with: py tools/fetch_fr_titles.py
//
// The French name of each entity, and the French Wikipedia article, taken
// from Wikipedia's own interlanguage links. A lookup, not a translation:
// these are the titles the French Wikipedia community chose themselves.
// Baked at build time so the app never touches the network to render.
//
// 371 of 383 entities have a French article (96.9%). The rest keep their
// English name, which is correct — not every subject has a French page.

window.CURIO_FR_ENTITIES = {
  "ARPANET": "ARPANET",
  "Abdelkader_ibn_Muhieddine": "Abdelkader (émir)",
  "Aboriginal_Australians": "Aborigènes d'Australie",
  "Absolute_zero": "Zéro absolu",
  "Ada_Lovelace": "Ada Lovelace",
  "Africa": "Afrique",
  "African_bush_elephant": "Éléphant de savane d'Afrique",
  "Ah!_vous_dirai-je,_maman": "Ah ! vous dirai-je, maman",
  "Al-Azhar_Mosque": "Mosquée Al-Azhar",
  "Al-Khwarizmi": "Al-Khwârizmî",
  "Alaska_Purchase": "Achat de l'Alaska",
  "Albert_Einstein": "Albert Einstein",
  "Allotropes_of_carbon": "Allotropie du carbone",
  "Almoravid_dynasty": "Almoravides",
  "Amazon_River": "Amazone (fleuve)",
  "Amelia_Earhart": "Amelia Earhart",
  "Ancient_Olympic_Games": "Jeux olympiques antiques",
  "Andes": "Cordillère des Andes",
  "Angel_Falls": "Salto Ángel",
  "Angkor_Wat": "Angkor Vat",
  "Antarctica": "Antarctique",
  "Apollo_11": "Apollo 11",
  "Arctic_tern": "Sterne arctique",
  "Ashoka": "Ashoka",
  "Atacama_Desert": "Désert d'Atacama",
  "Athenian_democracy": "Démocratie athénienne",
  "Athens": "Athènes",
  "Atomic_nucleus": "Noyau atomique",
  "Augustus": "Auguste",
  "Ayutthaya_Kingdom": "Royaume d'Ayutthaya",
  "Aztec_Empire": "Empire aztèque",
  "Banana_equivalent_dose": "Dose équivalente en banane",
  "Bat": "Chiroptera",
  "Battle_of_Adwa": "Bataille d'Adoua",
  "Battle_of_Ain_Jalut": "Bataille d'Aïn Djalout",
  "Benin_Bronzes": "Bronzes du Bénin",
  "Berry_(botany)": "Baie (botanique)",
  "Binary_number": "Système binaire",
  "Black_Death": "Peste noire",
  "Blue_whale": "Baleine bleue",
  "Boiling_point": "Point d'ébullition",
  "Bolivian_Navy": "Marine bolivienne",
  "Bosporus": "Bosphore",
  "Brahmagupta": "Brahmagupta",
  "Brasília": "Brasilia",
  "Buddhism_in_Thailand": "Bouddhisme en Thaïlande",
  "Buddhist_cuisine": "Cuisine bouddhique",
  "Byte": "Byte",
  "Cacio_e_pepe": "Cacio e pepe",
  "Cahokia": "Cahokia",
  "Cairo": "Le Caire",
  "Can't_Buy_Me_Love": "Can't Buy Me Love",
  "Canada–United_States_border": "Frontière entre le Canada et les États-Unis",
  "Canberra": "Canberra",
  "Carbonara": "Pâtes à la carbonara",
  "Carthage": "Carthage",
  "Cattle": "Bos taurus",
  "Celesta": "Célesta",
  "Central_processing_unit": "CPU",
  "Challenger_Deep": "Challenger Deep",
  "Cheetah": "Guépard",
  "Chicha_morada": "Chicha morada",
  "Chinampa": "Chinampa",
  "Chinguetti": "Chinguetti",
  "Chlorophyll": "Chlorophylle",
  "Christopher_Columbus": "Christophe Colomb",
  "Chromosome": "Chromosome",
  "Cleopatra": "Cléopâtre VII",
  "Code_of_Hammurabi": "Code de Hammurabi",
  "Colosseum": "Colisée",
  "Common_ostrich": "Autruche d'Afrique",
  "Computer_mouse": "Souris (informatique)",
  "Coricancha": "Temple du Soleil (Cuzco)",
  "Couscous": "Couscous",
  "Cuneiform": "Écriture cunéiforme",
  "Cusco": "Cuzco",
  "Cyrus_Cylinder": "Cylindre de Cyrus",
  "DNA": "Acide désoxyribonucléique",
  "Danube": "Danube",
  "Day_of_the_Dead": "Jour des morts (Mexique)",
  "Dead_Sea": "Mer Morte",
  "Desert": "Désert",
  "Diamond": "Diamant",
  "Diomede_Islands": "Îles Diomède",
  "Dmitri_Mendeleev": "Dmitri Mendeleïev",
  "Douglas_Engelbart": "Douglas Engelbart",
  "Dresden_Codex": "Codex de Dresde",
  "ENIAC": "ENIAC",
  "Earth's_rotation": "Rotation de la Terre",
  "Earthworm": "Lumbricina",
  "Eiffel_Tower": "Tour Eiffel",
  "Electron": "Électron",
  "Elgin_Marbles": "Marbres d'Elgin",
  "Epic_of_Gilgamesh": "Épopée de Gilgamesh",
  "Evzones": "Evzones",
  "Fahrenheit": "Degré Fahrenheit",
  "Fall_of_Constantinople": "Chute de Constantinople",
  "Femur": "Fémur",
  "Fibonacci_sequence": "Suite de Fibonacci",
  "Flag_of_Canada": "Drapeau du Canada",
  "Flag_of_Mexico": "Drapeau du Mexique",
  "Flag_of_Nepal": "Drapeau du Népal",
  "Frappé_coffee": "Café frappé",
  "Frida_Kahlo": "Frida Kahlo",
  "Fundamental_interaction": "Interaction élémentaire",
  "Fushimi_Inari-taisha": "Fushimi Inari-taisha",
  "Geisha": "Geisha",
  "Geography_of_Saudi_Arabia": "Géographie de l'Arabie saoudite",
  "Ghana": "Ghana",
  "Ghana_Empire": "Empire du Ghana",
  "Gion": "Gion",
  "Glass": "Verre",
  "Gold": "Or",
  "Goldfish": "Poisson rouge",
  "Google_Chrome": "Google Chrome",
  "Grand_Palace": "Palais royal (Bangkok)",
  "Great_Barrier_Reef": "Grande Barrière de corail",
  "Great_Law_of_Peace": "Constitution iroquoise",
  "Great_Mosque_of_Djenné": "Grande mosquée de Djenné",
  "Great_Pyramid_of_Giza": "Pyramide de Khéops",
  "Great_Sphinx_of_Giza": "Sphinx de Gizeh",
  "Great_Wall_of_China": "Grande Muraille",
  "Great_Zimbabwe": "Grand Zimbabwe",
  "Guinea_pig": "Cavia porcellus",
  "Gunpowder": "Poudre noire",
  "HTTP": "Hypertext Transfer Protocol",
  "Hagia_Sophia": "Sainte-Sophie (Constantinople)",
  "Hangul": "Hangeul",
  "Hannibal": "Hannibal Barca",
  "Hanseatic_League": "Hanse",
  "Heart": "Cœur",
  "Herbivore": "Herbivore",
  "Hexadecimal": "Système hexadécimal",
  "History_of_chocolate": "Histoire de la culture du cacao",
  "Honey": "Miel",
  "Honey_bee": "Apis (insecte)",
  "Horned_helmet": "Casque à cornes",
  "House_of_Wisdom": "Maison de la sagesse",
  "Human_skin": "Peau humaine",
  "Human_tooth": "Dent (anatomie humaine)",
  "Hundred_Years'_War": "Guerre de Cent Ans",
  "Hydrogen": "Hydrogène",
  "Ibn_Battuta": "Ibn Battûta",
  "Ice": "Glace",
  "Inca_road_system": "Chemins incas",
  "Incandescent_light_bulb": "Lampe à incandescence",
  "Inclined_plane": "Plan incliné",
  "Indian_Ocean": "Océan Indien",
  "Industrial_Revolution": "Révolution industrielle",
  "Insect": "Insecte",
  "Inti_Raymi": "Inti Raymi",
  "Iron": "Fer",
  "Istanbul": "Istanbul",
  "James_Watt": "James Watt",
  "Japanese_tea_ceremony": "Cérémonie du thé japonaise",
  "Jemaa_el-Fnaa": "Place Jemaa el-Fna",
  "Justinian_I": "Justinien Ier",
  "Kairouan": "Kairouan",
  "Kaiseki": "Kaiseki",
  "Kangaroo": "Kangourou",
  "Kapnikarea": "Église de la Panagía Kapnikaréa",
  "Khan_el-Khalili": "Khân al-Khalili",
  "Kinkaku-ji": "Kinkaku-ji",
  "Kiyomizu-dera": "Kiyomizu-dera",
  "Koshari": "Kochari",
  "Koutoubia_Mosque": "Mosquée Koutoubia",
  "Kyoto": "Kyoto",
  "L'Anse_aux_Meadows": "L'Anse aux Meadows",
  "La_Paz": "La Paz",
  "Lake_Baikal": "Lac Baïkal",
  "Lake_Victoria": "Lac Victoria",
  "Landlocked_country": "Pays sans littoral",
  "Leptis_Magna": "Leptis Magna",
  "Lesotho": "Lesotho",
  "Light-year": "Année-lumière",
  "Lightning": "Foudre",
  "Lion": "Lion",
  "List_of_bones_of_the_human_skeleton": "Liste des os du squelette humain",
  "List_of_islands_by_area": "Liste d'îles par superficie",
  "Machu_Picchu": "Machu Picchu",
  "Macintosh_128K": "Macintosh 128K",
  "Maghrebi_mint_tea": "Thé à la menthe",
  "Magna_Carta": "Magna Carta",
  "Majapahit": "Majapahit",
  "Mansa_Musa": "Mansa Moussa",
  "Marie_Curie": "Marie Curie",
  "Marrakesh": "Marrakech",
  "Masinissa": "Massinissa",
  "Mass–energy_equivalence": "E=mc2",
  "Mauna_Kea": "Mauna Kea",
  "Maya_script": "Écriture maya",
  "Mayflower": "Mayflower",
  "Mercury_(planet)": "Mercure (planète)",
  "Mevlevi_order": "Ordre mevlevi",
  "Milky_Way": "Voie lactée",
  "Mitochondrion": "Mitochondrie",
  "Moai": "Moaï",
  "Mole_(sauce)": "Mole (sauce)",
  "Mona_Lisa": "La Joconde",
  "Mosque_of_Ibn_Tulun": "Mosquée Ibn Touloun",
  "Mount_Everest": "Everest",
  "Mount_Fuji": "Mont Fuji",
  "Mount_Kilimanjaro": "Kilimandjaro",
  "Moussaka": "Moussaka",
  "Mulukhiyah": "Mloukhiya",
  "Naguib_Mahfouz": "Naguib Mahfouz",
  "Nahuatl": "Nahuatl",
  "Nairobi_National_Park": "Parc national de Nairobi",
  "Name_day": "Fête du prénom",
  "Napoleon": "Napoléon Ier",
  "Nazar_(amulet)": "Nazar boncuk",
  "Netherlands": "Pays-Bas (pays constitutif)",
  "Newton_(unit)": "Newton (unité)",
  "Nile": "Nil",
  "Ninety-five_Theses": "95 thèses",
  "Nitrogen_fixation": "Fixation biologique du diazote",
  "Nocturnality": "Nocturne (comportement animal)",
  "North_Pole": "Pôle Nord",
  "Nowruz": "Norouz",
  "Nubian_pyramids": "Pyramides nubiennes",
  "Obelisk_of_Axum": "May-Hedja",
  "Octopus": "Octopoda",
  "Odyssey": "Odyssée",
  "Ohm": "Ohm (unité)",
  "Olympus_Mons": "Olympus Mons",
  "One_Hundred_Years_of_Solitude": "Cent Ans de solitude",
  "One_Thousand_and_One_Nights": "Les Mille et Une Nuits",
  "PH": "Potentiel hydrogène",
  "Pacific_Ocean": "Océan Pacifique",
  "Pad_thai": "Phat thai",
  "Panama_Canal": "Canal de Panama",
  "Pantheon,_Rome": "Panthéon (Rome)",
  "Parthenon": "Parthénon",
  "Peace_of_Westphalia": "Traités de Westphalie",
  "Pecorino_Romano": "Pecorino romano",
  "Penicillin": "Pénicilline",
  "Persepolis": "Persépolis",
  "Petra": "Pétra",
  "Phoenician_alphabet": "Alphabet phénicien",
  "Photosynthesis": "Photosynthèse",
  "Pi": "Pi",
  "Piano": "Piano",
  "Pilaf": "Riz pilaf",
  "Pompeii": "Pompéi",
  "Potato": "Pomme de terre",
  "Pretoria": "Pretoria",
  "Prime_number": "Nombre premier",
  "Printing_press": "Presse typographique",
  "Pueblo_Bonito": "Pueblo Bonito",
  "QWERTY": "QWERTY",
  "Quechuan_languages": "Quechua",
  "Queen_Victoria": "Victoria (reine)",
  "Quipu": "Quipu",
  "Rattanakosin_Kingdom": "Royaume de Rattanakosin",
  "Ray_Tomlinson": "Ray Tomlinson",
  "Rayleigh_scattering": "Diffusion Rayleigh",
  "Rebetiko": "Rébétiko",
  "Registan": "Régistan (Samarcande)",
  "Renaissance": "Renaissance",
  "Rideau_Canal": "Canal Rideau",
  "Rock-Hewn_Churches,_Lalibela": "Églises rupestres de Lalibela",
  "Roman_Republic": "République romaine",
  "Roman_roads": "Voie romaine",
  "Root": "Racine (botanique)",
  "Rosetta_Stone": "Pierre de Rosette",
  "Rust": "Rouille (oxyde)",
  "SOS": "SOS",
  "Sacsayhuamán": "Saqsaywaman",
  "Sahara": "Sahara",
  "Saltwater_crocodile": "Crocodile marin",
  "Samarkand": "Samarcande",
  "Samurai": "Samouraï",
  "Sardinia": "Sardaigne",
  "Saturn": "Saturne (planète)",
  "Scurvy": "Scorbut",
  "Self-portraits_by_Rembrandt": "Autoportraits de Rembrandt",
  "Sequoia_sempervirens": "Sequoia sempervirens",
  "Sequoyah": "Sequoyah",
  "Serfdom": "Servage",
  "Seven_hills_of_Rome": "Sept collines de Rome",
  "Sexagesimal": "Système sexagésimal",
  "Shah-i-Zinda": "Chah-e-Zindeh",
  "Silicon": "Silicium",
  "Silk_Road": "Route de la soie",
  "Simit": "Simit",
  "Sistine_Chapel_ceiling": "Plafond de la chapelle Sixtine",
  "Sodium_bicarbonate": "Bicarbonate de sodium",
  "Sodium_chloride": "Chlorure de sodium",
  "Sogdia": "Sogdiane",
  "Solomon_R._Guggenheim_Museum": "Musée Solomon-R.-Guggenheim",
  "Som_tam": "Salade de papaye verte",
  "Songhai_Empire": "Empire songhaï",
  "Songkran": "Songkran",
  "Sound": "Onde sonore",
  "Souvlaki": "Souvláki",
  "Speed_of_sound": "Vitesse du son",
  "Srivijaya": "Sriwijaya",
  "Stephenson's_Rocket": "Fusée de Stephenson",
  "Stockholm_archipelago": "Archipel de Stockholm",
  "Strait_of_Gibraltar": "Détroit de Gibraltar",
  "Suez_Canal": "Canal de Suez",
  "Sultan_Ahmed_Mosque": "Mosquée bleue",
  "Sun": "Soleil",
  "Suzani_(textile)": "Suzani",
  "Swahili_coast": "Zanguebar",
  "Sydney_Opera_House": "Opéra de Sydney",
  "Symphony_No._9_(Beethoven)": "Symphonie no 9 de Beethoven",
  "Tacos_al_pastor": "Al pastor",
  "Taghaza": "Teghazza",
  "Tajine": "Tajine",
  "Tanjia": "Tangia",
  "Taíno": "Taïnos",
  "Teahouse": "Salon de thé",
  "Temple_of_the_Emerald_Buddha": "Wat Phra Kaeo (Bangkok)",
  "Templo_Mayor": "Templo Mayor",
  "Ten_percent_of_the_brain_myth": "Mythe de l'utilisation incomplète du cerveau",
  "Tenochtitlan": "Mexico-Tenochtitlan",
  "Teotihuacan": "Teotihuacan",
  "Terracotta_Army": "Armée de terre cuite",
  "The_Canon_of_Medicine": "Qanûn (Avicenne)",
  "The_Great_Wave_off_Kanagawa": "La Grande Vague de Kanagawa",
  "The_Scream": "Le Cri",
  "The_Starry_Night": "La Nuit étoilée (1889)",
  "The_Tale_of_Genji": "Le Dit du Genji",
  "Things_Fall_Apart": "Tout s'effondre",
  "Thonburi_Kingdom": "Royaume de Thonburi",
  "Three_Sisters_(agriculture)": "Trois sœurs (agriculture)",
  "Tifinagh": "Tifinagh",
  "Tiger": "Tigre",
  "Timbuktu": "Tombouctou",
  "Time_in_France": "Heure en France",
  "Time_in_Russia": "Heure en Russie",
  "Timur": "Tamerlan",
  "Tokyo": "Tokyo",
  "Tom_yum": "Tom yum",
  "Tooth_enamel": "Émail dentaire",
  "Tornado": "Tornade",
  "Trans-Saharan_trade": "Commerce transsaharien",
  "Trevi_Fountain": "Fontaine de Trevi",
  "Trojan_Room_coffee_pot": "Trojan Room coffee pot",
  "Turing_test": "Test de Turing",
  "Turkish_bath": "Hammam",
  "Turkish_delight": "Loukoum",
  "Tutankhamun": "Toutânkhamon",
  "Tzistarakis_Mosque": "Mosquée Tzistarakis",
  "Uji": "Uji",
  "Ulugh_Beg": "Ulugh Beg",
  "Ulugh_Beg_Observatory": "Observatoire astronomique d'Ulugh Beg",
  "Umm_Kulthum": "Oum Kalthoum",
  "Units_of_information": "Unité de mesure en informatique",
  "University_of_Oxford": "Université d'Oxford",
  "University_of_al-Qarawiyyin": "Université Al Quaraouiyine",
  "Uzbek_cuisine": "Cuisine ouzbèke",
  "Vatican_City": "Vatican",
  "Venus": "Vénus (planète)",
  "Victoria_Falls": "Chutes Victoria",
  "Violin": "Violon",
  "Wai_(gesture)": "Wai",
  "Washington_Monument": "Washington Monument",
  "Wat_Pho": "Wat Pho",
  "Wellington": "Wellington",
  "White_blood_cell": "Leucocyte",
  "Wombat": "Wombat",
  "Women's_suffrage_in_New_Zealand": "Droit de vote des femmes en Nouvelle-Zélande",
  "Wreck_of_the_Titanic": "Épave du Titanic",
  "Wright_brothers": "Orville et Wilbur Wright",
  "Xochimilco": "Xochimilco",
  "Yam_(route)": "Örtöö",
  "Yuan_dynasty": "Dynastie Yuan",
  "Zheng_He": "Zheng He",
  "Zócalo": "Place de la Constitution (Mexico)",
};
