// © 2026 Qpio. All rights reserved.
// GENERATED — do not hand-edit. Rebuild: py tools/fetch_meta.py
//
// What each entity IS, in Wikipedia's own one-line description, plus a
// type derived from it. The type is what lets the app show shelves of
// real things — people, places, works — instead of category buttons.
//
// d = description · t = person | work | visit | go | event | idea

window.CURIO_META = {
  "API": {d:"Connection between computers or programs",t:"idea"},
  "ARPANET": {d:"Early packet switching network (1969–1990)",t:"person"},
  "Abdelkader_ibn_Muhieddine": {d:"Algerian religious and military leader (1808–1883)",t:"person"},
  "Aboriginal_Australians": {d:"One of the two categories of Indigenous Australians",t:"idea"},
  "Absolute_zero": {d:"Lowest theoretical temperature",t:"idea"},
  "Achilles_tendon": {d:"Tendon at the back of the lower leg",t:"idea"},
  "Ada_Lovelace": {d:"English mathematician (1815–1852)",t:"person"},
  "Adrenal_gland": {d:"Endocrine gland",t:"idea"},
  "Africa": {d:"Continent",t:"go"},
  "African_bush_elephant": {d:"Species of mammal",t:"idea"},
  "Ah!_vous_dirai-je,_maman": {d:"French children's song",t:"work"},
  "Ahmad_ibn_Ibrahim_al-Ghazi": {d:"16th century Imam and General of the Adal Sultanate",t:"person"},
  "Akan_goldweights": {d:"Ghanaian weight made of brass used by the Akans",t:"idea"},
  "Al-Azhar_Mosque": {d:"Mosque in Cairo, Egypt",t:"visit"},
  "Al-Khwarizmi": {d:"Islamic mathematician (c. 780 – c. 850)",t:"person"},
  "Al-Kindi": {d:"Muslim Arab philosopher, mathematician and physician (c. 801–873)",t:"person"},
  "Alaska_Purchase": {d:"1867 sale by Russia to the United States",t:"idea"},
  "Albert_Einstein": {d:"German-born theoretical physicist (1879–1955)",t:"person"},
  "Allotropes_of_carbon": {d:"Materials made only out of carbon",t:"idea"},
  "Almoravid_dynasty": {d:"1040–1147 Berber dynasty in west Africa and Iberia",t:"person"},
  "AlphaGo": {d:"Artificial intelligence that plays Go",t:"idea"},
  "Amanirenas": {d:"Queen of the Meroitic Kingdom of Kush",t:"person"},
  "Amazon_River": {d:"Major river in Northern South America",t:"go"},
  "Amelia_Earhart": {d:"American aviation pioneer (1897–1937)",t:"person"},
  "Amina_of_Zazzau": {d:"Ruler of Zazzau",t:"person"},
  "Ancient_Olympic_Games": {d:"Athletic competitions in ancient Greece",t:"idea"},
  "Andes": {d:"Mountain range in South America",t:"go"},
  "Andreas_Vesalius": {d:"Anatomist, physician and author (1514–1564)",t:"person"},
  "Angel_Falls": {d:"Tallest single drop waterfall in the world, Venezuela",t:"go"},
  "Angkor_Wat": {d:"Buddhist temple complex in Cambodia",t:"visit"},
  "Antarctica": {d:"Earth's southernmost continent",t:"go"},
  "Aperitivo": {d:"Alcoholic drink normally served before or after a meal",t:"idea"},
  "Apollo_11": {d:"First crewed Moon landing (1969)",t:"idea"},
  "Arctic_tern": {d:"Bird that breeds in the Arctic and subarctic and migrates to the Antarctic",t:"idea"},
  "Aryabhata": {d:"Indian mathematician-astronomer (476–550)",t:"person"},
  "Ashoka": {d:"Mauryan emperor from 269 to 232 BCE",t:"person"},
  "Atacama_Desert": {d:"Plateau on Pacific coast of South America",t:"go"},
  "Athenian_democracy": {d:"Government regime in ancient Athens",t:"idea"},
  "Athens": {d:"Capital and largest city of Greece",t:"go"},
  "Atomic_nucleus": {d:"Core of an atom composed of nucleons",t:"idea"},
  "Augustus": {d:"Roman emperor from 27 BC to AD 14",t:"person"},
  "Ayutthaya_Kingdom": {d:"Siamese kingdom in Southeast Asia (1351–1767)",t:"person"},
  "Aztec_Empire": {d:"Alliance of three Nahua city states in Mexico (1428–1521)",t:"person"},
  "Banana_equivalent_dose": {d:"Informal measurement of ionizing radiation exposure",t:"idea"},
  "Baqt": {d:"7th-century treaty between Makuria and Egypt",t:"event"},
  "Bat": {d:"Order of flying mammals",t:"idea"},
  "Battle_of_Adwa": {d:"1896 battle of the First Italo-Ethiopian War",t:"event"},
  "Battle_of_Ain_Jalut": {d:"1260 battle between the Mamluk Sultanate and the Mongol Empire",t:"person"},
  "Benin_Bronzes": {d:"Metal plaques and sculptures from the Kingdom of Benin",t:"person"},
  "Benjamin_Banneker": {d:"American scientist, surveyor and farmer (1731–1806)",t:"person"},
  "Berry_(botany)": {d:"Botanical fruit with fleshy pericarp, containing one or many seeds",t:"idea"},
  "Binary_number": {d:"Number expressed in the base-2 numeral system",t:"idea"},
  "Black_Death": {d:"1346–1353 pandemic in Eurasia and North Africa",t:"person"},
  "Blue_whale": {d:"Species of whale; largest animal known",t:"idea"},
  "Boiling_point": {d:"Characteristic temperature for a substance",t:"idea"},
  "Bolivian_Navy": {d:"Military unit",t:"idea"},
  "Bone_marrow": {d:"Semi-solid tissue in the spongy portions of bones",t:"idea"},
  "Bosporus": {d:"Narrow strait in northwestern Turkey",t:"go"},
  "Brahmagupta": {d:"Indian mathematician and astronomer (598–668)",t:"person"},
  "Brasília": {d:"Federal capital of Brazil",t:"go"},
  "Bristlecone_pine": {d:"Three species of pine trees native to the Western United States",t:"idea"},
  "Buddhist_cuisine": {d:"East Asian cuisine informed by Buddhism",t:"idea"},
  "Buganda": {d:"Bantu kingdom within Uganda",t:"person"},
  "Byte": {d:"Unit of digital information, usually 8 bits",t:"idea"},
  "Byte-pair_encoding": {d:"Adjacent characters (tokens) merge-based compression algorithm",t:"idea"},
  "Cacio_e_pepe": {d:"Italian pasta dish",t:"idea"},
  "Cahokia": {d:"Archaeological site in southwestern Illinois, US",t:"visit"},
  "Cairo": {d:"Capital and largest city of Egypt",t:"go"},
  "Can't_Buy_Me_Love": {d:"1964 single by the Beatles",t:"idea"},
  "Canada–United_States_border": {d:"International border in North America",t:"idea"},
  "Canberra": {d:"Capital city of Australia",t:"go"},
  "Capillary": {d:"Smallest type of blood vessel",t:"idea"},
  "Carbonara": {d:"Italian pasta dish",t:"idea"},
  "Carthage": {d:"Ancient city in Tunisia",t:"go"},
  "Cattle": {d:"Large, domesticated, cloven-hooved herbivores",t:"idea"},
  "Celesta": {d:"Struck idiophone operated by a keyboard",t:"idea"},
  "Central_processing_unit": {d:"Central computer component that executes instructions",t:"idea"},
  "Cerebellum": {d:"Structure at the rear of the vertebrate brain, beneath the cerebrum",t:"idea"},
  "Cervical_vertebrae": {d:"Vertebrae of the neck",t:"idea"},
  "Challenger_Deep": {d:"Deepest known point of Earth's seabed",t:"idea"},
  "Cheetah": {d:"Large feline of the genus Acinonyx",t:"idea"},
  "Chicha_morada": {d:"Prehispanic corn beverage from Peru",t:"idea"},
  "Chinampa": {d:"Type of Mesoamerican agriculture",t:"idea"},
  "Chinguetti": {d:"Place in Adrar Region, Mauritania",t:"go"},
  "Chlorophyll": {d:"Green pigments found in plants, algae and bacteria",t:"idea"},
  "Christopher_Columbus": {d:"Italian navigator and explorer (1451–1506)",t:"person"},
  "Chromosome": {d:"DNA molecule containing genetic material of a cell",t:"idea"},
  "Cleopatra": {d:"Pharaoh of Egypt from 51 to 30 BC",t:"person"},
  "Coca": {d:"Plant in the Erythroxylaceae family",t:"idea"},
  "Cochlea": {d:"Snail-shaped part of inner ear involved in hearing",t:"idea"},
  "Code_of_Hammurabi": {d:"Babylonian legal text",t:"work"},
  "Colosseum": {d:"Ancient Roman amphitheater in Rome",t:"idea"},
  "Common_ostrich": {d:"Species of flightless bird",t:"idea"},
  "Computer_mouse": {d:"Pointing device used to control a computer",t:"idea"},
  "Coricancha": {d:"Archaeological site in Peru",t:"visit"},
  "Cornea": {d:"Transparent front layer of the eye",t:"idea"},
  "Couscous": {d:"Traditional Maghrebi dish",t:"idea"},
  "Cuneiform": {d:"Writing system of the ancient Near East",t:"idea"},
  "Cusco": {d:"City in Peru",t:"go"},
  "Cyrus_Cylinder": {d:"Ancient clay cylinder with Akkadian cuneiform script",t:"idea"},
  "DNA": {d:"Molecule that carries genetic information",t:"idea"},
  "Dahomey_Amazons": {d:"Female regiment in the Kingdom of Dahomey",t:"person"},
  "Danube": {d:"Second-longest river in Europe",t:"go"},
  "Day_of_the_Dead": {d:"Mexican multi-day holiday",t:"idea"},
  "Dead_Sea": {d:"Salt lake in the Levant",t:"go"},
  "Deep_Blue_(chess_computer)": {d:"Chess-playing computer made by IBM",t:"idea"},
  "Desert": {d:"Area of land where little precipitation occurs",t:"idea"},
  "Diamond": {d:"Form of carbon",t:"idea"},
  "Diomede_Islands": {d:"Islands in the Bering Strait",t:"go"},
  "Djenné-Djenno": {d:"Historic site in Djenné Cercle, Mali",t:"idea"},
  "Dmitri_Mendeleev": {d:"Russian chemist (1834–1907)",t:"person"},
  "Domain_Name_System": {d:"System to identify resources on a network",t:"idea"},
  "Donald_Davies": {d:"British computer scientist (1924–2000)",t:"person"},
  "Douglas_Engelbart": {d:"American engineer and inventor (1925–2013)",t:"person"},
  "Dresden_Codex": {d:"Maya manuscript",t:"work"},
  "Dry_ice": {d:"Solid form of carbon dioxide",t:"idea"},
  "ELIZA": {d:"Natural language processing computer program",t:"idea"},
  "ENIAC": {d:"First electronic general-purpose digital computer",t:"person"},
  "Earth's_rotation": {d:"Rotation of Earth around its axis",t:"idea"},
  "Earthworm": {d:"Terrestrial invertebrate, order Opisthopora",t:"idea"},
  "Eiffel_Tower": {d:"Tower in Paris, France",t:"visit"},
  "Electron": {d:"Elementary particle with negative charge",t:"idea"},
  "Elgin_Marbles": {d:"Ancient Greek sculptures held in London",t:"idea"},
  "Elizabeth_J._Feinler": {d:"American information scientist (born 1931)",t:"person"},
  "Emmy_Noether": {d:"German mathematician (1882–1935)",t:"person"},
  "Epic_of_Gilgamesh": {d:"Epic poem from Mesopotamia",t:"work"},
  "Epidermis": {d:"Outermost of the three layers that make up the skin",t:"idea"},
  "Eratosthenes": {d:"Greek librarian, mathematician, geographer, and poet",t:"person"},
  "Ethiopian_calendar": {d:"Principal calendar used in Ethiopia and Eritrea",t:"idea"},
  "Evzones": {d:"Unit type of the Hellenic Army",t:"idea"},
  "Fahrenheit": {d:"Temperature scale",t:"idea"},
  "Fall_of_Constantinople": {d:"1453 Ottoman conquest of the Byzantine capital",t:"go"},
  "Fasil_Ghebbi": {d:"Fortified royal place of Gondarine period emperors in Ethiopia",t:"person"},
  "Femur": {d:"Thigh bone",t:"idea"},
  "Fibonacci": {d:"Italian mathematician (c. 1170 – c. 1240/50)",t:"person"},
  "Fibonacci_sequence": {d:"Numbers obtained by adding the two previous ones",t:"idea"},
  "Fish_sandwich": {d:"Sandwich or burger made with fish",t:"idea"},
  "Florence_Nightingale": {d:"English founder of modern nursing (1820–1910)",t:"person"},
  "Frappé_coffee": {d:"Greek iced coffee drink",t:"idea"},
  "Frida_Kahlo": {d:"Mexican painter (1907–1954)",t:"person"},
  "Fundamental_interaction": {d:"Most basic type of physical force",t:"idea"},
  "Fushimi_Inari-taisha": {d:"Shinto shrine near Kyoto, Japan",t:"idea"},
  "Gastric_acid": {d:"Digestive fluid formed in the stomach",t:"idea"},
  "Geisha": {d:"Japanese female entertainer and hostess",t:"idea"},
  "Ghana": {d:"Country in West Africa",t:"go"},
  "Ghana_Empire": {d:"Empire in West Africa from c. 200s to c. 1200s",t:"event"},
  "Gion": {d:"Geisha district in Kyoto, Japan",t:"idea"},
  "Glass": {d:"Transparent non-crystalline solid material",t:"idea"},
  "Global_Positioning_System": {d:"American satellite-based radio navigation service",t:"idea"},
  "Gluteus_maximus": {d:"Largest and most superficial of the three gluteal muscles",t:"idea"},
  "Gold": {d:"Chemical element with atomic number 79 (Au)",t:"idea"},
  "Golden_Stool": {d:"Throne of Asante kings",t:"person"},
  "Goldfish": {d:"Freshwater fish common in aquariums",t:"idea"},
  "Google_Chrome": {d:"Web browser developed by Google",t:"idea"},
  "Grand_Palace": {d:"Royal residence in Bangkok, Thailand",t:"idea"},
  "Graphics_processing_unit": {d:"Specialized electronic circuit that accelerates graphics",t:"idea"},
  "Great_Barrier_Reef": {d:"Coral reef system in Queensland, Australia",t:"person"},
  "Great_Law_of_Peace": {d:"Oral constitution of the Haudenosaunee Confederacy",t:"idea"},
  "Great_Mosque_of_Djenné": {d:"Mosque in Djenné, Mali",t:"visit"},
  "Great_Pyramid_of_Giza": {d:"Largest pyramid in the Giza Necropolis, Egypt",t:"visit"},
  "Great_Sphinx_of_Giza": {d:"Limestone statue of a reclining sphinx",t:"idea"},
  "Great_Wall_of_China": {d:"Series of fortifications in northern China",t:"idea"},
  "Great_Zimbabwe": {d:"Ruins of an ancient/medieval city in southeast Zimbabwe",t:"visit"},
  "Guinea_pig": {d:"Domesticated rodent from South America",t:"idea"},
  "Gunpowder": {d:"Type of firearm propellant",t:"idea"},
  "HTTP": {d:"Application layer protocol",t:"idea"},
  "HTTPS": {d:"HTTP extension supporting TLS encryption",t:"idea"},
  "Hagia_Sophia": {d:"Mosque and former church in Istanbul, Turkey",t:"visit"},
  "Hallucination_(artificial_intelligence)": {d:"Erroneous AI-generated content presented as true",t:"idea"},
  "Hangul": {d:"Native alphabet of the Korean language",t:"idea"},
  "Hannibal": {d:"Carthaginian general and statesman (247–183/181 BC)",t:"person"},
  "Hanseatic_League": {d:"1200s–1669 trade confederation in Northern Europe",t:"person"},
  "Harar": {d:"Capital of Harari Region, Ethiopia",t:"go"},
  "Heart": {d:"Organ found in humans and other animals",t:"idea"},
  "Hemoglobin": {d:"Metalloprotein that binds with oxygen",t:"idea"},
  "Herbivore": {d:"Organism that eats mostly or exclusively plant material",t:"idea"},
  "Hexadecimal": {d:"Base-16 numeric representation",t:"idea"},
  "Hippocampus": {d:"Vertebrate brain region",t:"go"},
  "Honey": {d:"Sweet and viscous substance made by bees",t:"idea"},
  "Honey_bee": {d:"Colonial flying insect",t:"idea"},
  "Horned_helmet": {d:"Helmet with horns",t:"idea"},
  "House_of_Wisdom": {d:"Abbasid-era library in Baghdad, modern-day Iraq",t:"visit"},
  "Huffman_coding": {d:"Technique to compress data",t:"idea"},
  "Human_microbiome": {d:"Microorganisms in or on human skin and biofluids",t:"idea"},
  "Human_skin": {d:"Organ covering the outside of the human body",t:"idea"},
  "Human_tooth": {d:"Calcified whitish structure in humans' mouths used to break down food",t:"idea"},
  "Hundred_Years'_War": {d:"Medieval Anglo-French conflicts, 1337–1453",t:"person"},
  "Hydrogen": {d:"Chemical element with atomic number 1 (H)",t:"idea"},
  "Hypatia": {d:"4th-century Alexandrian astronomer and mathematician",t:"person"},
  "IP_address": {d:"Numerical label used to identify a network interface in an IP network",t:"idea"},
  "Ibn_Battuta": {d:"Maghrebi traveller and scholar (1304–1368/1369)",t:"person"},
  "Ibn_al-Nafis": {d:"Arab polymath and physician (1213–1288)",t:"person"},
  "Ice": {d:"Frozen water; the solid state of water",t:"idea"},
  "Ife": {d:"City in Osun State, Nigeria",t:"go"},
  "Igbo-Ukwu": {d:"Place in Anambra, Nigeria",t:"idea"},
  "ImageNet": {d:"Image dataset",t:"idea"},
  "Inca_road_system": {d:"Transportation system of the Inca empire",t:"event"},
  "Incandescent_light_bulb": {d:"Electric light bulb with a resistively heated wire filament",t:"idea"},
  "Inclined_plane": {d:"Tilted flat supporting surface",t:"idea"},
  "Indian_Ocean": {d:"Oceanic division",t:"idea"},
  "Industrial_Revolution": {d:"1760–1840 agrarian to industrial era shift",t:"person"},
  "Influence_of_William_Shakespeare": {d:"Impact of English playwright and poet",t:"person"},
  "Insect": {d:"Class of arthropods",t:"idea"},
  "Inti_Raymi": {d:"Incan religious festival",t:"idea"},
  "Iron": {d:"Chemical element with atomic number 26 (Fe)",t:"idea"},
  "Ishango_bone": {d:"Paleolithic artifact from Congo",t:"idea"},
  "Istanbul": {d:"Largest city in Turkey",t:"go"},
  "James_Watt": {d:"Scottish inventor, engineer and chemist (1736–1819)",t:"person"},
  "Japanese_tea_ceremony": {d:"Traditional Japanese ceremony",t:"idea"},
  "Jemaa_el-Fnaa": {d:"Moroccan cultural heritage site",t:"visit"},
  "Joseph_Fourier": {d:"French mathematician and physicist (1768–1830)",t:"person"},
  "Joy_Buolamwini": {d:"Computer scientist and digital activist",t:"person"},
  "Justinian_I": {d:"Roman emperor from 527 to 565",t:"person"},
  "Kairouan": {d:"City in Kairouan Governorate, Tunisia",t:"go"},
  "Kaiseki": {d:"Traditional multi-course Japanese dinner",t:"idea"},
  "Kanem–Bornu_Empire": {d:"Empire around Lake Chad, Africa, c. 700–1902",t:"person"},
  "Kangaroo": {d:"Marsupial of the family Macropodidae",t:"idea"},
  "Kapnikarea": {d:"Byzantine church in Athens, Greece",t:"visit"},
  "Katherine_Johnson": {d:"American mathematician (1918–2020)",t:"person"},
  "Khan_el-Khalili": {d:"Major souk in Cairo",t:"idea"},
  "Kilwa_Kisiwani": {d:"Island, hamlet and former Swahili city-state in Lindi Region, Tanzania",t:"go"},
  "Kilwa_Sultanate": {d:"Swahili sultanate (957–1513)",t:"person"},
  "Kingdom_of_Aksum": {d:"Polity in Africa and Arabia before 960",t:"idea"},
  "Kingdom_of_Kongo": {d:"1390–1914 state in Central Africa; Portuguese vassal from 1857",t:"person"},
  "Kingdom_of_Mutapa": {d:"Empire in Southern Africa from the 15th to late-19th centuries",t:"event"},
  "Kinkaku-ji": {d:"Zen Buddhist temple in Kyoto, Japan",t:"visit"},
  "Kiyomizu-dera": {d:"Buddhist temple in Kyoto, Japan",t:"visit"},
  "Koshari": {d:"National dish of Egypt",t:"idea"},
  "Koutoubia_Mosque": {d:"Mosque in Marrakesh, Morocco",t:"visit"},
  "Kyoto": {d:"City in the Kansai region of Japan",t:"go"},
  "L'Anse_aux_Meadows": {d:"Norse archaeological site in Newfoundland, Canada",t:"visit"},
  "La_Paz": {d:"Seat of government of Bolivia",t:"idea"},
  "Lake_Baikal": {d:"Freshwater rift lake in Russia",t:"go"},
  "Lake_Victoria": {d:"Lake in East-central Africa",t:"go"},
  "Landlocked_country": {d:"Country with no ocean coastline",t:"go"},
  "Large_intestine": {d:"Last part of the digestive system in vertebrates",t:"idea"},
  "Large_language_model": {d:"Type of machine learning model",t:"idea"},
  "Leptis_Magna": {d:"Ancient city in modern Libya",t:"go"},
  "Lesotho": {d:"Country in Southern Africa",t:"go"},
  "Light-year": {d:"Distance that light travels in one year",t:"idea"},
  "Lightning": {d:"Weather phenomenon involving electrostatic discharge",t:"idea"},
  "Lion": {d:"Large cat native to Africa and India",t:"idea"},
  "Liver": {d:"Vertebrate organ involved in metabolism",t:"idea"},
  "Lukasa": {d:"Memory device of the Luba people",t:"idea"},
  "Lusona": {d:"Ideographic art tradition in parts of Africa",t:"idea"},
  "Machine_learning": {d:"Subset of artificial intelligence",t:"idea"},
  "Machu_Picchu": {d:"15th-century Inca citadel in Peru",t:"idea"},
  "Macintosh_128K": {d:"First model of Apple's Macintosh computer line",t:"idea"},
  "Madhava_of_Sangamagrama": {d:"Indian mathematician and astronomer (1340–1425)",t:"person"},
  "Maghrebi_mint_tea": {d:"North African green tea",t:"idea"},
  "Magna_Carta": {d:"English charter of freedoms made in 1215",t:"idea"},
  "Majapahit": {d:"Javanese empire from 1292 to 1527",t:"event"},
  "Mansa_Musa": {d:"Ruler of Mali from c. 1312 to c. 1337",t:"person"},
  "Mapungubwe": {d:"Ancient kingdom in the Limpopo-Shashe Basin, northern South Africa",t:"person"},
  "Marie_Curie": {d:"Polish-French physicist and chemist (1867–1934)",t:"person"},
  "Marrakesh": {d:"City in Marrakesh–Safi, Morocco",t:"go"},
  "Maryam_Mirzakhani": {d:"Iranian mathematician (1977–2017)",t:"person"},
  "Masinissa": {d:"First King of Numidia from 202 BC to 148 BC",t:"person"},
  "Mass–energy_equivalence": {d:"Physics concept expressed as E = mc²",t:"idea"},
  "Mauna_Kea": {d:"Hawaiian volcano",t:"go"},
  "Maya_numerals": {d:"System used by the ancient Mayan civilization to represent numbers and dates",t:"event"},
  "Maya_script": {d:"Writing system of the Maya civilization",t:"event"},
  "Mayflower": {d:"17th-century ship of American colonists",t:"idea"},
  "Melanin": {d:"Group of natural pigments found in most organisms",t:"idea"},
  "Mercury_(planet)": {d:"First planet from the Sun",t:"idea"},
  "Merina_Kingdom": {d:"1540–1897 kingdom in Madagascar",t:"person"},
  "Meroitic_script": {d:"Two alphasyllabaric scripts for the extinct Meroitic language",t:"idea"},
  "Mevlevi_order": {d:"Sufi order in Islam",t:"idea"},
  "Milky_Way": {d:"Galaxy containing the Solar System",t:"idea"},
  "Mitochondrion": {d:"Organelle in eukaryotic cells responsible for respiration",t:"idea"},
  "Moai": {d:"Monolithic statues on Easter Island",t:"go"},
  "Model_Context_Protocol": {d:"Protocol for communicating between LLMs and applications",t:"idea"},
  "Mole_(sauce)": {d:"Mexican sauce and marinade",t:"idea"},
  "Mona_Lisa": {d:"Painting by Leonardo da Vinci",t:"work"},
  "Mosque_of_Ibn_Tulun": {d:"Mosque in Cairo, Egypt",t:"visit"},
  "Mount_Everest": {d:"Earth's highest mountain",t:"go"},
  "Mount_Fuji": {d:"Volcano in Japan",t:"go"},
  "Mount_Kilimanjaro": {d:"Mountain in Tanzania, highest in Africa",t:"go"},
  "Moussaka": {d:"Dish of layered vegetables, sauce and meat",t:"idea"},
  "Mulukhiyah": {d:"Jute-leaf dish from Egypt",t:"idea"},
  "Naguib_Mahfouz": {d:"Egyptian writer (1911–2006)",t:"person"},
  "Nahuatl": {d:"Uto-Aztecan language of Mexico",t:"idea"},
  "Nairobi_National_Park": {d:"First national park in Kenya",t:"go"},
  "Name_day": {d:"Traditional celebration in Christianity",t:"idea"},
  "Nana_Asma'u": {d:"Nigerian princess and poet",t:"person"},
  "Napoleon": {d:"French general and emperor (1769–1821)",t:"person"},
  "Nazar_(amulet)": {d:"Eye-shaped amulet believed to protect against the evil eye",t:"idea"},
  "Nephron": {d:"Microscopic structural and functional unit of the kidney",t:"idea"},
  "Netherlands": {d:"Country in Northwestern Europe and the Caribbean",t:"go"},
  "Newton_(unit)": {d:"Unit of force in physics",t:"idea"},
  "Nii_Quaynor": {d:"Ghanaian scientist and engineer",t:"person"},
  "Nile": {d:"Major river in northeast Africa",t:"go"},
  "Ninety-five_Theses": {d:"Disputation by Martin Luther on indulgences",t:"idea"},
  "Nitrogen_fixation": {d:"Conversion of dinitrogen into ammonia",t:"idea"},
  "Nocturnality": {d:"Behavior characterized by activity during the night and sleeping during the day",t:"idea"},
  "Nok_culture": {d:"Ancient civilization of Nigeria",t:"event"},
  "North_Pole": {d:"Northernmost point on Earth",t:"idea"},
  "Nowruz": {d:"New Year's Day on the Iranian calendars",t:"idea"},
  "Nubian_pyramids": {d:"Pyramids built by ancient Kushite kingdoms in present-day northern Sudan",t:"person"},
  "Nzinga_of_Ndongo_and_Matamba": {d:"Ambundu queen in Angola (c. 1583–1663)",t:"person"},
  "Obelisk_of_Axum": {d:"4th-century phonolite stele in Axum, Tigray Region, Ethiopia",t:"go"},
  "Octopus": {d:"Soft-bodied eight-limbed order of molluscs",t:"idea"},
  "Odyssey": {d:"Epic poem attributed to Homer",t:"work"},
  "Ohm": {d:"SI derived unit of electrical resistance",t:"idea"},
  "Olympus_Mons": {d:"Martian volcano, highest point on Mars",t:"go"},
  "Omar_Khayyam": {d:"Persian polymath and poet (1048–1131)",t:"person"},
  "One_Hundred_Years_of_Solitude": {d:"1967 novel by Gabriel García Márquez",t:"work"},
  "One_Thousand_and_One_Nights": {d:"Collection of Middle Eastern folk tales",t:"idea"},
  "Open-source_software": {d:"Software with publicly available source code",t:"idea"},
  "Optical_fiber": {d:"Light-conducting fiber",t:"idea"},
  "Oyo_Empire": {d:"Former empire in present day Nigeria and Benin Republic",t:"event"},
  "PH": {d:"Measure of the level of acidity or basicity of an aqueous solution",t:"idea"},
  "Pacific_Ocean": {d:"Largest ocean on Earth",t:"go"},
  "Packet_switching": {d:"Method for transmitting data over a computer network",t:"idea"},
  "Pad_thai": {d:"Stir-fried noodle dish from Thailand",t:"idea"},
  "Panama_Canal": {d:"Shipping route across Central America",t:"idea"},
  "Pancreas": {d:"Organ of the digestive system and endocrine system of vertebrates",t:"idea"},
  "Pantheon,_Rome": {d:"Roman temple, later church, in Rome",t:"visit"},
  "Parthenon": {d:"Temple on the Athenian Acropolis, Greece",t:"visit"},
  "Peace_of_Westphalia": {d:"1648 treaties ending the Thirty Years' War and Eighty Years' War",t:"event"},
  "Pecorino_Romano": {d:"Hard, salty Italian cheese, often grated",t:"idea"},
  "Penicillin": {d:"Group of antibiotics derived from fungi",t:"idea"},
  "Persepolis": {d:"Ceremonial capital of the Achaemenid Empire",t:"go"},
  "Petra": {d:"Ancient rock-cut historical city in Jordan",t:"go"},
  "Phoenician_alphabet": {d:"Writing system used c. 1050 to 146 BC",t:"idea"},
  "Photosynthesis": {d:"Biological process to convert light into chemical energy",t:"idea"},
  "Pi": {d:"Number, approximately 3.14",t:"idea"},
  "Piano": {d:"Keyboard instrument",t:"idea"},
  "Pilaf": {d:"Rice dish in which grains do not stick",t:"idea"},
  "Piye": {d:"Ancient Kushite king and pharaoh",t:"person"},
  "Plimpton_322": {d:"Babylonian clay tablet of numbers in Pythagorean triples",t:"idea"},
  "Pompeii": {d:"Ancient city near modern Naples, Italy",t:"go"},
  "Potato": {d:"Starchy tuber used as a staple food",t:"idea"},
  "Pretoria": {d:"Executive capital of South Africa",t:"go"},
  "Prime_number": {d:"Number divisible only by 1 and itself",t:"idea"},
  "Printing_press": {d:"Machine for applying ink under pressure",t:"idea"},
  "Problem_of_points": {d:"Problem in probability theory",t:"idea"},
  "Prompt_engineering": {d:"Structuring text as input to generative artificial intelligence",t:"work"},
  "Public-key_cryptography": {d:"Cryptographic system with public and private keys",t:"idea"},
  "Pueblo_Bonito": {d:"Ancient Puebloan ruin in New Mexico",t:"idea"},
  "Pulmonary_alveolus": {d:"Hollow cavity found in the lungs",t:"idea"},
  "Pythagorean_theorem": {d:"Relation between sides of a right triangle",t:"idea"},
  "QWERTY": {d:"Keyboard layout for Latin-script alphabets",t:"idea"},
  "Quechuan_languages": {d:"Language family of the Andes in South America",t:"idea"},
  "Queen_Victoria": {d:"Queen of the United Kingdom from 1837 to 1901",t:"person"},
  "Quipu": {d:"Andean record-keeping system using knotted cords",t:"idea"},
  "RSA_cryptosystem": {d:"Algorithm for public-key cryptography",t:"idea"},
  "Radia_Perlman": {d:"American software designer and network engineer",t:"person"},
  "Rattanakosin_Kingdom": {d:"Period of Thai history",t:"event"},
  "Ray_Tomlinson": {d:"American computer programmer (1941–2016)",t:"person"},
  "Rayleigh_scattering": {d:"Light scattering by small particles",t:"idea"},
  "Rebetiko": {d:"Greek music genre",t:"idea"},
  "Red_blood_cell": {d:"Oxygen-delivering blood cell and the most common type of blood cell",t:"idea"},
  "Reed–Solomon_error_correction": {d:"Error-correcting codes",t:"idea"},
  "Registan": {d:"Historical center of Samarkand, Uzbekistan",t:"idea"},
  "Renaissance": {d:"European cultural period of the 14th to 17th centuries",t:"event"},
  "Retina": {d:"Part of the eye",t:"idea"},
  "Rhind_Mathematical_Papyrus": {d:"Ancient Egyptian mathematical document",t:"idea"},
  "Rideau_Canal": {d:"Canal in Canada",t:"idea"},
  "Rock-Hewn_Churches,_Lalibela": {d:"Eleven monolithic churches found in Lalibela, Amhara Region, Ethiopia",t:"go"},
  "Roman_Republic": {d:"Period of Roman history (c. 509 – 27 BC)",t:"event"},
  "Roman_roads": {d:"Roads built in service of the ancient Roman civilization",t:"event"},
  "Root": {d:"Basal organ of a vascular plant",t:"idea"},
  "Rosetta_Stone": {d:"Egyptian stele with three versions of a 196 BC decree",t:"idea"},
  "Router_(computing)": {d:"Device that forwards data packets between computer networks",t:"idea"},
  "Rust": {d:"Type of iron oxide",t:"idea"},
  "SOS": {d:"International Morse code distress signal for help",t:"idea"},
  "Sacsayhuamán": {d:"Archaeological site near Cusco, Peru",t:"visit"},
  "Sahara": {d:"Desert on the African continent",t:"go"},
  "Saltwater_crocodile": {d:"Species of reptile",t:"idea"},
  "Samarkand": {d:"City in southeastern Uzbekistan",t:"go"},
  "Samsa_(food)": {d:"Savoury pie",t:"idea"},
  "Samurai": {d:"Japanese warrior class",t:"idea"},
  "Sardinia": {d:"Island in the Mediterranean and region of Italy",t:"go"},
  "Saturn": {d:"Sixth planet from the Sun",t:"idea"},
  "Sciatic_nerve": {d:"Large nerve in humans and other animals",t:"idea"},
  "Scurvy": {d:"Disease resulting from a lack of vitamin C",t:"idea"},
  "Seki_Takakazu": {d:"Japanese mathematician (c. 1642–1708)",t:"person"},
  "Semicircular_canals": {d:"Organ located in innermost part of ear",t:"idea"},
  "Sequoia_sempervirens": {d:"Species of tree",t:"idea"},
  "Sequoyah": {d:"Cherokee polymath and creator of the Cherokee syllabary",t:"idea"},
  "Serfdom": {d:"Status of peasants under feudalism",t:"idea"},
  "Server_(computing)": {d:"Computer providing a central resource or service",t:"idea"},
  "Seven_Bridges_of_Königsberg": {d:"Classic problem in graph theory",t:"idea"},
  "Seven_hills_of_Rome": {d:"Geographical heart of Rome, Italy, within the walls of the city",t:"go"},
  "Sexagesimal": {d:"Base sixty numeral system",t:"idea"},
  "Shah-i-Zinda": {d:"Necropolis in Samarkand, Uzbekistan",t:"idea"},
  "Shaka": {d:"Zulu king from 1816 to 1828",t:"person"},
  "Silicon": {d:"Chemical element with atomic number 14 (Si)",t:"idea"},
  "Silk_Road": {d:"Historical network of Eurasian trade routes",t:"idea"},
  "Simit": {d:"Circular bread from Turkey and the Balkans",t:"idea"},
  "Sine_and_cosine": {d:"Fundamental trigonometric functions",t:"idea"},
  "Sinoatrial_node": {d:"Group of cells in the wall of the heart",t:"idea"},
  "Sistine_Chapel_ceiling": {d:"Cycle of frescoes by Michelangelo",t:"idea"},
  "Small_intestine": {d:"Organ in the gastrointestinal tract",t:"idea"},
  "Sodium_bicarbonate": {d:"Chemical compound",t:"idea"},
  "Sodium_chloride": {d:"Chemical compound with formula NaCl",t:"idea"},
  "Sogdia": {d:"Ancient Iranian civilization (6th century BCE – 11th century CE)",t:"event"},
  "Solomon_R._Guggenheim_Museum": {d:"Art museum in Manhattan, New York",t:"visit"},
  "Som_tam": {d:"Spicy salad made from unripe papaya",t:"idea"},
  "Songhai_Empire": {d:"Empire in West Africa from c. 1464 to 1591",t:"event"},
  "Songkran": {d:"Traditional Thai New Year's holiday",t:"idea"},
  "Sound": {d:"Audible vibration that travels via pressure waves in matter",t:"idea"},
  "Souvlaki": {d:"Greek fast food",t:"idea"},
  "Speed_of_sound": {d:"Speed of sound wave through elastic medium",t:"idea"},
  "Spleen": {d:"Immune organ that filters blood",t:"idea"},
  "Srivijaya": {d:"Empire based on Sumatra (c. 671–1025 AD)",t:"person"},
  "Stapes": {d:"Bone of the middle ear",t:"idea"},
  "Stephenson's_Rocket": {d:"Steam locomotive by Robert Stephenson in 1829",t:"idea"},
  "Stockholm_archipelago": {d:"Archipelago east of Stockholm, Sweden",t:"go"},
  "Strait_of_Gibraltar": {d:"Strait connecting the Atlantic to the Mediterranean",t:"go"},
  "Submarine_communications_cable": {d:"Transoceanic communication line placed on the seabed",t:"idea"},
  "Suez_Canal": {d:"Artificial sea-level waterway in Egypt",t:"go"},
  "Sultan_Ahmed_Mosque": {d:"17th-century mosque in Turkey",t:"visit"},
  "Sun": {d:"Star at the centre of the Solar System",t:"idea"},
  "Sundiata_Keita": {d:"Founder and first ruler of the Mali Empire",t:"person"},
  "Sunlight": {d:"Light emitted by the Sun",t:"idea"},
  "Suzani_(textile)": {d:"Embroidered tribal textile made in Central Asia and Iran",t:"idea"},
  "Swahili_coast": {d:"Coastal area of the Indian Ocean in southeast Africa",t:"go"},
  "Sydney_Opera_House": {d:"Performing arts centre in Australia",t:"idea"},
  "Symphony_No._9_(Beethoven)": {d:"1824 symphony by Ludwig van Beethoven",t:"work"},
  "Ta'ameya": {d:"Egyptian fava bean fritter",t:"idea"},
  "Tacos_al_pastor": {d:"Mexican spit-grilled pork seasoned with adobada",t:"idea"},
  "Taghaza": {d:"Abandoned salt-mining settlement in Mali",t:"idea"},
  "Tajine": {d:"Maghrebi dish prepared in the earthenware pot of the same name",t:"idea"},
  "Tanjia": {d:"Cooking vessel",t:"idea"},
  "Taíno": {d:"Indigenous people of the Caribbean",t:"idea"},
  "Teahouse": {d:"Cafe-type business serving tea",t:"idea"},
  "Temple_of_the_Emerald_Buddha": {d:"Buddhist temple in Bangkok, Thailand",t:"visit"},
  "Templo_Mayor": {d:"Former Aztec temple in Tenochtitlan (now Mexico City)",t:"visit"},
  "Ten_percent_of_the_brain_myth": {d:"Myth regarding human brain usage",t:"idea"},
  "Tenochtitlan": {d:"Former city-state in the Valley of Mexico",t:"go"},
  "Teotihuacan": {d:"Ancient Mesoamerican city",t:"go"},
  "Terracotta_Army": {d:"Collection of ancient Chinese military statues",t:"idea"},
  "The_Canon_of_Medicine": {d:"1025 Encyclopedia of medicine compiled by Avicenna",t:"idea"},
  "The_Great_Wave_off_Kanagawa": {d:"Woodblock print by Hokusai (1831)",t:"idea"},
  "The_Nine_Chapters_on_the_Mathematical_Art": {d:"Ancient Chinese mathematics text",t:"work"},
  "The_Scream": {d:"1893 painting by Edvard Munch",t:"work"},
  "The_Starry_Night": {d:"1889 painting by Vincent van Gogh",t:"work"},
  "The_Tale_of_Genji": {d:"Classic work of Japanese literature",t:"idea"},
  "Things_Fall_Apart": {d:"1958 novel by Chinua Achebe",t:"work"},
  "Thonburi_Kingdom": {d:"Kingdom in Southeast Asia (1767–1782)",t:"person"},
  "Thoracic_diaphragm": {d:"Sheet of internal skeletal muscle",t:"idea"},
  "Three_Sisters_(agriculture)": {d:"Agricultural technique of Indigenous people in the Americas",t:"idea"},
  "Thymus": {d:"Endocrine gland",t:"idea"},
  "Thyroid": {d:"Endocrine gland in the neck",t:"idea"},
  "Tideway": {d:"Part of the River Thames subject to tides",t:"go"},
  "Tifinagh": {d:"Script used for Berber languages",t:"idea"},
  "Tiger": {d:"Species of large cat",t:"idea"},
  "Tim_Berners-Lee": {d:"English computer scientist (born 1955)",t:"person"},
  "Timbuktu": {d:"City in Tombouctou Region, Mali",t:"go"},
  "Timbuktu_Manuscripts": {d:"Manuscripts preserved in Timbuktu, Mali",t:"idea"},
  "Time_in_Russia": {d:"Time spanning Europe and Asia",t:"idea"},
  "Timur": {d:"Turco-Mongol conqueror (1320s–1405)",t:"person"},
  "Tokyo": {d:"Capital and most populous city in Japan",t:"go"},
  "Tom_yum": {d:"Thai soup",t:"idea"},
  "Tooth_enamel": {d:"Major tissue that makes up part of the tooth in humans and many animals",t:"idea"},
  "Tornado": {d:"Violently rotating column of air",t:"idea"},
  "Training,_validation,_and_test_data_sets": {d:"Tasks in machine learning",t:"idea"},
  "Trans-Saharan_trade": {d:"Trade between sub-Saharan Africa and North Africa",t:"idea"},
  "Transformer_(deep_learning)": {d:"Algorithm for modelling sequential data",t:"idea"},
  "Trevi_Fountain": {d:"Fountain in Rome, Italy",t:"idea"},
  "Trojan_Room_coffee_pot": {d:"Predecessor of the webcam",t:"idea"},
  "Turing_test": {d:"Test of a machine's ability to imitate human intelligence",t:"idea"},
  "Turkish_bath": {d:"Place of public bathing common in Muslim societies",t:"idea"},
  "Turkish_delight": {d:"Gelatinous candy",t:"idea"},
  "Tutankhamun": {d:"Pharaoh of Egypt from 1333 to 1324 BC",t:"person"},
  "Twelve-angled_stone": {d:"Incan archaeological artifact in Peru",t:"visit"},
  "Tzistarakis_Mosque": {d:"Former mosque, now museum, in Athens, Greece",t:"visit"},
  "Uji": {d:"City in Kansai, Japan",t:"go"},
  "Ulugh_Beg": {d:"Timurid sultan, astronomer and mathematician (1394–1449)",t:"person"},
  "Ulugh_Beg_Observatory": {d:"Observatory in Samarkand, Uzbekistan",t:"visit"},
  "Umm_Kulthum": {d:"Egyptian singer-songwriter and actress (1904–1975)",t:"person"},
  "Units_of_information": {d:"Unit of measure for digital data",t:"idea"},
  "University_of_Oxford": {d:"Collegiate research university in England",t:"idea"},
  "University_of_al-Qarawiyyin": {d:"University in Fez, Morocco",t:"idea"},
  "Uzbek_cuisine": {d:"Culinary traditions of Uzbekistan",t:"idea"},
  "Vagus_nerve": {d:"Main nerve of the parasympathetic nervous system",t:"idea"},
  "Vatican_City": {d:"Enclaved Holy See's independent city-state",t:"go"},
  "Venus": {d:"Second planet from the Sun",t:"idea"},
  "Vibe_coding": {d:"AI-dependent computer programming",t:"idea"},
  "Victoria_Falls": {d:"Waterfall on the Zambezi River in Zambia and Zimbabwe",t:"go"},
  "Vint_Cerf": {d:"American computer scientist and Internet pioneer (born 1943)",t:"person"},
  "Violin": {d:"Bowed string instrument",t:"idea"},
  "Wai_(gesture)": {d:"Gesture used in Thailand",t:"idea"},
  "Walls_of_Benin": {d:"Historic moat in Nigeria",t:"idea"},
  "Wang_Zhenyi_(astronomer)": {d:"Chinese astronomer (1768–1797)",t:"person"},
  "Washington_Monument": {d:"U.S. national memorial in Washington, D.C.",t:"visit"},
  "Wat_Pho": {d:"Buddhist temple in Phra Nakhon district, Bangkok, Thailand",t:"visit"},
  "Web_browser": {d:"Software used to access websites",t:"idea"},
  "Web_crawler": {d:"Software that systematically browses the World Wide Web",t:"idea"},
  "Wellington": {d:"Capital city of New Zealand",t:"go"},
  "White_blood_cell": {d:"Type of cells of the immunological system",t:"idea"},
  "Wi-Fi": {d:"Family of wireless network protocols",t:"idea"},
  "Wilhelm_Röntgen": {d:"German physicist (1845–1923)",t:"person"},
  "William_Harvey": {d:"English physician (1578–1657)",t:"person"},
  "Wombat": {d:"Species of marsupial native to Australia",t:"idea"},
  "World_Wide_Web": {d:"Linked hypertext system on the Internet",t:"idea"},
  "Wreck_of_the_Titanic": {d:"Shipwreck in the North Atlantic Ocean",t:"go"},
  "Wright_brothers": {d:"American aviation pioneers, inventors of the airplane",t:"person"},
  "Xochimilco": {d:"Borough in Mexico City, Mexico",t:"go"},
  "Yaa_Asantewaa": {d:"Ashanti queen mother and military leader",t:"person"},
  "Yam_(route)": {d:"Postal service system originating from the Mongol period",t:"event"},
  "Yoruba_numerals": {d:"Numerals in Yorùbá Language",t:"idea"},
  "Yuan_dynasty": {d:"Mongol-led dynasty of China (1271–1368)",t:"person"},
  "Zheng_He": {d:"Chinese admiral and diplomat (1371–1433/1435)",t:"person"},
  "Zimbabwe_Bird": {d:"National emblem of Zimbabwe",t:"idea"},
  "Zu_Chongzhi": {d:"Chinese mathematician-astronomer (429–500)",t:"person"},
  "Zócalo": {d:"Plaza de la Constitución, Mexico City",t:"go"},
};
