// © 2026 Qpio. All rights reserved.
// GENERATED — do not hand-edit. Rebuild: py tools/fetch_meta.py
//
// What each entity IS, in Wikipedia's own one-line description, plus a
// type derived from it. The type is what lets the app show shelves of
// real things — people, places, works — instead of category buttons.
//
// d = description · t = person | work | visit | go | event | idea

window.CURIO_META = {
  "1883_eruption_of_Krakatoa": {d:"Large volcanic eruption in the Sunda Strait",t:"go"},
  "API": {d:"Connection between computers or programs",t:"idea"},
  "ARPANET": {d:"Early packet switching network (1969–1990)",t:"person"},
  "A_Trip_to_the_Moon": {d:"1902 French short film by Georges Méliès",t:"work"},
  "Abd_al-Rahman_al-Sufi": {d:"Persian astronomer (903–986)",t:"person"},
  "Abdelkader_ibn_Muhieddine": {d:"Algerian religious and military leader (1808–1883)",t:"person"},
  "Aboriginal_Australians": {d:"One of the two categories of Indigenous Australians",t:"idea"},
  "Absolute_zero": {d:"Lowest theoretical temperature",t:"idea"},
  "Achilles_tendon": {d:"Tendon at the back of the lower leg",t:"idea"},
  "Active_noise_control": {d:"Method for reducing unwanted sound",t:"idea"},
  "Ada_Lovelace": {d:"English mathematician (1815–1852)",t:"person"},
  "Adansonia": {d:"Genus of trees known as baobab",t:"idea"},
  "Addis_Ababa": {d:"Capital and largest city of Ethiopia",t:"go"},
  "Adrenal_gland": {d:"Endocrine gland",t:"idea"},
  "Aerogel": {d:"Synthetic ultralight solid material",t:"idea"},
  "Africa": {d:"Continent",t:"go"},
  "African_bush_elephant": {d:"Species of mammal",t:"idea"},
  "Ah!_vous_dirai-je,_maman": {d:"French children's song",t:"work"},
  "Ahmad_ibn_Ibrahim_al-Ghazi": {d:"16th century Imam and General of the Adal Sultanate",t:"person"},
  "Akan_goldweights": {d:"Ghanaian weight made of brass used by the Akans",t:"idea"},
  "Al-Azhar_Mosque": {d:"Mosque in Cairo, Egypt",t:"visit"},
  "Al-Khwarizmi": {d:"Islamic mathematician (c. 780 – c. 850)",t:"person"},
  "Al-Kindi": {d:"Muslim Arab philosopher, mathematician and physician (c. 801–873)",t:"person"},
  "Alaska_Purchase": {d:"1867 sale by Russia to the United States",t:"idea"},
  "Albert_Einstein": {d:"German-born theoretical physicist (1879–1955)",t:"person"},
  "Ali_Farka_Touré": {d:"Malian singer and musician (1939–2006)",t:"person"},
  "Allotropes_of_carbon": {d:"Materials made only out of carbon",t:"idea"},
  "Almoravid_dynasty": {d:"1040–1147 Berber dynasty in west Africa and Iberia",t:"person"},
  "Along_the_River_During_the_Qingming_Festival": {d:"Painting attributed to Zhang Zeduan",t:"work"},
  "AlphaGo": {d:"Artificial intelligence that plays Go",t:"idea"},
  "Amanirenas": {d:"Queen of the Meroitic Kingdom of Kush",t:"person"},
  "Amazon_River": {d:"Major river in Northern South America",t:"go"},
  "Amelia_Earhart": {d:"American aviation pioneer (1897–1937)",t:"person"},
  "Amina_of_Zazzau": {d:"Ruler of Zazzau",t:"person"},
  "Ancient_Olympic_Games": {d:"Athletic competitions in ancient Greece",t:"idea"},
  "Andes": {d:"Mountain range in South America",t:"go"},
  "Andreas_Vesalius": {d:"Anatomist, physician and author (1514–1564)",t:"person"},
  "Angel_Falls": {d:"Tallest single drop waterfall in the world, Venezuela",t:"go"},
  "Angkor_Wat": {d:"Buddhist temple complex in Cambodia",t:"visit"},
  "Anglerfish": {d:"Bony fish with a natural lure",t:"idea"},
  "Antarctica": {d:"Earth's southernmost continent",t:"go"},
  "Aorta": {d:"Largest artery in the human body",t:"idea"},
  "Aperitivo": {d:"Alcoholic drink normally served before or after a meal",t:"idea"},
  "Apollo_11": {d:"First crewed Moon landing (1969)",t:"idea"},
  "Apollo_15": {d:"Fourth crewed Moon landing",t:"idea"},
  "Appendix_(anatomy)": {d:"Tube attached to the intestine",t:"idea"},
  "Archerfish": {d:"Family of fishes",t:"idea"},
  "Archimedes'_principle": {d:"Buoyancy principle in fluid dynamics",t:"idea"},
  "Arctic_tern": {d:"Bird that breeds in the Arctic and subarctic and migrates to the Antarctic",t:"idea"},
  "Armillaria_ostoyae": {d:"Species of fungus",t:"idea"},
  "Armour": {d:"Covering used to protect from physical injury or damage",t:"idea"},
  "Aryabhata": {d:"Indian mathematician-astronomer (476–550)",t:"person"},
  "Ashoka": {d:"Mauryan emperor from 269 to 232 BCE",t:"person"},
  "Aspirin": {d:"Nonsteroidal anti-inflammatory drug",t:"idea"},
  "Atacama_Desert": {d:"Plateau on Pacific coast of South America",t:"go"},
  "Atacama_Large_Millimeter_Array": {d:"66-telescope radio observatory in Chile",t:"visit"},
  "Athenian_democracy": {d:"Government regime in ancient Athens",t:"idea"},
  "Athens": {d:"Capital and largest city of Greece",t:"go"},
  "Atomic_nucleus": {d:"Core of an atom composed of nucleons",t:"idea"},
  "Augustus": {d:"Roman emperor from 27 BC to AD 14",t:"person"},
  "Aurora": {d:"Atmospheric effect caused by the solar wind",t:"idea"},
  "Australian_Aboriginal_astronomy": {d:"Aboriginal Australian culture relating to astronomical subjects",t:"idea"},
  "Axolotl": {d:"Species of salamander",t:"idea"},
  "Aye-aye": {d:"Species of primate",t:"idea"},
  "Ayutthaya_Kingdom": {d:"Siamese kingdom in Southeast Asia (1351–1767)",t:"person"},
  "Aztec_Empire": {d:"Alliance of three Nahua city states in Mexico (1428–1521)",t:"person"},
  "Aït_Benhaddou": {d:"Historical village in southeastern Morocco",t:"idea"},
  "Bagan": {d:"UNESCO historical city in Mandalay Region, Myanmar",t:"go"},
  "Bakhshali_manuscript": {d:"Ancient mathematical text",t:"work"},
  "Banana_equivalent_dose": {d:"Informal measurement of ionizing radiation exposure",t:"idea"},
  "Bangkok": {d:"Capital and largest city of Thailand",t:"go"},
  "Baqt": {d:"7th-century treaty between Makuria and Egypt",t:"event"},
  "Bar-tailed_godwit": {d:"Species of bird",t:"idea"},
  "Barcode": {d:"Optical machine-readable representation of data",t:"idea"},
  "Basilica_of_Our_Lady_of_Peace": {d:"Church in Yamoussoukro, Ivory Coast",t:"visit"},
  "Bat": {d:"Order of flying mammals",t:"idea"},
  "Batik": {d:"Cloth dyeing technique",t:"idea"},
  "Battle_of_Adwa": {d:"1896 battle of the First Italo-Ethiopian War",t:"event"},
  "Battle_of_Ain_Jalut": {d:"1260 battle between the Mamluk Sultanate and the Mongol Empire",t:"person"},
  "Bee_hummingbird": {d:"Smallest species of bird",t:"idea"},
  "Benin_Bronzes": {d:"Metal plaques and sculptures from the Kingdom of Benin",t:"person"},
  "Benjamin_Banneker": {d:"American scientist, surveyor and farmer (1731–1806)",t:"person"},
  "Berry_(botany)": {d:"Botanical fruit with fleshy pericarp, containing one or many seeds",t:"idea"},
  "Betelgeuse": {d:"Red supergiant star in the constellation Orion",t:"idea"},
  "Bharatanatyam": {d:"Major form of Indian classical dance",t:"idea"},
  "Binary_number": {d:"Number expressed in the base-2 numeral system",t:"idea"},
  "Birthday_problem": {d:"Probability of shared birthdays",t:"idea"},
  "Black_Death": {d:"1346–1353 pandemic in Eurasia and North Africa",t:"person"},
  "Blue_whale": {d:"Species of whale; largest animal known",t:"idea"},
  "Blues": {d:"Music genre originating in 1860s",t:"idea"},
  "Bluetooth": {d:"Short-range wireless technology standard",t:"idea"},
  "Boiling_point": {d:"Characteristic temperature for a substance",t:"idea"},
  "Bolivian_Navy": {d:"Military unit",t:"idea"},
  "Bombardier_beetle": {d:"Beetles that emit a spray when threatened",t:"idea"},
  "Bone_marrow": {d:"Semi-solid tissue in the spongy portions of bones",t:"idea"},
  "Boomerang": {d:"Thrown tool and weapon",t:"idea"},
  "Bosporus": {d:"Narrow strait in northwestern Turkey",t:"go"},
  "Bossa_nova": {d:"Style of Brazilian music",t:"idea"},
  "Brahmagupta": {d:"Indian mathematician and astronomer (598–668)",t:"person"},
  "Brasília": {d:"Federal capital of Brazil",t:"go"},
  "Bristlecone_pine": {d:"Three species of pine trees native to the Western United States",t:"idea"},
  "Buddhist_cuisine": {d:"East Asian cuisine informed by Buddhism",t:"idea"},
  "Buganda": {d:"Bantu kingdom within Uganda",t:"person"},
  "Byte": {d:"Unit of digital information, usually 8 bits",t:"idea"},
  "Byte-pair_encoding": {d:"Adjacent characters (tokens) merge-based compression algorithm",t:"idea"},
  "Bògòlanfini": {d:"Malian dyed cotton fabric",t:"idea"},
  "C._V._Raman": {d:"Indian physicist (1888–1970)",t:"person"},
  "Cacio_e_pepe": {d:"Italian pasta dish",t:"idea"},
  "Cahokia": {d:"Archaeological site in southwestern Illinois, US",t:"visit"},
  "Cairo": {d:"Capital and largest city of Egypt",t:"go"},
  "Can't_Buy_Me_Love": {d:"1964 single by the Beatles",t:"idea"},
  "Canada–United_States_border": {d:"International border in North America",t:"idea"},
  "Canberra": {d:"Capital city of Australia",t:"go"},
  "Capacitive_sensing": {d:"Technology in electrical engineering",t:"person"},
  "Capillary": {d:"Smallest type of blood vessel",t:"idea"},
  "Carbonara": {d:"Italian pasta dish",t:"idea"},
  "Carthage": {d:"Ancient city in Tunisia",t:"go"},
  "Catatumbo_lightning": {d:"Atmospheric phenomenon in Venezuela",t:"idea"},
  "Cattle": {d:"Large, domesticated, cloven-hooved herbivores",t:"idea"},
  "Celesta": {d:"Struck idiophone operated by a keyboard",t:"idea"},
  "Central_processing_unit": {d:"Central computer component that executes instructions",t:"idea"},
  "Cerebellum": {d:"Structure at the rear of the vertebrate brain, beneath the cerebrum",t:"idea"},
  "Cerebral_cortex": {d:"Outer layer of the cerebrum of the mammalian brain",t:"idea"},
  "Cervical_vertebrae": {d:"Vertebrae of the neck",t:"idea"},
  "Ceviche": {d:"Dish of marinated raw seafood",t:"idea"},
  "Challenger_Deep": {d:"Deepest known point of Earth's seabed",t:"idea"},
  "Chan_Chan": {d:"Pre-Columbian city in South America",t:"go"},
  "Chandrayaan-3": {d:"Indian lunar mission (2023–Present)",t:"idea"},
  "Chang'e_4": {d:"2019 Chinese lunar lander & rover",t:"idea"},
  "Charles_K._Kao": {d:"Hong Kong electrical engineer (1933–2018)",t:"person"},
  "Chartres_Cathedral": {d:"Medieval cathedral in France",t:"visit"},
  "Cheetah": {d:"Large feline of the genus Acinonyx",t:"idea"},
  "Chefchaouen": {d:"City in Tangier-Tetouan-Al Hoceima, Morocco",t:"go"},
  "Cherenkov_radiation": {d:"Electromagnetic radiation from a charged particle in a medium",t:"idea"},
  "Chicha_morada": {d:"Prehispanic corn beverage from Peru",t:"idea"},
  "Chicxulub_crater": {d:"Prehistoric impact crater in Mexico",t:"idea"},
  "Chieko_Asakawa": {d:"Japanese computer scientist",t:"person"},
  "Chinampa": {d:"Type of Mesoamerican agriculture",t:"idea"},
  "Chinguetti": {d:"Place in Adrar Region, Mauritania",t:"go"},
  "Chlorophyll": {d:"Green pigments found in plants, algae and bacteria",t:"idea"},
  "Christmas_Island_red_crab": {d:"Species of crustacean (Gecarcoidea natalis)",t:"idea"},
  "Christopher_Columbus": {d:"Italian navigator and explorer (1451–1506)",t:"person"},
  "Chromosome": {d:"DNA molecule containing genetic material of a cell",t:"idea"},
  "Clarence_Ellis_(computer_scientist)": {d:"American computer scientist and professor",t:"person"},
  "Cleopatra": {d:"Pharaoh of Egypt from 51 to 30 BC",t:"person"},
  "Cloud_computing": {d:"Form of shared internet-based computing",t:"idea"},
  "Clownfish": {d:"Monotypic subfamily of fishes",t:"idea"},
  "Coca": {d:"Plant in the Erythroxylaceae family",t:"idea"},
  "Cochineal": {d:"Species of insect producing the crimson dye carmine",t:"idea"},
  "Cochlea": {d:"Snail-shaped part of inner ear involved in hearing",t:"idea"},
  "Cocoa_bean": {d:"Fatty seed of Theobroma cacao",t:"idea"},
  "Code_of_Hammurabi": {d:"Babylonian legal text",t:"work"},
  "Coelacanth": {d:"Class of lobe-finned fishes",t:"idea"},
  "Collagen": {d:"Most abundant structural protein in animals",t:"idea"},
  "Colosseum": {d:"Ancient Roman amphitheater in Rome",t:"idea"},
  "Commedia_dell'arte": {d:"Form of theatre originating in Italy",t:"idea"},
  "Common_cuckoo": {d:"Species of bird",t:"idea"},
  "Common_ostrich": {d:"Species of flightless bird",t:"idea"},
  "Compass": {d:"Instrument used for navigation and orientation",t:"idea"},
  "Complaint_tablet_to_Ea-nassir": {d:"Oldest known written complaint (c. 1750 BC)",t:"idea"},
  "Computer_mouse": {d:"Pointing device used to control a computer",t:"idea"},
  "Congo_River": {d:"River in Central Africa",t:"go"},
  "Continental_drift": {d:"Movement of Earth's continents relative to each other",t:"event"},
  "Coober_Pedy": {d:"Town in South Australia",t:"go"},
  "Coral": {d:"Marine invertebrates of the subphylum Anthozoa",t:"idea"},
  "Coricancha": {d:"Archaeological site in Peru",t:"visit"},
  "Cornea": {d:"Transparent front layer of the eye",t:"idea"},
  "Corpus_callosum": {d:"White matter tract connecting the two cerebral hemispheres",t:"idea"},
  "Couscous": {d:"Traditional Maghrebi dish",t:"idea"},
  "Crab_Nebula": {d:"Supernova remnant in the constellation Taurus",t:"idea"},
  "Credential_stuffing": {d:"Cyberattack using mass login requests",t:"idea"},
  "Cuneiform": {d:"Writing system of the ancient Near East",t:"idea"},
  "Cusco": {d:"City in Peru",t:"go"},
  "Cyrus_Cylinder": {d:"Ancient clay cylinder with Akkadian cuneiform script",t:"idea"},
  "DJ_Kool_Herc": {d:"Jamaican-American DJ (born 1955)",t:"person"},
  "DNA": {d:"Molecule that carries genetic information",t:"idea"},
  "Dahomey_Amazons": {d:"Female regiment in the Kingdom of Dahomey",t:"person"},
  "Damascus_steel": {d:"Type of steel used in Middle Eastern swordmaking",t:"idea"},
  "Danakil_Depression": {d:"Geological feature in East Africa",t:"idea"},
  "Danube": {d:"Second-longest river in Europe",t:"go"},
  "Day_of_the_Dead": {d:"Mexican multi-day holiday",t:"idea"},
  "Dead_Sea": {d:"Salt lake in the Levant",t:"go"},
  "Deccan_Traps": {d:"Large igneous province in India",t:"go"},
  "Deep_Blue_(chess_computer)": {d:"Chess-playing computer made by IBM",t:"idea"},
  "Deepfake": {d:"Realistic artificially generated media",t:"idea"},
  "Derinkuyu_underground_city": {d:"Ancient underground city in Turkey",t:"go"},
  "Desert": {d:"Area of land where little precipitation occurs",t:"idea"},
  "Diamond": {d:"Form of carbon",t:"idea"},
  "Diomede_Islands": {d:"Islands in the Bering Strait",t:"go"},
  "Djenné-Djenno": {d:"Historic site in Djenné Cercle, Mali",t:"idea"},
  "Dmitri_Mendeleev": {d:"Russian chemist (1834–1907)",t:"person"},
  "Dodo": {d:"Extinct species of bird",t:"idea"},
  "Domain_Name_System": {d:"System to identify resources on a network",t:"idea"},
  "Don_Quixote": {d:"1605–1615 novel by Miguel de Cervantes",t:"person"},
  "Donald_Davies": {d:"British computer scientist (1924–2000)",t:"person"},
  "Doppler_effect": {d:"Frequency change of a wave for observer relative to its source",t:"idea"},
  "Dorothy_Vaughan": {d:"American human computer and computer programmer (1910–2008)",t:"person"},
  "Double-slit_experiment": {d:"Physics experiment",t:"idea"},
  "Douglas_Engelbart": {d:"American engineer and inventor (1925–2013)",t:"person"},
  "Dresden_Codex": {d:"Maya manuscript",t:"work"},
  "Dromedary": {d:"One-humped camel",t:"idea"},
  "Dry_ice": {d:"Solid form of carbon dioxide",t:"idea"},
  "Dung_beetle": {d:"Informal group of insects",t:"idea"},
  "ELIZA": {d:"Natural language processing computer program",t:"idea"},
  "ENIAC": {d:"First electronic general-purpose digital computer",t:"person"},
  "Earth's_rotation": {d:"Rotation of Earth around its axis",t:"idea"},
  "Earthworm": {d:"Terrestrial invertebrate, order Opisthopora",t:"idea"},
  "Eddington_experiment": {d:"1919 observations which confirmed Einstein's theory of general relativity",t:"person"},
  "Egyptian_blue": {d:"Pigment used in ancient Egypt",t:"idea"},
  "Eiffel_Tower": {d:"Tower in Paris, France",t:"visit"},
  "El_Castillo,_Chichen_Itza": {d:"Step pyramid in the Mayan city of Chichen Itza in Tinúm, Mexico",t:"visit"},
  "El_Niño": {d:"Global climate phenomenon",t:"idea"},
  "Electric_eel": {d:"Genus of fishes in South America",t:"idea"},
  "Electromagnetic_induction": {d:"Production of voltage by a varying magnetic field",t:"idea"},
  "Electromagnetic_radiation": {d:"Physical model of propagating energy",t:"idea"},
  "Electron": {d:"Elementary particle with negative charge",t:"idea"},
  "Elgin_Marbles": {d:"Ancient Greek sculptures held in London",t:"idea"},
  "Elisha_Otis": {d:"19th-century American industrialist and inventor of the Otis Elevator",t:"person"},
  "Elizabeth_J._Feinler": {d:"American information scientist (born 1931)",t:"person"},
  "Emirates_Mars_Mission": {d:"Space exploration probe mission to Mars",t:"idea"},
  "Emmy_Noether": {d:"German mathematician (1882–1935)",t:"person"},
  "Emperor_penguin": {d:"Large flightless seabird endemic to Antarctica",t:"idea"},
  "Enceladus": {d:"Natural satellite orbiting Saturn",t:"idea"},
  "End-to-end_encryption": {d:"Secure communications method",t:"idea"},
  "Enteric_nervous_system": {d:"Vital part of the nervous system controlling the gastrointestinal tract",t:"idea"},
  "Epic_of_Gilgamesh": {d:"Epic poem from Mesopotamia",t:"work"},
  "Epidermis": {d:"Outermost of the three layers that make up the skin",t:"idea"},
  "Epiglottis": {d:"Flap in the throat protecting the windpipe",t:"idea"},
  "Eratosthenes": {d:"Greek librarian, mathematician, geographer, and poet",t:"person"},
  "Ethiopian_calendar": {d:"Principal calendar used in Ethiopia and Eritrea",t:"idea"},
  "Eustachian_tube": {d:"Tube connecting middle ear to throat",t:"idea"},
  "Evzones": {d:"Unit type of the Hellenic Army",t:"idea"},
  "Fahrenheit": {d:"Temperature scale",t:"idea"},
  "Fall_of_Constantinople": {d:"1453 Ottoman conquest of the Byzantine capital",t:"go"},
  "Fasil_Ghebbi": {d:"Fortified royal place of Gondarine period emperors in Ethiopia",t:"person"},
  "Fela_Kuti": {d:"Nigerian musician and activist (1938–1997)",t:"person"},
  "Femur": {d:"Thigh bone",t:"idea"},
  "Fibonacci": {d:"Italian mathematician (c. 1170 – c. 1240/50)",t:"person"},
  "Fibonacci_sequence": {d:"Numbers obtained by adding the two previous ones",t:"idea"},
  "Fireworks": {d:"Low explosive pyrotechnic devices for entertainment",t:"idea"},
  "Fish_sandwich": {d:"Sandwich or burger made with fish",t:"idea"},
  "Five-hundred-meter_Aperture_Spherical_Telescope": {d:"Radio telescope in Guizhou, China",t:"idea"},
  "Flash_memory": {d:"Electronic non-volatile computer storage device",t:"idea"},
  "Florence_Nightingale": {d:"English founder of modern nursing (1820–1910)",t:"person"},
  "Flying_buttress": {d:"Form of buttress",t:"idea"},
  "Four-stroke_engine": {d:"Internal combustion engine type",t:"idea"},
  "Four_color_theorem": {d:"Planar maps require at most four colors",t:"idea"},
  "Frappé_coffee": {d:"Greek iced coffee drink",t:"idea"},
  "Fresco": {d:"Mural painting upon freshly laid lime plaster",t:"work"},
  "Frida_Kahlo": {d:"Mexican painter (1907–1954)",t:"person"},
  "Fundamental_interaction": {d:"Most basic type of physical force",t:"idea"},
  "Fushimi_Inari-taisha": {d:"Shinto shrine near Kyoto, Japan",t:"idea"},
  "Gabriela_Mistral": {d:"Chilean author and diplomat (1889–1957)",t:"person"},
  "Galton_board": {d:"Device invented by Francis Galton",t:"idea"},
  "Gastric_acid": {d:"Digestive fluid formed in the stomach",t:"idea"},
  "Geisha": {d:"Japanese female entertainer and hostess",t:"idea"},
  "Ghana": {d:"Country in West Africa",t:"go"},
  "Ghana_Empire": {d:"Empire in West Africa from c. 200s to c. 1200s",t:"event"},
  "Gion": {d:"Geisha district in Kyoto, Japan",t:"idea"},
  "Girih_tile": {d:"Five tiles used in Islamic decorative art",t:"idea"},
  "Gladys_West": {d:"American mathematician (1930–2026)",t:"person"},
  "Glass": {d:"Transparent non-crystalline solid material",t:"idea"},
  "Global_Positioning_System": {d:"American satellite-based radio navigation service",t:"idea"},
  "Gluteus_maximus": {d:"Largest and most superficial of the three gluteal muscles",t:"idea"},
  "Gold": {d:"Chemical element with atomic number 79 (Au)",t:"idea"},
  "Golden_Stool": {d:"Throne of Asante kings",t:"person"},
  "Goldfish": {d:"Freshwater fish common in aquariums",t:"idea"},
  "Google_Chrome": {d:"Web browser developed by Google",t:"idea"},
  "Grace_Hopper": {d:"U.S. naval officer and computer scientist (1906–1992)",t:"person"},
  "Grand_Palace": {d:"Royal residence in Bangkok, Thailand",t:"idea"},
  "Graphics_processing_unit": {d:"Specialized electronic circuit that accelerates graphics",t:"idea"},
  "Great_Barrier_Reef": {d:"Coral reef system in Queensland, Australia",t:"person"},
  "Great_Blue_Hole": {d:"Marine sinkhole off the coast of Belize",t:"idea"},
  "Great_Law_of_Peace": {d:"Oral constitution of the Haudenosaunee Confederacy",t:"idea"},
  "Great_Mosque_of_Djenné": {d:"Mosque in Djenné, Mali",t:"visit"},
  "Great_Pyramid_of_Giza": {d:"Largest pyramid in the Giza Necropolis, Egypt",t:"visit"},
  "Great_Red_Spot": {d:"Persistent storm in Jupiter's atmosphere",t:"idea"},
  "Great_Sphinx_of_Giza": {d:"Limestone statue of a reclining sphinx",t:"idea"},
  "Great_Wall_of_China": {d:"Series of fortifications in northern China",t:"idea"},
  "Great_Zimbabwe": {d:"Ruins of an ancient/medieval city in southeast Zimbabwe",t:"visit"},
  "Greater_flamingo": {d:"Species of bird",t:"idea"},
  "Greater_honeyguide": {d:"Species of bird",t:"idea"},
  "Green_flash": {d:"Meteorological optical phenomenon",t:"idea"},
  "Greenland_ice_sheet": {d:"Vast body of ice in Greenland, Northern Hemisphere",t:"idea"},
  "Guernica_(Picasso)": {d:"1937 anti-war painting by Pablo Picasso",t:"work"},
  "Guinea_pig": {d:"Domesticated rodent from South America",t:"idea"},
  "Gunpowder": {d:"Type of firearm propellant",t:"idea"},
  "HTTP": {d:"Application layer protocol",t:"idea"},
  "HTTPS": {d:"HTTP extension supporting TLS encryption",t:"idea"},
  "HTTP_cookie": {d:"Data item stored in a browser by a website",t:"idea"},
  "Hafele–Keating_experiment": {d:"Test of relativistic time dilation",t:"idea"},
  "Hagia_Sophia": {d:"Mosque and former church in Istanbul, Turkey",t:"visit"},
  "Hallucination_(artificial_intelligence)": {d:"Erroneous AI-generated content presented as true",t:"idea"},
  "Hangul": {d:"Native alphabet of the Korean language",t:"idea"},
  "Hannibal": {d:"Carthaginian general and statesman (247–183/181 BC)",t:"person"},
  "Hanseatic_League": {d:"1200s–1669 trade confederation in Northern Europe",t:"person"},
  "Harar": {d:"Capital of Harari Region, Ethiopia",t:"go"},
  "Harmattan": {d:"West African dry weather season",t:"idea"},
  "Hatshepsut": {d:"Pharaoh of Egypt from 1479 to 1458 BC",t:"person"},
  "Hayabusa2": {d:"Japanese space mission to asteroid Ryugu",t:"idea"},
  "Heart": {d:"Organ found in humans and other animals",t:"idea"},
  "Hedy_Lamarr": {d:"Austrian-American actress and inventor (1914–2000)",t:"person"},
  "Hemoglobin": {d:"Metalloprotein that binds with oxygen",t:"idea"},
  "Henna": {d:"Vegetable dye",t:"idea"},
  "Herbivore": {d:"Organism that eats mostly or exclusively plant material",t:"idea"},
  "Hexadecimal": {d:"Base-16 numeric representation",t:"idea"},
  "Hippocampus": {d:"Vertebrate brain region",t:"go"},
  "Hoba_meteorite": {d:"Largest known intact meteorite",t:"idea"},
  "Honey": {d:"Sweet and viscous substance made by bees",t:"idea"},
  "Honey_bee": {d:"Colonial flying insect",t:"idea"},
  "Horned_helmet": {d:"Helmet with horns",t:"idea"},
  "House_of_Wisdom": {d:"Abbasid-era library in Baghdad, modern-day Iraq",t:"visit"},
  "Huffman_coding": {d:"Technique to compress data",t:"idea"},
  "Hulhumalé": {d:"District of Malé City in North Malé Atoll, Maldives",t:"go"},
  "Human_microbiome": {d:"Microorganisms in or on human skin and biofluids",t:"idea"},
  "Human_skin": {d:"Organ covering the outside of the human body",t:"idea"},
  "Human_tooth": {d:"Calcified whitish structure in humans' mouths used to break down food",t:"idea"},
  "Hundred_Years'_War": {d:"Medieval Anglo-French conflicts, 1337–1453",t:"person"},
  "Hydrogen": {d:"Chemical element with atomic number 1 (H)",t:"idea"},
  "Hyoid_bone": {d:"Bone situated in the neck between the chin and the thyroid-cartilage",t:"idea"},
  "Hypatia": {d:"4th-century Alexandrian astronomer and mathematician",t:"person"},
  "IP_address": {d:"Numerical label used to identify a network interface in an IP network",t:"idea"},
  "Ibn_Battuta": {d:"Maghrebi traveller and scholar (1304–1368/1369)",t:"person"},
  "Ibn_al-Haytham": {d:"Arab physicist, mathematician and astronomer (c.965–c.1040)",t:"person"},
  "Ibn_al-Nafis": {d:"Arab polymath and physician (1213–1288)",t:"person"},
  "Ice": {d:"Frozen water; the solid state of water",t:"idea"},
  "Ice_stupa": {d:"Artificial glacier mound for storing water",t:"go"},
  "Ife": {d:"City in Osun State, Nigeria",t:"go"},
  "Igbo-Ukwu": {d:"Place in Anambra, Nigeria",t:"idea"},
  "ImageNet": {d:"Image dataset",t:"idea"},
  "Impression,_Sunrise": {d:"1872 painting by Claude Monet",t:"work"},
  "Inca_road_system": {d:"Transportation system of the Inca empire",t:"event"},
  "Incandescent_light_bulb": {d:"Electric light bulb with a resistively heated wire filament",t:"idea"},
  "Inclined_plane": {d:"Tilted flat supporting surface",t:"idea"},
  "Indian_Ocean": {d:"Oceanic division",t:"idea"},
  "Indigo_dye": {d:"Chemical compound, food additive and dye",t:"idea"},
  "Industrial_Revolution": {d:"1760–1840 agrarian to industrial era shift",t:"person"},
  "Influence_of_William_Shakespeare": {d:"Impact of English playwright and poet",t:"person"},
  "Insect": {d:"Class of arthropods",t:"idea"},
  "Inti_Raymi": {d:"Incan religious festival",t:"idea"},
  "Iron": {d:"Chemical element with atomic number 26 (Fe)",t:"idea"},
  "Ishango_bone": {d:"Paleolithic artifact from Congo",t:"idea"},
  "Islamic_calligraphy": {d:"Artistic practice of calligraphy in Islamic contexts",t:"person"},
  "Istanbul": {d:"Largest city in Turkey",t:"go"},
  "Jaipur": {d:"Capital of Rajasthan, India",t:"go"},
  "Jakarta": {d:"Capital and largest city in Indonesia",t:"go"},
  "James_Watt": {d:"Scottish inventor, engineer and chemist (1736–1819)",t:"person"},
  "Jantar_Mantar,_Jaipur": {d:"UNESCO World Heritage Site in Jaipur",t:"visit"},
  "Japanese_tea_ceremony": {d:"Traditional Japanese ceremony",t:"idea"},
  "Jemaa_el-Fnaa": {d:"Moroccan cultural heritage site",t:"visit"},
  "Joint_cracking": {d:"Bending a person's joints to produce a distinct cracking or popping sound",t:"idea"},
  "Joseph_Fourier": {d:"French mathematician and physicist (1768–1830)",t:"person"},
  "Joy_Buolamwini": {d:"Computer scientist and digital activist",t:"person"},
  "Justinian_I": {d:"Roman emperor from 527 to 565",t:"person"},
  "Kairouan": {d:"City in Kairouan Governorate, Tunisia",t:"go"},
  "Kaiseki": {d:"Traditional multi-course Japanese dinner",t:"idea"},
  "Kanem–Bornu_Empire": {d:"Empire around Lake Chad, Africa, c. 700–1902",t:"person"},
  "Kangaroo": {d:"Marsupial of the family Macropodidae",t:"idea"},
  "Kapnikarea": {d:"Byzantine church in Athens, Greece",t:"visit"},
  "Karen_Spärck_Jones": {d:"British computer and information scientist (1935–2007)",t:"person"},
  "Katherine_Johnson": {d:"American mathematician (1918–2020)",t:"person"},
  "Kente_cloth": {d:"Ghanaian textile",t:"idea"},
  "Khan_el-Khalili": {d:"Major souk in Cairo",t:"idea"},
  "Khartoum": {d:"Capital of Sudan",t:"go"},
  "Kilwa_Kisiwani": {d:"Island, hamlet and former Swahili city-state in Lindi Region, Tanzania",t:"go"},
  "Kilwa_Sultanate": {d:"Swahili sultanate (957–1513)",t:"person"},
  "Kimchi": {d:"Korean side dish of fermented vegetables",t:"idea"},
  "Kind_of_Blue": {d:"1959 studio album by Miles Davis",t:"work"},
  "Kingdom_of_Aksum": {d:"Polity in Africa and Arabia before 960",t:"idea"},
  "Kingdom_of_Kongo": {d:"1390–1914 state in Central Africa; Portuguese vassal from 1857",t:"person"},
  "Kingdom_of_Mutapa": {d:"Empire in Southern Africa from the 15th to late-19th centuries",t:"event"},
  "Kinkaku-ji": {d:"Zen Buddhist temple in Kyoto, Japan",t:"visit"},
  "Kintsugi": {d:"Japanese pottery repair method with gold lacquer",t:"idea"},
  "Kiyomizu-dera": {d:"Buddhist temple in Kyoto, Japan",t:"visit"},
  "Koch_snowflake": {d:"Fractal curve",t:"idea"},
  "Kora_(instrument)": {d:"Stringed instrument from West Africa",t:"idea"},
  "Koshari": {d:"National dish of Egypt",t:"idea"},
  "Koutoubia_Mosque": {d:"Mosque in Marrakesh, Morocco",t:"visit"},
  "Kyoto": {d:"City in the Kansai region of Japan",t:"go"},
  "L'Anse_aux_Meadows": {d:"Norse archaeological site in Newfoundland, Canada",t:"visit"},
  "La_Paz": {d:"Seat of government of Bolivia",t:"idea"},
  "Lake_Baikal": {d:"Freshwater rift lake in Russia",t:"go"},
  "Lake_Titicaca": {d:"Large lake on the border of Peru and Bolivia",t:"go"},
  "Lake_Victoria": {d:"Lake in East-central Africa",t:"go"},
  "Landlocked_country": {d:"Country with no ocean coastline",t:"go"},
  "Large_intestine": {d:"Last part of the digestive system in vertebrates",t:"idea"},
  "Large_language_model": {d:"Type of machine learning model",t:"idea"},
  "Leafcutter_ant": {d:"Over 50 species of leaf-foraging ants of the Americas",t:"idea"},
  "Leatherback_sea_turtle": {d:"Species of marine reptile",t:"idea"},
  "Leptis_Magna": {d:"Ancient city in modern Libya",t:"go"},
  "Lesotho": {d:"Country in Southern Africa",t:"go"},
  "Light-emitting_diode": {d:"Semiconductor light source",t:"idea"},
  "Light-year": {d:"Distance that light travels in one year",t:"idea"},
  "Lightning": {d:"Weather phenomenon involving electrostatic discharge",t:"idea"},
  "Lion": {d:"Large cat native to Africa and India",t:"idea"},
  "Lithium-ion_battery": {d:"Type of rechargeable battery",t:"idea"},
  "Liver": {d:"Vertebrate organ involved in metabolism",t:"idea"},
  "Lodestone": {d:"Naturally magnetized mineral",t:"idea"},
  "Lukasa": {d:"Memory device of the Luba people",t:"idea"},
  "Lunar_Laser_Ranging_experiments": {d:"Measuring the distance between the Earth and the Moon with laser light",t:"idea"},
  "Luoshu_Square": {d:"Ancient Chinese diagram",t:"idea"},
  "Lusona": {d:"Ideographic art tradition in parts of Africa",t:"idea"},
  "Lymphatic_system": {d:"Organ system in vertebrates complementary to the circulatory system",t:"idea"},
  "Machine_learning": {d:"Subset of artificial intelligence",t:"idea"},
  "Machu_Picchu": {d:"15th-century Inca citadel in Peru",t:"idea"},
  "Macintosh_128K": {d:"First model of Apple's Macintosh computer line",t:"idea"},
  "Madhava_of_Sangamagrama": {d:"Indian mathematician and astronomer (1340–1425)",t:"person"},
  "Magdeburg_hemispheres": {d:"Pair of copper hemispheres designed to demonstrate the power of atmospheric pressure",t:"idea"},
  "Maghrebi_mint_tea": {d:"North African green tea",t:"idea"},
  "Magna_Carta": {d:"English charter of freedoms made in 1215",t:"idea"},
  "Maillard_reaction": {d:"Chemical reaction that gives browned food flavor",t:"idea"},
  "Majapahit": {d:"Javanese empire from 1292 to 1527",t:"event"},
  "Malick_Sidibé": {d:"Malian photographer (1935–2016)",t:"person"},
  "Mangrove": {d:"Shrub growing in brackish water",t:"idea"},
  "Mansa_Musa": {d:"Ruler of Mali from c. 1312 to c. 1337",t:"person"},
  "Mantis_shrimp": {d:"Order of crustaceans",t:"idea"},
  "Mapungubwe": {d:"Ancient kingdom in the Limpopo-Shashe Basin, northern South Africa",t:"person"},
  "Margaret_Hamilton_(software_engineer)": {d:"American software engineer (born 1936)",t:"person"},
  "Marian_Rejewski": {d:"Polish mathematician and cryptologist (1905–1980)",t:"person"},
  "Marie_Curie": {d:"Polish-French physicist and chemist (1867–1934)",t:"person"},
  "Marie_Tharp": {d:"American oceanographer and cartographer (1920–2006)",t:"person"},
  "Mark_Dean_(computer_scientist)": {d:"American inventor and computer engineer",t:"person"},
  "Marrakesh": {d:"City in Marrakesh–Safi, Morocco",t:"go"},
  "Mars_Orbiter_Mission": {d:"Indian orbiter mission to Mars (2013–2022)",t:"person"},
  "Marshall_Islands_stick_chart": {d:"Micronesian navigational aid",t:"idea"},
  "Maryam_Mirzakhani": {d:"Iranian mathematician (1977–2017)",t:"person"},
  "Masinissa": {d:"First King of Numidia from 202 BC to 148 BC",t:"person"},
  "Masseter_muscle": {d:"One of the masticatory muscles in mammals",t:"idea"},
  "Mass–energy_equivalence": {d:"Physics concept expressed as E = mc²",t:"idea"},
  "Mauna_Kea": {d:"Hawaiian volcano",t:"go"},
  "Maya_blue": {d:"Azure blue pigment made in pre-Columbian Mesoamerica",t:"idea"},
  "Maya_numerals": {d:"System used by the ancient Mayan civilization to represent numbers and dates",t:"event"},
  "Maya_script": {d:"Writing system of the Maya civilization",t:"event"},
  "Mayflower": {d:"17th-century ship of American colonists",t:"idea"},
  "Melanin": {d:"Group of natural pigments found in most organisms",t:"idea"},
  "Mercator_projection": {d:"Cylindrical conformal map projection",t:"idea"},
  "Mercury_(planet)": {d:"First planet from the Sun",t:"idea"},
  "Merina_Kingdom": {d:"1540–1897 kingdom in Madagascar",t:"person"},
  "Meroitic_script": {d:"Two alphasyllabaric scripts for the extinct Meroitic language",t:"idea"},
  "Mevlevi_order": {d:"Sufi order in Islam",t:"idea"},
  "Mexican_muralism": {d:"20th-century art movement",t:"event"},
  "Mexico_City": {d:"Capital and most populous city of Mexico",t:"go"},
  "Microwave_oven": {d:"Kitchen cooking appliance",t:"idea"},
  "Milky_Way": {d:"Galaxy containing the Solar System",t:"idea"},
  "Milutin_Milanković": {d:"Serbian scientist and professor (1879–1958)",t:"person"},
  "Mirage": {d:"Optical illusion caused by bending of light",t:"idea"},
  "Mitochondrion": {d:"Organelle in eukaryotic cells responsible for respiration",t:"idea"},
  "Moai": {d:"Monolithic statues on Easter Island",t:"go"},
  "Model_Context_Protocol": {d:"Protocol for communicating between LLMs and applications",t:"idea"},
  "Mole_(sauce)": {d:"Mexican sauce and marinade",t:"idea"},
  "Mona_Lisa": {d:"Painting by Leonardo da Vinci",t:"work"},
  "Monarch_butterfly_migration": {d:"Migrations, mainly across North America",t:"idea"},
  "Monsoon": {d:"Seasonal changes in atmospheric circulation and precipitation",t:"idea"},
  "Monty_Hall_problem": {d:"Probability puzzle",t:"idea"},
  "Mosque_of_Ibn_Tulun": {d:"Mosque in Cairo, Egypt",t:"visit"},
  "Mount_Erebus": {d:"Volcano on Ross Island, Antarctica",t:"go"},
  "Mount_Everest": {d:"Earth's highest mountain",t:"go"},
  "Mount_Fuji": {d:"Volcano in Japan",t:"go"},
  "Mount_Kilimanjaro": {d:"Mountain in Tanzania, highest in Africa",t:"go"},
  "Mount_Tambora": {d:"Active stratovolcano on Sumbawa, Indonesia",t:"idea"},
  "Moussaka": {d:"Dish of layered vegetables, sauce and meat",t:"idea"},
  "Multi-factor_authentication": {d:"Method of computer access control",t:"idea"},
  "Mulukhiyah": {d:"Jute-leaf dish from Egypt",t:"idea"},
  "Mycorrhiza": {d:"Fungus-plant symbiotic association",t:"idea"},
  "Myelin": {d:"Fatty substance insulating nerve cell axons",t:"idea"},
  "Möbius_strip": {d:"Non-orientable surface with one edge",t:"idea"},
  "Naguib_Mahfouz": {d:"Egyptian writer (1911–2006)",t:"person"},
  "Nahuatl": {d:"Uto-Aztecan language of Mexico",t:"idea"},
  "Nail_(anatomy)": {d:"Hard keratin protection of digit",t:"idea"},
  "Nairobi_National_Park": {d:"First national park in Kenya",t:"go"},
  "Naked_mole-rat": {d:"Burrowing eusocial rodent",t:"idea"},
  "Name_day": {d:"Traditional celebration in Christianity",t:"idea"},
  "Nan_Madol": {d:"Ruined ancient city in the Federated States of Micronesia",t:"go"},
  "Nana_Asma'u": {d:"Nigerian princess and poet",t:"person"},
  "Napoleon": {d:"French general and emperor (1769–1821)",t:"person"},
  "Nazar_(amulet)": {d:"Eye-shaped amulet believed to protect against the evil eye",t:"idea"},
  "Nazca_lines": {d:"Geoglyphs in the Nazca Desert, Peru",t:"go"},
  "Near-field_communication": {d:"Set of device communication protocols",t:"idea"},
  "Nephron": {d:"Microscopic structural and functional unit of the kidney",t:"idea"},
  "Netherlands": {d:"Country in Northwestern Europe and the Caribbean",t:"go"},
  "Newton_(unit)": {d:"Unit of force in physics",t:"idea"},
  "Nii_Quaynor": {d:"Ghanaian scientist and engineer",t:"person"},
  "Nile": {d:"Major river in northeast Africa",t:"go"},
  "Ninety-five_Theses": {d:"Disputation by Martin Luther on indulgences",t:"idea"},
  "Nitrogen_fixation": {d:"Conversion of dinitrogen into ammonia",t:"idea"},
  "Nixtamalization": {d:"Procedure for preparing corn to eat",t:"idea"},
  "Nocturnality": {d:"Behavior characterized by activity during the night and sleeping during the day",t:"idea"},
  "Nok_culture": {d:"Ancient civilization of Nigeria",t:"event"},
  "North_Pole": {d:"Northernmost point on Earth",t:"idea"},
  "Nowruz": {d:"New Year's Day on the Iranian calendars",t:"idea"},
  "Nubian_pyramids": {d:"Pyramids built by ancient Kushite kingdoms in present-day northern Sudan",t:"person"},
  "Nzinga_of_Ndongo_and_Matamba": {d:"Ambundu queen in Angola (c. 1583–1663)",t:"person"},
  "Obelisk_of_Axum": {d:"4th-century phonolite stele in Axum, Tigray Region, Ethiopia",t:"go"},
  "Oboe": {d:"Double-reed woodwind instrument",t:"idea"},
  "Octopus": {d:"Soft-bodied eight-limbed order of molluscs",t:"idea"},
  "Odyssey": {d:"Epic poem attributed to Homer",t:"work"},
  "Ohm": {d:"SI derived unit of electrical resistance",t:"idea"},
  "Okapi": {d:"Species of mammal",t:"idea"},
  "Okavango_Delta": {d:"River delta in Botswana",t:"go"},
  "Ol_Doinyo_Lengai": {d:"Active volcano in Arusha Region, Tanzania",t:"go"},
  "Olfactory_system": {d:"Sensory system used for smelling",t:"idea"},
  "Olympus_Mons": {d:"Martian volcano, highest point on Mars",t:"go"},
  "Omar_Khayyam": {d:"Persian polymath and poet (1048–1131)",t:"person"},
  "One_Hundred_Years_of_Solitude": {d:"1967 novel by Gabriel García Márquez",t:"work"},
  "One_Thousand_and_One_Nights": {d:"Collection of Middle Eastern folk tales",t:"idea"},
  "Open-source_software": {d:"Software with publicly available source code",t:"idea"},
  "Ophiocordyceps_unilateralis": {d:"Species of fungus",t:"idea"},
  "Optical_fiber": {d:"Light-conducting fiber",t:"idea"},
  "Ouarzazate_Solar_Power_Station": {d:"Concentrated solar power station in Drâa-Tafilalet, Morocco",t:"idea"},
  "Ousmane_Sembène": {d:"Senegalese film director, producer, screenwriter, actor and author (1923–2007)",t:"person"},
  "Oyo_Empire": {d:"Former empire in present day Nigeria and Benin Republic",t:"event"},
  "Ozone_layer": {d:"Region of the stratosphere",t:"go"},
  "PH": {d:"Measure of the level of acidity or basicity of an aqueous solution",t:"idea"},
  "Pacific_Ocean": {d:"Largest ocean on Earth",t:"go"},
  "Packet_switching": {d:"Method for transmitting data over a computer network",t:"idea"},
  "Pad_thai": {d:"Stir-fried noodle dish from Thailand",t:"idea"},
  "Pamukkale": {d:"Natural site in Denizli Province in southwestern Turkey",t:"go"},
  "Panama_Canal": {d:"Shipping route across Central America",t:"idea"},
  "Pancreas": {d:"Organ of the digestive system and endocrine system of vertebrates",t:"idea"},
  "Pangolin": {d:"Mammals of the order Pholidota",t:"idea"},
  "Pansori": {d:"Korean traditional musical storytelling",t:"idea"},
  "Pantheon,_Rome": {d:"Roman temple, later church, in Rome",t:"visit"},
  "Papunya_Tula": {d:"Aboriginal art cooperative and art movement in the Northern Territory",t:"event"},
  "Parthenon": {d:"Temple on the Athenian Acropolis, Greece",t:"visit"},
  "Password_strength": {d:"Resistance of a password to being guessed",t:"idea"},
  "Patch_(computing)": {d:"Data and process for mutating a software resource to a desired state",t:"idea"},
  "Peace_of_Westphalia": {d:"1648 treaties ending the Thirty Years' War and Eighty Years' War",t:"event"},
  "Pecorino_Romano": {d:"Hard, salty Italian cheese, often grated",t:"idea"},
  "Penicillin": {d:"Group of antibiotics derived from fungi",t:"idea"},
  "Perito_Moreno_Glacier": {d:"Glacier located in the Patagonian Andes",t:"go"},
  "Persepolis": {d:"Ceremonial capital of the Achaemenid Empire",t:"go"},
  "Persian_miniature": {d:"Small Persian painting on paper",t:"work"},
  "Petra": {d:"Ancient rock-cut historical city in Jordan",t:"go"},
  "Petrichor": {d:"Earthy smell when rain falls on dry soil",t:"idea"},
  "Phishing": {d:"Form of social engineering",t:"person"},
  "Phoenician_alphabet": {d:"Writing system used c. 1050 to 146 BC",t:"idea"},
  "Photoelectric_effect": {d:"Emission of electrons when electromagnetic radiation hits a material",t:"idea"},
  "Photosynthesis": {d:"Biological process to convert light into chemical energy",t:"idea"},
  "Pi": {d:"Number, approximately 3.14",t:"idea"},
  "Piano": {d:"Keyboard instrument",t:"idea"},
  "Pilaf": {d:"Rice dish in which grains do not stick",t:"idea"},
  "Piye": {d:"Ancient Kushite king and pharaoh",t:"person"},
  "Platypus": {d:"Species of mammal",t:"idea"},
  "Plimpton_322": {d:"Babylonian clay tablet of numbers in Pythagorean triples",t:"idea"},
  "Polychromy": {d:"Art terminology and color method",t:"idea"},
  "Polynesian_navigation": {d:"Methods to navigate the Pacific Ocean",t:"go"},
  "Pompeii": {d:"Ancient city near modern Naples, Italy",t:"go"},
  "Porcelain": {d:"Ceramic material",t:"idea"},
  "Pot-in-pot_refrigerator": {d:"Non-electric method of refrigeration",t:"idea"},
  "Potato": {d:"Starchy tuber used as a staple food",t:"idea"},
  "Pretoria": {d:"Executive capital of South Africa",t:"go"},
  "Prime_number": {d:"Number divisible only by 1 and itself",t:"idea"},
  "Prince_Rupert's_drop": {d:"Glass object created by dripping molten glass into cold water",t:"idea"},
  "Printing_press": {d:"Machine for applying ink under pressure",t:"idea"},
  "Private_browsing": {d:"Privacy feature in most web browsers",t:"idea"},
  "Problem_of_points": {d:"Problem in probability theory",t:"idea"},
  "Prompt_engineering": {d:"Structuring text as input to generative artificial intelligence",t:"work"},
  "Public-key_cryptography": {d:"Cryptographic system with public and private keys",t:"idea"},
  "Pueblo_Bonito": {d:"Ancient Puebloan ruin in New Mexico",t:"idea"},
  "Pulmonary_alveolus": {d:"Hollow cavity found in the lungs",t:"idea"},
  "Pythagorean_theorem": {d:"Relation between sides of a right triangle",t:"idea"},
  "QR_code": {d:"Type of two-dimensional barcode",t:"idea"},
  "QWERTY": {d:"Keyboard layout for Latin-script alphabets",t:"idea"},
  "Quechuan_languages": {d:"Language family of the Andes in South America",t:"idea"},
  "Queen_Victoria": {d:"Queen of the United Kingdom from 1837 to 1901",t:"person"},
  "Quicksand": {d:"Colloid consisting of granular material and water",t:"idea"},
  "Quipu": {d:"Andean record-keeping system using knotted cords",t:"idea"},
  "RGB_color_model": {d:"Color model based on red, green and blue",t:"idea"},
  "RSA_cryptosystem": {d:"Algorithm for public-key cryptography",t:"idea"},
  "Radia_Perlman": {d:"American software designer and network engineer",t:"person"},
  "Rafflesia_arnoldii": {d:"Species of flowering plant",t:"idea"},
  "Raga": {d:"Melodic mode of improvisation in Indian music",t:"idea"},
  "Rainbow": {d:"Meteorological phenomenon",t:"idea"},
  "Rashomon": {d:"1950 film by Akira Kurosawa",t:"work"},
  "Rattanakosin_Kingdom": {d:"Period of Thai history",t:"event"},
  "Ray_Tomlinson": {d:"American computer programmer (1941–2016)",t:"person"},
  "Rayleigh_scattering": {d:"Light scattering by small particles",t:"idea"},
  "Rebetiko": {d:"Greek music genre",t:"idea"},
  "Red_blood_cell": {d:"Oxygen-delivering blood cell and the most common type of blood cell",t:"idea"},
  "Reed–Solomon_error_correction": {d:"Error-correcting codes",t:"idea"},
  "Registan": {d:"Historical center of Samarkand, Uzbekistan",t:"idea"},
  "Renaissance": {d:"European cultural period of the 14th to 17th centuries",t:"event"},
  "Retina": {d:"Part of the eye",t:"idea"},
  "Rhind_Mathematical_Papyrus": {d:"Ancient Egyptian mathematical document",t:"idea"},
  "Richat_Structure": {d:"Circular geological feature in the Sahara desert",t:"go"},
  "Rideau_Canal": {d:"Canal in Canada",t:"idea"},
  "Ring_of_Fire": {d:"Tectonic belt of earthquakes and volcanoes",t:"idea"},
  "Rock-Hewn_Churches,_Lalibela": {d:"Eleven monolithic churches found in Lalibela, Amhara Region, Ethiopia",t:"go"},
  "Roman_Republic": {d:"Period of Roman history (c. 509 – 27 BC)",t:"event"},
  "Roman_roads": {d:"Roads built in service of the ancient Roman civilization",t:"event"},
  "Root": {d:"Basal organ of a vascular plant",t:"idea"},
  "Rosetta_Stone": {d:"Egyptian stele with three versions of a 196 BC decree",t:"idea"},
  "Router_(computing)": {d:"Device that forwards data packets between computer networks",t:"idea"},
  "Rust": {d:"Type of iron oxide",t:"idea"},
  "Rømer's_determination_of_the_speed_of_light": {d:"1676 demonstration of light's finite speed by Danish astronomer Ole Rømer",t:"person"},
  "SOS": {d:"International Morse code distress signal for help",t:"idea"},
  "Sacsayhuamán": {d:"Archaeological site near Cusco, Peru",t:"visit"},
  "Sahara": {d:"Desert on the African continent",t:"go"},
  "Salar_de_Uyuni": {d:"Salt flat in Bolivia",t:"idea"},
  "Saltwater_crocodile": {d:"Species of reptile",t:"idea"},
  "Samarkand": {d:"City in southeastern Uzbekistan",t:"go"},
  "Samsa_(food)": {d:"Savoury pie",t:"idea"},
  "Samurai": {d:"Japanese warrior class",t:"idea"},
  "Sardinia": {d:"Island in the Mediterranean and region of Italy",t:"go"},
  "Sargasso_Sea": {d:"Region of the North Atlantic Ocean",t:"go"},
  "Saturn": {d:"Sixth planet from the Sun",t:"idea"},
  "Sciatic_nerve": {d:"Large nerve in humans and other animals",t:"idea"},
  "Scurvy": {d:"Disease resulting from a lack of vitamin C",t:"idea"},
  "Seki_Takakazu": {d:"Japanese mathematician (c. 1642–1708)",t:"person"},
  "Semicircular_canals": {d:"Organ located in innermost part of ear",t:"idea"},
  "Sequoia_sempervirens": {d:"Species of tree",t:"idea"},
  "Sequoyah": {d:"Cherokee polymath and creator of the Cherokee syllabary",t:"idea"},
  "Serfdom": {d:"Status of peasants under feudalism",t:"idea"},
  "Server_(computing)": {d:"Computer providing a central resource or service",t:"idea"},
  "Seven_Bridges_of_Königsberg": {d:"Classic problem in graph theory",t:"idea"},
  "Seven_hills_of_Rome": {d:"Geographical heart of Rome, Italy, within the walls of the city",t:"go"},
  "Sexagesimal": {d:"Base sixty numeral system",t:"idea"},
  "Shah-i-Zinda": {d:"Necropolis in Samarkand, Uzbekistan",t:"idea"},
  "Shaka": {d:"Zulu king from 1816 to 1828",t:"person"},
  "Shibam": {d:"Town in Hadhramaut, Yemen",t:"go"},
  "Silicon": {d:"Chemical element with atomic number 14 (Si)",t:"idea"},
  "Silk_Road": {d:"Historical network of Eurasian trade routes",t:"idea"},
  "Simit": {d:"Circular bread from Turkey and the Balkans",t:"idea"},
  "Sine_and_cosine": {d:"Fundamental trigonometric functions",t:"idea"},
  "Singapore": {d:"Island country in Southeast Asia",t:"go"},
  "Singing_sand": {d:"Phenomenon of sand that produces sound",t:"idea"},
  "Sinoatrial_node": {d:"Group of cells in the wall of the heart",t:"idea"},
  "Sistine_Chapel_ceiling": {d:"Cycle of frescoes by Michelangelo",t:"idea"},
  "Small_intestine": {d:"Organ in the gastrointestinal tract",t:"idea"},
  "Socotra": {d:"Largest of four islands of the Socotra Archipelago, Yemen",t:"go"},
  "Sodium_bicarbonate": {d:"Chemical compound",t:"idea"},
  "Sodium_chloride": {d:"Chemical compound with formula NaCl",t:"idea"},
  "Sogdia": {d:"Ancient Iranian civilization (6th century BCE – 11th century CE)",t:"event"},
  "Solar_cell": {d:"Device used to produce electricity from light",t:"idea"},
  "Solar_eclipse": {d:"Event wherein the Sun is obscured by the Moon",t:"idea"},
  "Solomon_R._Guggenheim_Museum": {d:"Art museum in Manhattan, New York",t:"visit"},
  "Som_tam": {d:"Spicy salad made from unripe papaya",t:"idea"},
  "Songhai_Empire": {d:"Empire in West Africa from c. 1464 to 1591",t:"event"},
  "Songkran": {d:"Traditional Thai New Year's holiday",t:"idea"},
  "Sonic_boom": {d:"Shock wave from flying at the speed of sound",t:"idea"},
  "Sonnet": {d:"Poetic form, traditionally fourteen specifically rhymed lines",t:"person"},
  "Sophie_Wilson": {d:"English computer scientist (born 1957)",t:"person"},
  "Sound": {d:"Audible vibration that travels via pressure waves in matter",t:"idea"},
  "Souvlaki": {d:"Greek fast food",t:"idea"},
  "Speed_of_sound": {d:"Speed of sound wave through elastic medium",t:"idea"},
  "Spleen": {d:"Immune organ that filters blood",t:"idea"},
  "Srivijaya": {d:"Empire based on Sumatra (c. 671–1025 AD)",t:"person"},
  "Stapedius_muscle": {d:"Muscle in the human ear",t:"idea"},
  "Stapes": {d:"Bone of the middle ear",t:"idea"},
  "Steelpan": {d:"Musical instrument from Trinidad and Tobago",t:"idea"},
  "Stephenson's_Rocket": {d:"Steam locomotive by Robert Stephenson in 1829",t:"idea"},
  "Stockholm_archipelago": {d:"Archipelago east of Stockholm, Sweden",t:"go"},
  "Strait_of_Gibraltar": {d:"Strait connecting the Atlantic to the Mediterranean",t:"go"},
  "Structural_coloration": {d:"Colour in living creatures caused by interference effects",t:"idea"},
  "Suanpan": {d:"Chinese abacus",t:"idea"},
  "Submarine_communications_cable": {d:"Transoceanic communication line placed on the seabed",t:"idea"},
  "Suez_Canal": {d:"Artificial sea-level waterway in Egypt",t:"go"},
  "Sultan_Ahmed_Mosque": {d:"17th-century mosque in Turkey",t:"visit"},
  "Sun": {d:"Star at the centre of the Solar System",t:"idea"},
  "Sundarbans": {d:"Mangrove forest in the Bay of Bengal",t:"go"},
  "Sundiata_Keita": {d:"Founder and first ruler of the Mali Empire",t:"person"},
  "Sunlight": {d:"Light emitted by the Sun",t:"idea"},
  "Superb_lyrebird": {d:"Species of bird",t:"idea"},
  "Superconductivity": {d:"Electrical conductivity with exactly zero resistance",t:"idea"},
  "Suzani_(textile)": {d:"Embroidered tribal textile made in Central Asia and Iran",t:"idea"},
  "Swahili_coast": {d:"Coastal area of the Indian Ocean in southeast Africa",t:"go"},
  "Sydney_Opera_House": {d:"Performing arts centre in Australia",t:"idea"},
  "Symphony_No._9_(Beethoven)": {d:"1824 symphony by Ludwig van Beethoven",t:"work"},
  "Ta'ameya": {d:"Egyptian fava bean fritter",t:"idea"},
  "Table_Mountain": {d:"Mountain overlooking Cape Town, South Africa",t:"go"},
  "Tacoma_Narrows_Bridge_(1940)": {d:"Failed suspension bridge in Washington, US",t:"idea"},
  "Tacos_al_pastor": {d:"Mexican spit-grilled pork seasoned with adobada",t:"idea"},
  "Taghaza": {d:"Abandoned salt-mining settlement in Mali",t:"idea"},
  "Taj_Mahal": {d:"Marble mausoleum in Agra, India",t:"idea"},
  "Tajine": {d:"Maghrebi dish prepared in the earthenware pot of the same name",t:"idea"},
  "Tanjia": {d:"Cooking vessel",t:"idea"},
  "Tardigrade": {d:"Phylum of microscopic animals",t:"idea"},
  "Taíno": {d:"Indigenous people of the Caribbean",t:"idea"},
  "Teahouse": {d:"Cafe-type business serving tea",t:"idea"},
  "Temple_of_the_Emerald_Buddha": {d:"Buddhist temple in Bangkok, Thailand",t:"visit"},
  "Templo_Mayor": {d:"Former Aztec temple in Tenochtitlan (now Mexico City)",t:"visit"},
  "Ten_percent_of_the_brain_myth": {d:"Myth regarding human brain usage",t:"idea"},
  "Tenochtitlan": {d:"Former city-state in the Valley of Mexico",t:"go"},
  "Teotihuacan": {d:"Ancient Mesoamerican city",t:"go"},
  "Terracotta_Army": {d:"Collection of ancient Chinese military statues",t:"idea"},
  "The_Canon_of_Medicine": {d:"1025 Encyclopedia of medicine compiled by Avicenna",t:"idea"},
  "The_Great_Wave_off_Kanagawa": {d:"Woodblock print by Hokusai (1831)",t:"idea"},
  "The_Nine_Chapters_on_the_Mathematical_Art": {d:"Ancient Chinese mathematics text",t:"work"},
  "The_Rite_of_Spring": {d:"1913 ballet by Igor Stravinsky",t:"idea"},
  "The_Scream": {d:"1893 painting by Edvard Munch",t:"work"},
  "The_Starry_Night": {d:"1889 painting by Vincent van Gogh",t:"work"},
  "The_Tale_of_Genji": {d:"Classic work of Japanese literature",t:"idea"},
  "The_Thinker": {d:"Sculpture by Auguste Rodin",t:"work"},
  "Thermal_conduction": {d:"Process by which heat is transferred within an object",t:"idea"},
  "Thermopolium": {d:"Ancient Greco-Roman cookshop",t:"idea"},
  "Things_Fall_Apart": {d:"1958 novel by Chinua Achebe",t:"work"},
  "Thonburi_Kingdom": {d:"Kingdom in Southeast Asia (1767–1782)",t:"person"},
  "Thoracic_diaphragm": {d:"Sheet of internal skeletal muscle",t:"idea"},
  "Three-toed_sloth": {d:"Genus of mammals",t:"idea"},
  "Three_Sisters_(agriculture)": {d:"Agricultural technique of Indigenous people in the Americas",t:"idea"},
  "Thymus": {d:"Endocrine gland",t:"idea"},
  "Thyroid": {d:"Endocrine gland in the neck",t:"idea"},
  "Tidal_locking": {d:"Situation in which an astronomical object's orbital period matches its rotational period",t:"event"},
  "Tideway": {d:"Part of the River Thames subject to tides",t:"go"},
  "Tifinagh": {d:"Script used for Berber languages",t:"idea"},
  "Tiger": {d:"Species of large cat",t:"idea"},
  "Tim_Berners-Lee": {d:"English computer scientist (born 1955)",t:"person"},
  "Timbuktu": {d:"City in Tombouctou Region, Mali",t:"go"},
  "Timbuktu_Manuscripts": {d:"Manuscripts preserved in Timbuktu, Mali",t:"idea"},
  "Time_in_Russia": {d:"Time spanning Europe and Asia",t:"idea"},
  "Timur": {d:"Turco-Mongol conqueror (1320s–1405)",t:"person"},
  "Tokyo": {d:"Capital and most populous city in Japan",t:"go"},
  "Tom_yum": {d:"Thai soup",t:"idea"},
  "Tommy_Flowers": {d:"English engineer (1905–1998)",t:"person"},
  "Tongue_map": {d:"Misconception about taste and the tongue",t:"idea"},
  "Tooth_enamel": {d:"Major tissue that makes up part of the tooth in humans and many animals",t:"idea"},
  "Tornado": {d:"Violently rotating column of air",t:"idea"},
  "Trachea": {d:"Cartilaginous tube",t:"idea"},
  "Training,_validation,_and_test_data_sets": {d:"Tasks in machine learning",t:"idea"},
  "Trans-Saharan_trade": {d:"Trade between sub-Saharan Africa and North Africa",t:"idea"},
  "Transformer_(deep_learning)": {d:"Algorithm for modelling sequential data",t:"idea"},
  "Trevi_Fountain": {d:"Fountain in Rome, Italy",t:"idea"},
  "Trojan_Room_coffee_pot": {d:"Predecessor of the webcam",t:"idea"},
  "Tsingy_de_Bemaraha_Strict_Nature_Reserve": {d:"Strict nature reserve of Madagascar",t:"idea"},
  "Tu_Youyou": {d:"Chinese pharmaceutical chemist (born 1930)",t:"person"},
  "Tuned_mass_damper": {d:"Device designed to reduce vibrations in structures",t:"idea"},
  "Turing_test": {d:"Test of a machine's ability to imitate human intelligence",t:"idea"},
  "Turkish_bath": {d:"Place of public bathing common in Muslim societies",t:"idea"},
  "Turkish_delight": {d:"Gelatinous candy",t:"idea"},
  "Turritopsis_dohrnii": {d:"Species of small, biologically immortal jellyfish",t:"idea"},
  "Tutankhamun": {d:"Pharaoh of Egypt from 1333 to 1324 BC",t:"person"},
  "Twelve-angled_stone": {d:"Incan archaeological artifact in Peru",t:"visit"},
  "Tyrian_purple": {d:"Natural dye extracted from Murex sea snails",t:"go"},
  "Tzistarakis_Mosque": {d:"Former mosque, now museum, in Athens, Greece",t:"visit"},
  "Uji": {d:"City in Kansai, Japan",t:"go"},
  "Ulaanbaatar": {d:"Capital and largest city of Mongolia",t:"go"},
  "Ulugh_Beg": {d:"Timurid sultan, astronomer and mathematician (1394–1449)",t:"person"},
  "Ulugh_Beg_Observatory": {d:"Observatory in Samarkand, Uzbekistan",t:"visit"},
  "Uluru": {d:"Sandstone monolith in the Northern Territory, Australia",t:"idea"},
  "Umm_Kulthum": {d:"Egyptian singer-songwriter and actress (1904–1975)",t:"person"},
  "Units_of_information": {d:"Unit of measure for digital data",t:"idea"},
  "University_of_Oxford": {d:"Collegiate research university in England",t:"idea"},
  "University_of_al-Qarawiyyin": {d:"University in Fez, Morocco",t:"idea"},
  "Uzbek_cuisine": {d:"Culinary traditions of Uzbekistan",t:"idea"},
  "Vacuum_flask": {d:"Double-walled insulated storage vessel",t:"idea"},
  "Vagus_nerve": {d:"Main nerve of the parasympathetic nervous system",t:"idea"},
  "Vapor-compression_refrigeration": {d:"Refrigeration process",t:"idea"},
  "Vatican_City": {d:"Enclaved Holy See's independent city-state",t:"go"},
  "Venice": {d:"City in Veneto, Italy",t:"go"},
  "Venus": {d:"Second planet from the Sun",t:"idea"},
  "Vibe_coding": {d:"AI-dependent computer programming",t:"idea"},
  "Victoria_Falls": {d:"Waterfall on the Zambezi River in Zambia and Zimbabwe",t:"go"},
  "View_from_the_Window_at_Le_Gras": {d:"Oldest surviving camera photograph",t:"idea"},
  "Vint_Cerf": {d:"American computer scientist and Internet pioneer (born 1943)",t:"person"},
  "Violin": {d:"Bowed string instrument",t:"idea"},
  "Voltaic_pile": {d:"First electrical battery that could continuously provide an electric current to a circuit",t:"idea"},
  "Voyager_1": {d:"NASA space probe launched in 1977",t:"idea"},
  "Wai_(gesture)": {d:"Gesture used in Thailand",t:"idea"},
  "Walls_of_Benin": {d:"Historic moat in Nigeria",t:"idea"},
  "Wang_Zhenyi_(astronomer)": {d:"Chinese astronomer (1768–1797)",t:"person"},
  "Washington_Monument": {d:"U.S. national memorial in Washington, D.C.",t:"visit"},
  "Wat_Pho": {d:"Buddhist temple in Phra Nakhon district, Bangkok, Thailand",t:"visit"},
  "Web_browser": {d:"Software used to access websites",t:"idea"},
  "Web_crawler": {d:"Software that systematically browses the World Wide Web",t:"idea"},
  "Wellington": {d:"Capital city of New Zealand",t:"go"},
  "Welwitschia": {d:"Monotypic genus of plants",t:"idea"},
  "Wheat_and_chessboard_problem": {d:"Mathematical problem",t:"idea"},
  "White_blood_cell": {d:"Type of cells of the immunological system",t:"idea"},
  "Wi-Fi": {d:"Family of wireless network protocols",t:"idea"},
  "Wilhelm_Röntgen": {d:"German physicist (1845–1923)",t:"person"},
  "William_Harvey": {d:"English physician (1578–1657)",t:"person"},
  "Windcatcher": {d:"Architectural element for creating a draft",t:"idea"},
  "Wombat": {d:"Species of marsupial native to Australia",t:"idea"},
  "World_Wide_Web": {d:"Linked hypertext system on the Internet",t:"idea"},
  "Wreck_of_the_Titanic": {d:"Shipwreck in the North Atlantic Ocean",t:"go"},
  "Wright_brothers": {d:"American aviation pioneers, inventors of the airplane",t:"person"},
  "Xochimilco": {d:"Borough in Mexico City, Mexico",t:"go"},
  "Yaa_Asantewaa": {d:"Ashanti queen mother and military leader",t:"person"},
  "Yam_(route)": {d:"Postal service system originating from the Mongol period",t:"event"},
  "Yoruba_numerals": {d:"Numerals in Yorùbá Language",t:"idea"},
  "Yuan_dynasty": {d:"Mongol-led dynasty of China (1271–1368)",t:"person"},
  "Zhang_Heng": {d:"Chinese scientist and statesman (78–139)",t:"person"},
  "Zheng_He": {d:"Chinese admiral and diplomat (1371–1433/1435)",t:"person"},
  "Zimbabwe_Bird": {d:"National emblem of Zimbabwe",t:"idea"},
  "Zu_Chongzhi": {d:"Chinese mathematician-astronomer (429–500)",t:"person"},
  "Zócalo": {d:"Plaza de la Constitución, Mexico City",t:"go"},
};
