// © 2026 Qpio. All rights reserved. Not covered by the MIT LICENSE.
// Terms of use: /CONTENT-LICENCE.md · Machine use reserved: /ai.txt
//
// GENERATED — do not hand-edit. Rebuild with: py tools/fetch_fr_titles.py
//
// The French name of each entity, and the French Wikipedia article, taken
// from Wikipedia's own interlanguage links. A lookup, not a translation:
// these are the titles the French Wikipedia community chose themselves.
// Baked at build time so the app never touches the network to render.
//
// 719 of 741 entities have a French article (97.0%). The rest keep their
// English name, which is correct — not every subject has a French page.

window.CURIO_FR_ENTITIES = {
  "1883_eruption_of_Krakatoa": "Éruption du Krakatoa en 1883",
  "API": "Interface de programmation",
  "ARPANET": "ARPANET",
  "A_Trip_to_the_Moon": "Le Voyage dans la Lune",
  "Abd_al-Rahman_al-Sufi": "Abd al-Rahman al-Soufi",
  "Abdelkader_ibn_Muhieddine": "Abdelkader (émir)",
  "Aboriginal_Australians": "Aborigènes d'Australie",
  "Absolute_zero": "Zéro absolu",
  "Achilles_tendon": "Tendon calcanéen",
  "Active_noise_control": "Contrôle actif du bruit",
  "Ada_Lovelace": "Ada Lovelace",
  "Adansonia": "Adansonia",
  "Adrenal_gland": "Glande surrénale",
  "Africa": "Afrique",
  "African_bush_elephant": "Éléphant de savane d'Afrique",
  "Ah!_vous_dirai-je,_maman": "Ah ! vous dirai-je, maman",
  "Ahmad_ibn_Ibrahim_al-Ghazi": "Ahmed Ibn Ibrahim Al-Ghazi",
  "Akan_goldweights": "Poids à peser l'or",
  "Al-Azhar_Mosque": "Mosquée Al-Azhar",
  "Al-Khwarizmi": "Al-Khwârizmî",
  "Al-Kindi": "Al-Kindi",
  "Alaska_Purchase": "Achat de l'Alaska",
  "Albert_Einstein": "Albert Einstein",
  "Ali_Farka_Touré": "Ali Farka Touré",
  "Allotropes_of_carbon": "Allotropie du carbone",
  "Almoravid_dynasty": "Almoravides",
  "Along_the_River_During_the_Qingming_Festival": "La Fête de Qingming au bord de la rivière",
  "AlphaGo": "AlphaGo",
  "Amanirenas": "Amanirenas",
  "Amazon_River": "Amazone (fleuve)",
  "Amelia_Earhart": "Amelia Earhart",
  "Amina_of_Zazzau": "Amina de Zaria",
  "Ancient_Olympic_Games": "Jeux olympiques antiques",
  "Andes": "Cordillère des Andes",
  "Andreas_Vesalius": "André Vésale",
  "Angel_Falls": "Salto Ángel",
  "Angkor_Wat": "Angkor Vat",
  "Anglerfish": "Lophiiformes",
  "Antarctica": "Antarctique",
  "Apollo_11": "Apollo 11",
  "Apollo_15": "Apollo 15",
  "Archerfish": "Toxotidae",
  "Archimedes'_principle": "Poussée d'Archimède",
  "Arctic_tern": "Sterne arctique",
  "Armillaria_ostoyae": "Armillaria solidipes",
  "Aryabhata": "Aryabhata",
  "Ashoka": "Ashoka",
  "Atacama_Desert": "Désert d'Atacama",
  "Athenian_democracy": "Démocratie athénienne",
  "Athens": "Athènes",
  "Atomic_nucleus": "Noyau atomique",
  "Augustus": "Auguste",
  "Aurora": "Aurore polaire",
  "Australian_Aboriginal_astronomy": "Astronomie des Aborigènes d'Australie",
  "Axolotl": "Axolotl",
  "Aye-aye": "Aye-aye",
  "Ayutthaya_Kingdom": "Royaume d'Ayutthaya",
  "Aztec_Empire": "Empire aztèque",
  "Banana_equivalent_dose": "Dose équivalente en banane",
  "Baqt": "Baqt",
  "Bar-tailed_godwit": "Barge rousse",
  "Barcode": "Code-barres",
  "Bat": "Chiroptera",
  "Batik": "Batik",
  "Battle_of_Adwa": "Bataille d'Adoua",
  "Battle_of_Ain_Jalut": "Bataille d'Aïn Djalout",
  "Bee_hummingbird": "Colibri d'Elena",
  "Benin_Bronzes": "Bronzes du Bénin",
  "Benjamin_Banneker": "Benjamin Banneker",
  "Berry_(botany)": "Baie (botanique)",
  "Bharatanatyam": "Bharata natyam",
  "Binary_number": "Système binaire",
  "Black_Death": "Peste noire",
  "Blue_whale": "Baleine bleue",
  "Blues": "Blues",
  "Bluetooth": "Bluetooth",
  "Boiling_point": "Point d'ébullition",
  "Bolivian_Navy": "Marine bolivienne",
  "Bombardier_beetle": "Coléoptère bombardier",
  "Bone_marrow": "Moelle osseuse",
  "Bosporus": "Bosphore",
  "Bossa_nova": "Bossa nova",
  "Brahmagupta": "Brahmagupta",
  "Brasília": "Brasilia",
  "Buddhism_in_Thailand": "Bouddhisme en Thaïlande",
  "Buddhist_cuisine": "Cuisine bouddhique",
  "Buganda": "Buganda",
  "Byte": "Byte",
  "Byte-pair_encoding": "Byte pair encoding",
  "Bògòlanfini": "Bogolan",
  "C._V._Raman": "Chandrashekhara Venkata Râman",
  "Cacio_e_pepe": "Cacio e pepe",
  "Cahokia": "Cahokia",
  "Cairo": "Le Caire",
  "Can't_Buy_Me_Love": "Can't Buy Me Love",
  "Canada–United_States_border": "Frontière entre le Canada et les États-Unis",
  "Canberra": "Canberra",
  "Capillary": "Capillaire sanguin",
  "Carbonara": "Pâtes à la carbonara",
  "Carthage": "Carthage",
  "Cattle": "Bos taurus",
  "Celesta": "Célesta",
  "Central_processing_unit": "CPU",
  "Cerebellum": "Cervelet",
  "Cervical_vertebrae": "Vertèbre cervicale",
  "Challenger_Deep": "Challenger Deep",
  "Chandrayaan-3": "Chandrayaan-3",
  "Chartres_Cathedral": "Cathédrale Notre-Dame de Chartres",
  "Cheetah": "Guépard",
  "Chicha_morada": "Chicha morada",
  "Chicxulub_crater": "Cratère de Chicxulub",
  "Chieko_Asakawa": "Chieko Asakawa",
  "Chinampa": "Chinampa",
  "Chinguetti": "Chinguetti",
  "Chlorophyll": "Chlorophylle",
  "Christmas_Island_red_crab": "Gecarcoidea natalis",
  "Christopher_Columbus": "Christophe Colomb",
  "Chromosome": "Chromosome",
  "Cleopatra": "Cléopâtre VII",
  "Cloud_computing": "Cloud computing",
  "Clownfish": "Poisson-clown",
  "Code_of_Hammurabi": "Code de Hammurabi",
  "Coelacanth": "Coelacanthiformes",
  "Colosseum": "Colisée",
  "Commedia_dell'arte": "Commedia dell'arte",
  "Common_cuckoo": "Coucou gris",
  "Common_ostrich": "Autruche d'Afrique",
  "Compass": "Boussole",
  "Computer_mouse": "Souris (informatique)",
  "Continental_drift": "Dérive des continents",
  "Coral": "Corail",
  "Coricancha": "Temple du Soleil (Cuzco)",
  "Cornea": "Cornée",
  "Couscous": "Couscous",
  "Crab_Nebula": "Nébuleuse du Crabe",
  "Credential_stuffing": "Credential stuffing",
  "Cuneiform": "Écriture cunéiforme",
  "Cusco": "Cuzco",
  "Cyrus_Cylinder": "Cylindre de Cyrus",
  "DJ_Kool_Herc": "DJ Kool Herc",
  "DNA": "Acide désoxyribonucléique",
  "Dahomey_Amazons": "Amazones du Dahomey",
  "Danube": "Danube",
  "Day_of_the_Dead": "Jour des morts (Mexique)",
  "Dead_Sea": "Mer Morte",
  "Deep_Blue_(chess_computer)": "Deep Blue",
  "Deepfake": "Deepfake",
  "Desert": "Désert",
  "Diamond": "Diamant",
  "Diomede_Islands": "Îles Diomède",
  "Djenné-Djenno": "Djenné-Djeno",
  "Dmitri_Mendeleev": "Dmitri Mendeleïev",
  "Dodo": "Dodo (oiseau)",
  "Domain_Name_System": "Domain Name System",
  "Don_Quixote": "Don Quichotte",
  "Donald_Davies": "Donald Davies",
  "Doppler_effect": "Effet Doppler",
  "Dorothy_Vaughan": "Dorothy Vaughan",
  "Double-slit_experiment": "Expérience de la double fente",
  "Douglas_Engelbart": "Douglas Engelbart",
  "Dresden_Codex": "Codex de Dresde",
  "Dromedary": "Dromadaire",
  "Dung_beetle": "Bousier",
  "ELIZA": "ELIZA",
  "ENIAC": "ENIAC",
  "Earth's_rotation": "Rotation de la Terre",
  "Earthworm": "Lumbricina",
  "Eiffel_Tower": "Tour Eiffel",
  "El_Niño": "El Niño – Oscillation australe",
  "Electric_eel": "Electrophorus",
  "Electromagnetic_induction": "Induction électromagnétique",
  "Electromagnetic_radiation": "Rayonnement électromagnétique",
  "Electron": "Électron",
  "Elgin_Marbles": "Marbres d'Elgin",
  "Elisha_Otis": "Elisha Otis",
  "Elizabeth_J._Feinler": "Elizabeth J. Feinler",
  "Emmy_Noether": "Emmy Noether",
  "Emperor_penguin": "Manchot empereur",
  "End-to-end_encryption": "Chiffrement de bout en bout",
  "Environmental_impact_of_AI": "Impacts environnementaux de l'intelligence artificielle",
  "Epic_of_Gilgamesh": "Épopée de Gilgamesh",
  "Epidermis": "Épiderme (anatomie)",
  "Eratosthenes": "Ératosthène",
  "Ethiopian_calendar": "Calendrier éthiopien",
  "Evzones": "Evzones",
  "Fahrenheit": "Degré Fahrenheit",
  "Fall_of_Constantinople": "Chute de Constantinople",
  "Fasil_Ghebbi": "Fasil Ghebi",
  "Fela_Kuti": "Fela Kuti",
  "Femur": "Fémur",
  "Fibonacci": "Leonardo Fibonacci",
  "Fibonacci_sequence": "Suite de Fibonacci",
  "Flag_of_Albania": "Drapeau de l'Albanie",
  "Flag_of_Argentina": "Drapeau de l'Argentine",
  "Flag_of_Australia": "Drapeau de l'Australie",
  "Flag_of_Bangladesh": "Drapeau du Bangladesh",
  "Flag_of_Belgium": "Drapeau de la Belgique",
  "Flag_of_Bhutan": "Drapeau du Bhoutan",
  "Flag_of_Botswana": "Drapeau du Botswana",
  "Flag_of_Brazil": "Drapeau du Brésil",
  "Flag_of_Cambodia": "Drapeau du Cambodge",
  "Flag_of_Canada": "Drapeau du Canada",
  "Flag_of_Chile": "Drapeau du Chili",
  "Flag_of_Colombia": "Drapeau de la Colombie",
  "Flag_of_Cuba": "Drapeau de Cuba",
  "Flag_of_Egypt": "Drapeau de l'Égypte",
  "Flag_of_Ethiopia": "Drapeau de l'Éthiopie",
  "Flag_of_Fiji": "Drapeau des Fidji",
  "Flag_of_Finland": "Drapeau de la Finlande",
  "Flag_of_France": "Drapeau de la France",
  "Flag_of_Germany": "Drapeau de l'Allemagne",
  "Flag_of_Ghana": "Drapeau du Ghana",
  "Flag_of_Greece": "Drapeau de la Grèce",
  "Flag_of_Iceland": "Drapeau de l'Islande",
  "Flag_of_India": "Drapeau de l'Inde",
  "Flag_of_Indonesia": "Drapeau de l'Indonésie",
  "Flag_of_Iran": "Drapeau de l'Iran",
  "Flag_of_Ireland": "Drapeau de l'Irlande",
  "Flag_of_Israel": "Drapeau d'Israël",
  "Flag_of_Italy": "Drapeau de l'Italie",
  "Flag_of_Jamaica": "Drapeau de la Jamaïque",
  "Flag_of_Japan": "Drapeau du Japon",
  "Flag_of_Jordan": "Drapeau de la Jordanie",
  "Flag_of_Kazakhstan": "Drapeau du Kazakhstan",
  "Flag_of_Kenya": "Drapeau du Kenya",
  "Flag_of_Lebanon": "Drapeau du Liban",
  "Flag_of_Mali": "Drapeau du Mali",
  "Flag_of_Mexico": "Drapeau du Mexique",
  "Flag_of_Mongolia": "Drapeau de la Mongolie",
  "Flag_of_Morocco": "Drapeau du Maroc",
  "Flag_of_Mozambique": "Drapeau du Mozambique",
  "Flag_of_Namibia": "Drapeau de la Namibie",
  "Flag_of_Nepal": "Drapeau du Népal",
  "Flag_of_New_Zealand": "Drapeau de la Nouvelle-Zélande",
  "Flag_of_Nigeria": "Drapeau du Nigeria",
  "Flag_of_Norway": "Drapeau de la Norvège",
  "Flag_of_Papua_New_Guinea": "Drapeau de la Papouasie-Nouvelle-Guinée",
  "Flag_of_Peru": "Drapeau du Pérou",
  "Flag_of_Poland": "Drapeau de la Pologne",
  "Flag_of_Portugal": "Drapeau du Portugal",
  "Flag_of_Qatar": "Drapeau du Qatar",
  "Flag_of_Romania": "Drapeau de la Roumanie",
  "Flag_of_Rwanda": "Drapeau du Rwanda",
  "Flag_of_Saudi_Arabia": "Drapeau de l'Arabie saoudite",
  "Flag_of_Senegal": "Drapeau du Sénégal",
  "Flag_of_South_Africa": "Drapeau de l'Afrique du Sud",
  "Flag_of_South_Korea": "Drapeau de la Corée du Sud",
  "Flag_of_Spain": "Drapeau de l'Espagne",
  "Flag_of_Sri_Lanka": "Drapeau du Sri Lanka",
  "Flag_of_Sweden": "Drapeau de la Suède",
  "Flag_of_Switzerland": "Drapeau et armoiries de la Suisse",
  "Flag_of_Tanzania": "Drapeau de la Tanzanie",
  "Flag_of_Thailand": "Drapeau de la Thaïlande",
  "Flag_of_Turkey": "Drapeau de la Turquie",
  "Flag_of_Ukraine": "Drapeau de l'Ukraine",
  "Flag_of_Uruguay": "Drapeau de l'Uruguay",
  "Flag_of_Vietnam": "Drapeau du Vietnam",
  "Flag_of_the_Netherlands": "Drapeau des Pays-Bas",
  "Flag_of_the_Philippines": "Drapeau des Philippines",
  "Flag_of_the_United_Arab_Emirates": "Drapeau des Émirats arabes unis",
  "Flash_memory": "Mémoire flash",
  "Florence_Nightingale": "Florence Nightingale",
  "Flying_buttress": "Arc-boutant",
  "Four-stroke_engine": "Moteur à quatre temps",
  "Frappé_coffee": "Café frappé",
  "Fresco": "Fresque",
  "Frida_Kahlo": "Frida Kahlo",
  "Fundamental_interaction": "Interaction élémentaire",
  "Fushimi_Inari-taisha": "Fushimi Inari-taisha",
  "Gabriela_Mistral": "Gabriela Mistral",
  "Gastric_acid": "Suc gastrique",
  "Geisha": "Geisha",
  "Geography_of_Saudi_Arabia": "Géographie de l'Arabie saoudite",
  "Ghana": "Ghana",
  "Ghana_Empire": "Empire du Ghana",
  "Gion": "Gion",
  "Gladys_West": "Gladys West",
  "Glass": "Verre",
  "Global_Positioning_System": "Global Positioning System",
  "Gluteus_maximus": "Muscle grand glutéal",
  "Gold": "Or",
  "Golden_Stool": "Trône royal Ashanti",
  "Goldfish": "Poisson rouge",
  "Google_Chrome": "Google Chrome",
  "Grace_Hopper": "Grace Hopper",
  "Grand_Palace": "Palais royal (Bangkok)",
  "Graphics_processing_unit": "Processeur graphique",
  "Great_Barrier_Reef": "Grande Barrière de corail",
  "Great_Law_of_Peace": "Constitution iroquoise",
  "Great_Mosque_of_Djenné": "Grande mosquée de Djenné",
  "Great_Pyramid_of_Giza": "Pyramide de Khéops",
  "Great_Sphinx_of_Giza": "Sphinx de Gizeh",
  "Great_Wall_of_China": "Grande Muraille",
  "Great_Zimbabwe": "Grand Zimbabwe",
  "Greater_flamingo": "Flamant rose",
  "Greater_honeyguide": "Grand Indicateur",
  "Guernica_(Picasso)": "Guernica (Picasso)",
  "Guinea_pig": "Cavia porcellus",
  "Gunpowder": "Poudre noire",
  "HTTP": "Hypertext Transfer Protocol",
  "HTTPS": "Hypertext Transfer Protocol Secure",
  "HTTP_cookie": "Cookie (informatique)",
  "Hafele–Keating_experiment": "Expérience de Hafele-Keating",
  "Hagia_Sophia": "Sainte-Sophie (Constantinople)",
  "Hallucination_(artificial_intelligence)": "Hallucination (intelligence artificielle)",
  "Hangul": "Hangeul",
  "Hannibal": "Hannibal Barca",
  "Hanseatic_League": "Hanse",
  "Harar": "Harar",
  "Heart": "Cœur",
  "Hedy_Lamarr": "Hedy Lamarr",
  "Hemoglobin": "Hémoglobine",
  "Herbivore": "Herbivore",
  "Hexadecimal": "Système hexadécimal",
  "Hippocampus": "Hippocampe (cerveau)",
  "History_of_chocolate": "Histoire de la culture du cacao",
  "Honey": "Miel",
  "Honey_bee": "Apis (insecte)",
  "Horned_helmet": "Casque à cornes",
  "House_of_Wisdom": "Maison de la sagesse",
  "Huffman_coding": "Codage de Huffman",
  "Human_microbiome": "Microbiote de l'organisme humain",
  "Human_skin": "Peau humaine",
  "Human_tooth": "Dent (anatomie humaine)",
  "Hundred_Years'_War": "Guerre de Cent Ans",
  "Hydrogen": "Hydrogène",
  "Hypatia": "Hypatie",
  "IP_address": "Adresse IP",
  "Ibn_Battuta": "Ibn Battûta",
  "Ibn_al-Haytham": "Alhazen",
  "Ibn_al-Nafis": "Ibn al-Nafis",
  "Ice": "Glace",
  "Ife": "Ife",
  "Igbo-Ukwu": "Igbo-Ukwu",
  "ImageNet": "ImageNet",
  "Impression,_Sunrise": "Impression, soleil levant",
  "Inca_road_system": "Chemins incas",
  "Incandescent_light_bulb": "Lampe à incandescence",
  "Inclined_plane": "Plan incliné",
  "Indian_Ocean": "Océan Indien",
  "Industrial_Revolution": "Révolution industrielle",
  "Insect": "Insecte",
  "Inti_Raymi": "Inti Raymi",
  "Iron": "Fer",
  "Ishango_bone": "Os d'Ishango",
  "Islamic_calligraphy": "Calligraphie islamique",
  "Istanbul": "Istanbul",
  "James_Watt": "James Watt",
  "Jantar_Mantar,_Jaipur": "Yantra Mandir",
  "Japanese_tea_ceremony": "Cérémonie du thé japonaise",
  "Jemaa_el-Fnaa": "Place Jemaa el-Fna",
  "Joseph_Fourier": "Joseph Fourier",
  "Joy_Buolamwini": "Joy Buolamwini",
  "Justinian_I": "Justinien Ier",
  "Kairouan": "Kairouan",
  "Kaiseki": "Kaiseki",
  "Kanem–Bornu_Empire": "Royaume du Kanem-Bornou",
  "Kangaroo": "Kangourou",
  "Kapnikarea": "Église de la Panagía Kapnikaréa",
  "Karen_Spärck_Jones": "Karen Spärck Jones",
  "Katherine_Johnson": "Katherine Johnson",
  "Kente_cloth": "Kente (Ghana)",
  "Khan_el-Khalili": "Khân al-Khalili",
  "Kilwa_Kisiwani": "Kilwa Kisiwani",
  "Kilwa_Sultanate": "Sultanat de Kilwa",
  "Kind_of_Blue": "Kind of Blue",
  "Kingdom_of_Aksum": "Royaume d'Aksoum",
  "Kingdom_of_Kongo": "Royaume du Kongo",
  "Kingdom_of_Mutapa": "Empire du Monomotapa",
  "Kinkaku-ji": "Kinkaku-ji",
  "Kintsugi": "Kintsugi",
  "Kiyomizu-dera": "Kiyomizu-dera",
  "Kora_(instrument)": "Kora",
  "Koshari": "Kochari",
  "Koutoubia_Mosque": "Mosquée Koutoubia",
  "Kyoto": "Kyoto",
  "L'Anse_aux_Meadows": "L'Anse aux Meadows",
  "La_Paz": "La Paz",
  "Lake_Baikal": "Lac Baïkal",
  "Lake_Victoria": "Lac Victoria",
  "Landlocked_country": "Pays sans littoral",
  "Large_intestine": "Gros intestin",
  "Large_language_model": "Grand modèle de langage",
  "Leafcutter_ant": "Fourmi coupe-feuille",
  "Leatherback_sea_turtle": "Tortue luth",
  "Leptis_Magna": "Leptis Magna",
  "Lesotho": "Lesotho",
  "Light-emitting_diode": "Diode électroluminescente",
  "Light-year": "Année-lumière",
  "Lightning": "Foudre",
  "Lion": "Lion",
  "List_of_bones_of_the_human_skeleton": "Liste des os du squelette humain",
  "List_of_islands_by_area": "Liste d'îles par superficie",
  "Lithium-ion_battery": "Accumulateur lithium-ion",
  "Liver": "Foie",
  "Lukasa": "Lukasa",
  "Lunar_Laser_Ranging_experiments": "Réflecteur lunaire",
  "Machine_learning": "Apprentissage automatique",
  "Machu_Picchu": "Machu Picchu",
  "Macintosh_128K": "Macintosh 128K",
  "Madhava_of_Sangamagrama": "Madhava de Sangamagrama",
  "Magdeburg_hemispheres": "Hémisphères de Magdebourg",
  "Maghrebi_mint_tea": "Thé à la menthe",
  "Magna_Carta": "Magna Carta",
  "Majapahit": "Majapahit",
  "Malick_Sidibé": "Malick Sidibé",
  "Mangrove": "Palétuvier",
  "Mansa_Musa": "Mansa Moussa",
  "Mantis_shrimp": "Stomatopoda",
  "Margaret_Hamilton_(software_engineer)": "Margaret Hamilton (scientifique)",
  "Marian_Rejewski": "Marian Rejewski",
  "Marie_Curie": "Marie Curie",
  "Marie_Tharp": "Marie Tharp",
  "Mark_Dean_(computer_scientist)": "Mark Dean",
  "Marrakesh": "Marrakech",
  "Maryam_Mirzakhani": "Maryam Mirzakhani",
  "Masinissa": "Massinissa",
  "Mass–energy_equivalence": "E=mc2",
  "Mauna_Kea": "Mauna Kea",
  "Maya_numerals": "Numération maya",
  "Maya_script": "Écriture maya",
  "Mayflower": "Mayflower",
  "Melanin": "Mélanine",
  "Mercury_(planet)": "Mercure (planète)",
  "Merina_Kingdom": "Royaume de Merina",
  "Meroitic_script": "Alphabet méroïtique",
  "Mevlevi_order": "Ordre mevlevi",
  "Mexican_muralism": "Muralisme mexicain",
  "Microwave_oven": "Four à micro-ondes",
  "Milky_Way": "Voie lactée",
  "Milutin_Milanković": "Milutin Milanković",
  "Mirage": "Mirage",
  "Mitochondrion": "Mitochondrie",
  "Moai": "Moaï",
  "Model_Context_Protocol": "Model Context Protocol",
  "Mole_(sauce)": "Mole (sauce)",
  "Mona_Lisa": "La Joconde",
  "Monsoon": "Mousson",
  "Mosque_of_Ibn_Tulun": "Mosquée Ibn Touloun",
  "Mount_Everest": "Everest",
  "Mount_Fuji": "Mont Fuji",
  "Mount_Kilimanjaro": "Kilimandjaro",
  "Mount_Tambora": "Tambora",
  "Moussaka": "Moussaka",
  "Mulukhiyah": "Mloukhiya",
  "Mycorrhiza": "Mycorhize",
  "Naguib_Mahfouz": "Naguib Mahfouz",
  "Nahuatl": "Nahuatl",
  "Nairobi_National_Park": "Parc national de Nairobi",
  "Naked_mole-rat": "Rat-taupe nu",
  "Name_day": "Fête du prénom",
  "Nana_Asma'u": "Nana Asma’u",
  "Napoleon": "Napoléon Ier",
  "Nazar_(amulet)": "Nazar boncuk",
  "Near-field_communication": "Near-field communication",
  "Nephron": "Néphron",
  "Netherlands": "Pays-Bas (pays constitutif)",
  "Newton_(unit)": "Newton (unité)",
  "Nii_Quaynor": "Nii Quaynor",
  "Nile": "Nil",
  "Ninety-five_Theses": "95 thèses",
  "Nitrogen_fixation": "Fixation biologique du diazote",
  "Nocturnality": "Nocturne (comportement animal)",
  "Nok_culture": "Nok (culture)",
  "North_Pole": "Pôle Nord",
  "Nowruz": "Norouz",
  "Nubian_pyramids": "Pyramides nubiennes",
  "Nzinga_of_Ndongo_and_Matamba": "Njinga du Ndongo et du Matamba",
  "Obelisk_of_Axum": "May-Hedja",
  "Oboe": "Hautbois",
  "Octopus": "Octopoda",
  "Odyssey": "Odyssée",
  "Ohm": "Ohm (unité)",
  "Okapi": "Okapi",
  "Olympus_Mons": "Olympus Mons",
  "Omar_Khayyam": "Omar Khayyam",
  "One_Hundred_Years_of_Solitude": "Cent Ans de solitude",
  "One_Thousand_and_One_Nights": "Les Mille et Une Nuits",
  "Open-source_software": "Logiciel open source",
  "Ophiocordyceps_unilateralis": "Ophiocordyceps unilateralis",
  "Optical_fiber": "Fibre optique",
  "Ousmane_Sembène": "Ousmane Sembène",
  "Oyo_Empire": "Empire d'Oyo",
  "Ozone_layer": "Couche d'ozone",
  "PH": "Potentiel hydrogène",
  "Pacific_Ocean": "Océan Pacifique",
  "Packet_switching": "Commutation de paquets",
  "Pad_thai": "Phat thai",
  "Panama_Canal": "Canal de Panama",
  "Pancreas": "Pancréas",
  "Pangolin": "Pholidota",
  "Pansori": "Pansori",
  "Pantheon,_Rome": "Panthéon (Rome)",
  "Papunya_Tula": "Papunya Tula",
  "Parthenon": "Parthénon",
  "Password_strength": "Robustesse d'un mot de passe",
  "Patch_(computing)": "Patch (informatique)",
  "Peace_of_Westphalia": "Traités de Westphalie",
  "Pecorino_Romano": "Pecorino romano",
  "Penicillin": "Pénicilline",
  "Persepolis": "Persépolis",
  "Persian_miniature": "Miniature persane",
  "Petra": "Pétra",
  "Phishing": "Hameçonnage",
  "Phoenician_alphabet": "Alphabet phénicien",
  "Photoelectric_effect": "Effet photoélectrique",
  "Photosynthesis": "Photosynthèse",
  "Pi": "Pi",
  "Piano": "Piano",
  "Pilaf": "Riz pilaf",
  "Piye": "Piânkhy",
  "Platypus": "Ornithorynque",
  "Plimpton_322": "Plimpton 322",
  "Pompeii": "Pompéi",
  "Potato": "Pomme de terre",
  "Pretoria": "Pretoria",
  "Prime_number": "Nombre premier",
  "Printing_press": "Presse typographique",
  "Private_browsing": "Navigation privée",
  "Problem_of_points": "Problème des partis",
  "Prompt_engineering": "Ingénierie de prompt",
  "Public-key_cryptography": "Cryptographie asymétrique",
  "Pueblo_Bonito": "Pueblo Bonito",
  "Pulmonary_alveolus": "Alvéole pulmonaire",
  "Pythagorean_theorem": "Théorème de Pythagore",
  "QR_code": "Code QR",
  "QWERTY": "QWERTY",
  "Quechuan_languages": "Quechua",
  "Queen_Victoria": "Victoria (reine)",
  "Quipu": "Quipu",
  "RGB_color_model": "Rouge-vert-bleu",
  "RSA_cryptosystem": "Chiffrement RSA",
  "Radia_Perlman": "Radia Perlman",
  "Rafflesia_arnoldii": "Rafflesia arnoldii",
  "Raga": "Râga (musique)",
  "Rainbow": "Arc-en-ciel",
  "Rashomon": "Rashōmon (film, 1950)",
  "Rattanakosin_Kingdom": "Royaume de Rattanakosin",
  "Ray_Tomlinson": "Ray Tomlinson",
  "Rayleigh_scattering": "Diffusion Rayleigh",
  "Rebetiko": "Rébétiko",
  "Red_blood_cell": "Érythrocyte",
  "Reed–Solomon_error_correction": "Code de Reed-Solomon",
  "Registan": "Régistan (Samarcande)",
  "Renaissance": "Renaissance",
  "Retina": "Rétine",
  "Rhind_Mathematical_Papyrus": "Papyrus Rhind",
  "Rideau_Canal": "Canal Rideau",
  "Ring_of_Fire": "Ceinture de feu du Pacifique",
  "Rock-Hewn_Churches,_Lalibela": "Églises rupestres de Lalibela",
  "Roman_Republic": "République romaine",
  "Roman_roads": "Voie romaine",
  "Root": "Racine (botanique)",
  "Rosetta_Stone": "Pierre de Rosette",
  "Router_(computing)": "Routeur",
  "Rust": "Rouille (oxyde)",
  "Rømer's_determination_of_the_speed_of_light": "Détermination de la vitesse de la lumière par Ole Rømer",
  "SOS": "SOS",
  "Sacsayhuamán": "Saqsaywaman",
  "Sahara": "Sahara",
  "Saltwater_crocodile": "Crocodile marin",
  "Samarkand": "Samarcande",
  "Samurai": "Samouraï",
  "Sardinia": "Sardaigne",
  "Saturn": "Saturne (planète)",
  "Sciatic_nerve": "Nerf ischiatique",
  "Scurvy": "Scorbut",
  "Seki_Takakazu": "Seki Kōwa",
  "Self-portraits_by_Rembrandt": "Autoportraits de Rembrandt",
  "Semicircular_canals": "Canaux semi-circulaires",
  "Sequoia_sempervirens": "Sequoia sempervirens",
  "Sequoyah": "Sequoyah",
  "Serfdom": "Servage",
  "Server_(computing)": "Serveur informatique",
  "Seven_Bridges_of_Königsberg": "Problème des sept ponts de Königsberg",
  "Seven_hills_of_Rome": "Sept collines de Rome",
  "Sexagesimal": "Système sexagésimal",
  "Shah-i-Zinda": "Chah-e-Zindeh",
  "Shaka": "Chaka (roi zoulou)",
  "Silicon": "Silicium",
  "Silk_Road": "Route de la soie",
  "Simit": "Simit",
  "Sinoatrial_node": "Nœud sinu-atrial",
  "Sistine_Chapel_ceiling": "Plafond de la chapelle Sixtine",
  "Small_intestine": "Intestin grêle",
  "Sodium_bicarbonate": "Bicarbonate de sodium",
  "Sodium_chloride": "Chlorure de sodium",
  "Sogdia": "Sogdiane",
  "Solar_cell": "Cellule photovoltaïque",
  "Solar_eclipse": "Éclipse solaire",
  "Solomon_R._Guggenheim_Museum": "Musée Solomon-R.-Guggenheim",
  "Som_tam": "Salade de papaye verte",
  "Songhai_Empire": "Empire songhaï",
  "Songkran": "Songkran",
  "Sonic_boom": "Bang supersonique",
  "Sonnet": "Sonnet",
  "Sophie_Wilson": "Sophie Wilson",
  "Sound": "Onde sonore",
  "Souvlaki": "Souvláki",
  "Speed_of_sound": "Vitesse du son",
  "Spleen": "Rate",
  "Srivijaya": "Sriwijaya",
  "Stapes": "Étrier (os)",
  "Steelpan": "Pan (instrument)",
  "Stephenson's_Rocket": "Fusée de Stephenson",
  "Stockholm_archipelago": "Archipel de Stockholm",
  "Strait_of_Gibraltar": "Détroit de Gibraltar",
  "Submarine_communications_cable": "Câble sous-marin",
  "Suez_Canal": "Canal de Suez",
  "Sultan_Ahmed_Mosque": "Mosquée bleue",
  "Sun": "Soleil",
  "Sundiata_Keita": "Soundiata Keïta",
  "Superb_lyrebird": "Ménure superbe",
  "Superconductivity": "Supraconductivité",
  "Suzani_(textile)": "Suzani",
  "Swahili_coast": "Zanguebar",
  "Sydney_Opera_House": "Opéra de Sydney",
  "Symphony_No._9_(Beethoven)": "Symphonie no 9 de Beethoven",
  "Tacos_al_pastor": "Al pastor",
  "Taghaza": "Teghazza",
  "Taj_Mahal": "Taj Mahal",
  "Tajine": "Tajine",
  "Tanjia": "Tangia",
  "Tardigrade": "Tardigrada",
  "Taíno": "Taïnos",
  "Teahouse": "Salon de thé",
  "Temple_of_the_Emerald_Buddha": "Wat Phra Kaeo (Bangkok)",
  "Templo_Mayor": "Templo Mayor",
  "Ten_percent_of_the_brain_myth": "Mythe de l'utilisation incomplète du cerveau",
  "Tenochtitlan": "Mexico-Tenochtitlan",
  "Teotihuacan": "Teotihuacan",
  "Terracotta_Army": "Armée de terre cuite",
  "The_Canon_of_Medicine": "Qanûn (Avicenne)",
  "The_Great_Wave_off_Kanagawa": "La Grande Vague de Kanagawa",
  "The_Nine_Chapters_on_the_Mathematical_Art": "Les Neuf Chapitres sur l'art mathématique",
  "The_Rite_of_Spring": "Le Sacre du printemps",
  "The_Scream": "Le Cri",
  "The_Starry_Night": "La Nuit étoilée (1889)",
  "The_Tale_of_Genji": "Le Dit du Genji",
  "The_Thinker": "Le Penseur",
  "Thermal_conduction": "Conduction thermique",
  "Things_Fall_Apart": "Tout s'effondre",
  "Thonburi_Kingdom": "Royaume de Thonburi",
  "Thoracic_diaphragm": "Diaphragme (organe)",
  "Three-toed_sloth": "Bradypus",
  "Three_Sisters_(agriculture)": "Trois sœurs (agriculture)",
  "Thymus": "Thymus (anatomie)",
  "Thyroid": "Glande thyroïde",
  "Tidal_locking": "Rotation synchrone",
  "Tifinagh": "Tifinagh",
  "Tiger": "Tigre",
  "Tim_Berners-Lee": "Tim Berners-Lee",
  "Timbuktu": "Tombouctou",
  "Timbuktu_Manuscripts": "Manuscrits de Tombouctou",
  "Time_in_France": "Heure en France",
  "Time_in_Russia": "Heure en Russie",
  "Timur": "Tamerlan",
  "Tokyo": "Tokyo",
  "Tom_yum": "Tom yum",
  "Tommy_Flowers": "Tommy Flowers",
  "Tooth_enamel": "Émail dentaire",
  "Tornado": "Tornade",
  "Training,_validation,_and_test_data_sets": "Jeux d'entrainement, de validation et de test",
  "Trans-Saharan_trade": "Commerce transsaharien",
  "Transformer_(deep_learning)": "Transformeur",
  "Trevi_Fountain": "Fontaine de Trevi",
  "Trojan_Room_coffee_pot": "Trojan Room coffee pot",
  "Turing_test": "Test de Turing",
  "Turkish_bath": "Hammam",
  "Turkish_delight": "Loukoum",
  "Turritopsis_dohrnii": "Turritopsis dohrnii",
  "Tutankhamun": "Toutânkhamon",
  "Tzistarakis_Mosque": "Mosquée Tzistarakis",
  "Uji": "Uji",
  "Ulugh_Beg": "Ulugh Beg",
  "Ulugh_Beg_Observatory": "Observatoire astronomique d'Ulugh Beg",
  "Umm_Kulthum": "Oum Kalthoum",
  "Units_of_information": "Unité de mesure en informatique",
  "University_of_Oxford": "Université d'Oxford",
  "University_of_al-Qarawiyyin": "Université Al Quaraouiyine",
  "Uzbek_cuisine": "Cuisine ouzbèke",
  "Vagus_nerve": "Nerf vague",
  "Vapor-compression_refrigeration": "Réfrigérateur à compression de vapeur",
  "Vatican_City": "Vatican",
  "Venus": "Vénus (planète)",
  "Vibe_coding": "Vibe coding",
  "Victoria_Falls": "Chutes Victoria",
  "View_from_the_Window_at_Le_Gras": "Point de vue du Gras",
  "Vint_Cerf": "Vint Cerf",
  "Violin": "Violon",
  "Voltaic_pile": "Pile voltaïque",
  "Voyager_1": "Voyager 1",
  "Wai_(gesture)": "Wai",
  "Walls_of_Benin": "Murs du Bénin",
  "Wang_Zhenyi_(astronomer)": "Wang Zhenyi",
  "Washington_Monument": "Washington Monument",
  "Wat_Pho": "Wat Pho",
  "Web_browser": "Navigateur web",
  "Web_crawler": "Robot d'indexation",
  "Wellington": "Wellington",
  "Welwitschia": "Welwitschia mirabilis",
  "White_blood_cell": "Leucocyte",
  "Wi-Fi": "Wi-Fi",
  "Wilhelm_Röntgen": "Wilhelm Röntgen",
  "William_Harvey": "William Harvey",
  "Wombat": "Wombat",
  "Women's_suffrage_in_New_Zealand": "Droit de vote des femmes en Nouvelle-Zélande",
  "World_Wide_Web": "World Wide Web",
  "Wreck_of_the_Titanic": "Épave du Titanic",
  "Wright_brothers": "Orville et Wilbur Wright",
  "Xochimilco": "Xochimilco",
  "Yaa_Asantewaa": "Yaa Asantewaa",
  "Yam_(route)": "Örtöö",
  "Yuan_dynasty": "Dynastie Yuan",
  "Zhang_Heng": "Zhang Heng",
  "Zheng_He": "Zheng He",
  "Zimbabwe_Bird": "Oiseau Zimbabwe",
  "Zu_Chongzhi": "Zu Chongzhi",
  "Zócalo": "Place de la Constitution (Mexico)",
};
