// © 2026 Qpio. All rights reserved. Not covered by the MIT LICENSE.
// Terms of use: /CONTENT-LICENCE.md · Machine use reserved: /ai.txt
//
// THE HOOKS — beat two of the loop (Charter VAL-13).
//
// Not facts. A fact closes the gap; a hook opens it. "The Bolivian Navy
// patrols Lake Titicaca" informs — "Why does a landlocked country have a
// navy?" pulls. A hook that answers itself has no reason to be tapped.
//
// en / fr are written separately, not translated: a French reader should feel
// the same pull, which sometimes needs a different angle.
//
// Every line here has been through tools/apply_hooks.js, which only lets a
// rewrite land once an adversarial checker has cleared it on all four counts:
// true, not a spoiler, actually pulls, idiomatic French. Hand-edit freely —
// but a hook that states a number or a superlative has to be checkable.

window.CURIO_HOOKS = {
  "ARPANET": { en: "Everyone knows it was built to survive a nuclear attack. The head of ARPA said otherwise.", fr: "Tout le monde sait qu'il devait survivre à une guerre nucléaire. Le patron de l'ARPA a démenti." },
  "Abdelkader_ibn_Muhieddine": { en: "There is a town in Iowa named after him. He never set foot in America.", fr: "Une petite ville de l'Iowa porte son nom. Il n'a jamais mis les pieds en Amérique." },
  "Aboriginal_Australians": { en: "Large stretches of the land their ancestors lived on are now under the sea.", fr: "De vastes portions du pays de leurs ancêtres se trouvent aujourd'hui sous la mer." },
  "Absolute_zero": { en: "Negative temperatures exist in the lab. They are hotter than every positive one.", fr: "Des températures négatives existent en laboratoire. Elles sont plus chaudes que les positives." },
  "Ada_Lovelace": { en: "Her mother steered her into mathematics partly to stop her turning out like her father.", fr: "Sa mère l'a orientée vers les maths en partie pour qu'elle ne ressemble pas à son père." },
  "African_bush_elephant": { en: "Two elephants can hold a conversation across open country, at a pitch you cannot hear.", fr: "Deux éléphants se parlent à des kilomètres, sur des fréquences que nous n'entendons pas." },
  "Al-Khwarizmi": { en: "One word at the heart of computing is his own name, mangled by Latin.", fr: "Un mot au cœur de l'informatique n'est que son nom, déformé par le latin." },
  "Alaska_Purchase": { en: "Russia sold Alaska because it expected to lose it in a war — to somebody else.", fr: "La Russie a vendu l'Alaska de peur de le perdre dans une guerre — face à un tout autre pays." },
  "Allotropes_of_carbon": { en: "One form of carbon is named after an architect, because it looks like his buildings.", fr: "Une forme du carbone porte le nom d'un architecte, tant elle ressemble à ses bâtiments." },
  "Amazon_River": { en: "In its entire length, not one bridge crosses the Amazon's main channel.", fr: "Sur toute sa longueur, aucun pont ne franchit le cours principal de l'Amazone." },
  "Amelia_Earhart": { en: "Between record flights, she was selling her own line of clothing in Macy's. Why?", fr: "Entre deux vols record, elle vendait sa propre ligne de vêtements chez Macy's. Pourquoi ?" },
  "Ancient_Olympic_Games": { en: "Only one event is recorded from the first thirteen Games. Everything else came later.", fr: "Une seule épreuve est attestée aux treize premiers Jeux. Tout le reste est venu après." },
  "Andes": { en: "The point on Earth farthest from its centre is not Everest. It is in the Andes.", fr: "Le point le plus éloigné du centre de la Terre n'est pas l'Everest. Il est dans les Andes." },
  "Angel_Falls": { en: "The Pemón have their own name for it. A visiting pilot's surname is the one that stuck.", fr: "Les Pemón ont leur propre nom pour elle. C'est celui d'un pilote étranger qui s'est imposé." },
  "Angkor_Wat": { en: "Most temples at Angkor face east. This one faces west, and scholars still argue why.", fr: "La plupart des temples d'Angkor regardent vers l'est. Celui-ci regarde l'ouest. Pourquoi ?" },
  "Antarctica": { en: "Long before the ice, Antarctica had forests. They are still there — as coal.", fr: "L'Antarctique fut longtemps couvert de forêts. Elles y sont toujours, sous forme de charbon." },
  "Apollo_11": { en: "A speech was written for the president in case the two men could not leave the Moon.", fr: "Un discours présidentiel était prêt au cas où les deux hommes ne pourraient pas repartir." },
  "Arctic_tern": { en: "It does not fly south in a straight line. The detour is deliberate.", fr: "Il ne descend pas vers le sud en ligne droite. Le détour est volontaire." },
  "Ashoka": { en: "An emperor won a war, then spent his reign apologising for it in stone.", fr: "Un empereur gagne une guerre, puis passe son règne à s'en excuser dans la pierre." },
  "Atacama_Desert": { en: "One of the driest places on Earth turns into a field of flowers. Where do they come from?", fr: "L'un des lieux les plus secs de la planète se couvre parfois de fleurs. D'où sortent-elles ?" },
  "Athenian_democracy": { en: "A large share of Athenian officials were never elected. They were chosen by lottery.", fr: "Une grande part des magistrats athéniens n'étaient pas élus. Ils étaient tirés au sort." },
  "Atomic_nucleus": { en: "Every proton in a nucleus repels every other. Something stronger holds them together.", fr: "Dans un noyau, chaque proton repousse les autres. Quelque chose de plus fort les retient." },
  "Augustus": { en: "He insisted the Republic had been restored and that he was merely its first citizen.", fr: "Il assurait que la République était rétablie et qu'il n'était que le premier des citoyens." },
  "Bat": { en: "A bat can weigh less than a mouse and still live past forty years.", fr: "Une chauve-souris peut peser moins qu'une souris et vivre plus de quarante ans." },
  "Battle_of_Adwa": { en: "One treaty clause said 'may' in Amharic and 'must' in the other version. A war followed.", fr: "Le traité n'avait pas le même sens en amharique et dans l'autre version. La guerre a suivi." },
  "Battle_of_Ain_Jalut": { en: "The army beaten here was a fraction of the invading force. The rest had already left.", fr: "L'armée battue ici n'était qu'un détachement. Le gros des troupes était déjà reparti." },
  "Benin_Bronzes": { en: "Europeans saw these castings and decided Africans could not have made them.", fr: "Devant ces bronzes, les Européens ont conclu que des Africains n'avaient pas pu les faire." },
  "Binary_number": { en: "Binary was written down in India over two thousand years ago. The subject was poetry.", fr: "Le binaire a été décrit en Inde il y a plus de deux mille ans, à propos de poésie." },
  "Black_Death": { en: "The survivors came out of it better paid. That was not a coincidence.", fr: "Les survivants en sont sortis mieux payés. Ce n'était pas un hasard." },
  "Blue_whale": { en: "A calf of this species puts on about ninety kilos a day. On milk alone.", fr: "Le petit de cette espèce prend quelque quatre-vingt-dix kilos par jour. Uniquement au lait." },
  "Boiling_point": { en: "Lower the pressure far enough and water will boil and freeze at the same moment.", fr: "Baissez assez la pression : l'eau se met à bouillir et à geler en même temps." },
  "Bolivian_Navy": { en: "Why does a country with no coastline still maintain a navy?", fr: "Pourquoi un pays sans littoral entretient-il encore une marine de guerre ?" },
  "Brahmagupta": { en: "The first person to write down rules for zero got one of them wrong.", fr: "Le premier à écrire les règles du zéro s'est trompé sur l'une d'elles." },
  "Brasília": { en: "A constitution reserved land for this capital in 1891. Nobody broke ground for 65 years.", fr: "Une constitution réserve le terrain de cette capitale en 1891. Les travaux attendront 65 ans." },
  "Bristlecone_pine": { en: "A tree cut down in 1964 turned out to be nearly 5,000 years old. Nobody knew beforehand.", fr: "Un arbre abattu en 1964 s'est révélé vieux de près de 5 000 ans. Personne ne s'en doutait." },
  "Byte": { en: "Why does a brand-new 1 TB drive show up on your computer as 931 GB?", fr: "Pourquoi un disque neuf de 1 To s'affiche-t-il en 931 Go sur votre ordinateur ?" },
  "Cahokia": { en: "A city of thousands emptied out by 1350. Nobody has settled on why.", fr: "Des milliers d'habitants, puis plus personne vers 1350. On ignore toujours pourquoi." },
  "Cairo": { en: "This capital may be named after a planet that happened to be rising.", fr: "Cette capitale doit peut-être son nom à une planète qui se levait ce jour-là." },
  "Can't_Buy_Me_Love": { en: "Why was this song recorded in a Paris studio and not the band's usual London one?", fr: "Pourquoi ce titre a-t-il été enregistré à Paris, et non dans le studio londonien habituel ?" },
  "Canada–United_States_border": { en: "A library here keeps its front door in one country and its books in the other.", fr: "Sur cette frontière, une bibliothèque a son entrée dans un pays et ses livres dans l'autre." },
  "Canberra": { en: "Architects across the British Empire boycotted the contest to design this capital. Why?", fr: "Les architectes britanniques ont boycotté le concours pour dessiner cette capitale. Pourquoi ?" },
  "Carthage": { en: "Legend says a queen took only the land one oxhide could cover — and got a hill.", fr: "Une peau de bœuf, disent les récits, suffit à une reine pour fonder une ville." },
  "Celesta": { en: "Tchaikovsky hid this instrument from rival composers until opening night. Then everyone heard it.", fr: "Tchaïkovski a caché cet instrument à ses rivaux jusqu'à la première. Puis on l'a entendu." },
  "Central_processing_unit": { en: "A chip hit 3 GHz in 2002. Clock speeds have crawled ever since. What stopped them?", fr: "Un processeur atteignait 3 GHz en 2002. Vingt ans plus tard, à peine le double. Pourquoi ?" },
  "Challenger_Deep": { en: "A weighted rope sounded this place in 1875 — and missed the true bottom by over 2 km.", fr: "Une corde lestée a sondé ce gouffre en 1875 : elle a manqué le vrai fond de plus de 2 km." },
  "Cheetah": { en: "This cat cannot roar. Hear it once and you will look up, expecting a bird.", fr: "Ce félin ne rugit pas. Entendez-le une fois : vous chercherez l'oiseau des yeux." },
  "Chinampa": { en: "The \"floating gardens\" never floated. So what has been holding them up?", fr: "Les « jardins flottants » n'ont jamais flotté. Qu'est-ce qui les tient en place ?" },
  "Chinguetti": { en: "A town the desert is burying still keeps manuscripts older than the printing press.", fr: "Une ville que le sable enterre conserve des manuscrits plus vieux que l'imprimerie." },
  "Chlorophyll": { en: "The yellow in an autumn leaf was already there all summer, hidden.", fr: "Le jaune des feuilles d'automne était déjà là tout l'été, simplement caché." },
  "Christopher_Columbus": { en: "Spain arrested him in 1500 and shipped him home a prisoner. What had he done out there?", fr: "En 1500, l'Espagne l'arrête aux Caraïbes et le renvoie prisonnier. Qu'avait-il fait là-bas ?" },
  "Chromosome": { en: "Science got this basic number about our own bodies wrong for thirty years.", fr: "Pendant trente ans, la science s'est trompée sur un chiffre de notre corps." },
  "Cleopatra": { en: "She lived closer in time to the Moon landing than to the building of the Great Pyramid.", fr: "Elle a vécu plus près du premier pas sur la Lune que de la construction des pyramides de Gizeh." },
  "Code_of_Hammurabi": { en: "How did a Babylonian king's law stone end up buried in what is now Iran?", fr: "Comment la stèle des lois d'un roi de Babylone a-t-elle fini enterrée en Iran ?" },
  "Common_ostrich": { en: "Ostriches never bury their heads in sand. Something they really do started the myth.", fr: "L'autruche ne se cache jamais la tête dans le sable. Un vrai comportement a lancé la légende." },
  "Computer_mouse": { en: "Why did the man who invented the mouse never receive a cent in royalties?", fr: "Pourquoi l'inventeur de la souris n'a-t-il jamais touché la moindre redevance ?" },
  "Cuneiform": { en: "One customer's furious complaint about bad copper survives, in clay, from 1750 BCE.", fr: "Un client furieux s'est plaint de son cuivre. Sa lettre d'argile date de 1750 av. J.-C." },
  "Cyrus_Cylinder": { en: "Some call it the world's first human rights charter. Most historians do not.", fr: "Beaucoup y voient la première charte des droits humains. Les historiens, beaucoup moins." },
  "DNA": { en: "Barely 2% of your DNA codes for proteins. Biologists still argue over the other 98%.", fr: "À peine 2 % de votre ADN code pour des protéines. Les biologistes débattent encore du reste." },
  "Danube": { en: "Why does part of this river vanish underground and come back up in the wrong sea?", fr: "Pourquoi une partie de ce fleuve s'enfonce-t-elle sous terre pour ressortir dans une autre mer ?" },
  "Dead_Sea": { en: "What did Egyptian embalmers want from this lake? Surely not the salt.", fr: "Que venaient chercher les embaumeurs égyptiens dans ce lac ? Sûrement pas le sel." },
  "Diamond": { en: "In 1772 a chemist burned a diamond with sunlight. Nothing was left but gas.", fr: "En 1772, un chimiste a brûlé un diamant au soleil. Il n'en est resté qu'un gaz." },
  "Diomede_Islands": { en: "One of these islands still has its Iñupiat village. The Soviet state emptied the other.", fr: "L'une de ces îles a toujours son village iñupiat. L'État soviétique a vidé l'autre." },
  "Dmitri_Mendeleev": { en: "Nine Nobel nominations, no prize. In 1906 the academy voted him down by one vote.", fr: "Neuf nominations au Nobel, aucun prix : en 1906, l'Académie l'a écarté à une voix près." },
  "Dresden_Codex": { en: "Almost every Maya book was burned. Three or four survived. This is one.", fr: "Presque tous les livres mayas ont brûlé. Trois ou quatre restent. Voici l'un d'eux." },
  "Dry_ice": { en: "Planes once dropped it into clouds to make rain. Something else does that job now.", fr: "Des avions en ont lâché dans les nuages pour faire pleuvoir. Aujourd'hui, on fait autrement." },
  "ENIAC": { en: "It was built to compute artillery tables. Its first real job was the hydrogen bomb.", fr: "Conçu pour calculer des tables de tir, il a d'abord servi à la bombe H." },
  "Earth's_rotation": { en: "Why do some minutes have 61 seconds in them?", fr: "Pourquoi certaines minutes durent-elles 61 secondes ?" },
  "Eiffel_Tower": { en: "A private apartment sits at the very top. Eiffel kept it for himself and hosted Edison.", fr: "Tout en haut se cache un appartement privé : celui d'Eiffel, où il recevait Edison." },
  "Electron": { en: "A father proved the electron is a particle. His son proved it is a wave. Both were right.", fr: "Le père : une particule. Le fils : une onde. Les deux avaient raison sur l'électron." },
  "Epic_of_Gilgamesh": { en: "The poem is still not finished. Software is hunting its missing lines in museum drawers.", fr: "Le poème est toujours incomplet. Des logiciels traquent ses vers perdus dans les musées." },
  "Fahrenheit": { en: "Zero on this scale was a bucket of ice and salt. 96 was meant to be body temperature.", fr: "Son zéro : un mélange de glace et de sel. Et 96 devait être la température du corps." },
  "Fall_of_Constantinople": { en: "The harbour was chained shut. So how did the sultan's fleet get in?", fr: "Le port était fermé par une chaîne. Comment la flotte du sultan est-elle entrée ?" },
  "Femur": { en: "Hand a forensic scientist this one bone and they can tell you your height.", fr: "Donnez cet os à un légiste : il vous dira quelle taille vous faisiez." },
  "Fibonacci_sequence": { en: "A sequence from a medieval rabbit puzzle keeps reappearing in pine cones.", fr: "Une suite née d'un problème de lapins réapparaît dans les pommes de pin." },
  "Flag_of_Canada": { en: "Settling this flag took six months of debate and a vote at 2 a.m.", fr: "Six mois de débats, puis un vote à deux heures du matin : voilà comment ce drapeau est né." },
  "Flag_of_Mexico": { en: "The oldest tellings of this legend have no snake in them at all. Where did it come from?", fr: "Les plus anciennes versions de la légende ne comportent aucun serpent. D'où sort-il ?" },
  "Flag_of_Nepal": { en: "Until 1962 the sun and the moon on this flag had human faces.", fr: "Jusqu'en 1962, le soleil et la lune de ce drapeau avaient un visage humain." },
  "Frida_Kahlo": { en: "Why did Kahlo insist she was born three years after she actually was?", fr: "Pourquoi Kahlo s'est-elle rajeunie de trois ans toute sa vie ?" },
  "Fundamental_interaction": { en: "One of nature's four forces gets stronger the further you pull it apart.", fr: "L'une des quatre forces fondamentales se renforce quand on l'étire. Laquelle ?" },
  "Geography_of_Saudi_Arabia": { en: "One aquifer under this desert holds more water than the entire Persian Gulf.", fr: "Une seule nappe sous ce désert contient plus d'eau que tout le golfe Persique." },
  "Ghana": { en: "A new country chose the name of an empire that never stood on its land.", fr: "Un pays neuf a pris le nom d'un empire qui n'a jamais occupé son territoire." },
  "Ghana_Empire": { en: "Every gold nugget belonged to the king by law. Everyone else could own only the dust.", fr: "Toute pépite d'or revenait au roi. Aux autres, la poussière d'or seulement." },
  "Gold": { en: "Almost all of Earth's gold sank into the core. So what are we digging up?", fr: "Presque tout l'or de la Terre a sombré dans le noyau. Alors, que déterre-t-on ?" },
  "Google_Chrome": { en: "Its main rivals now run on its engine. Even Microsoft gave up building its own.", fr: "Ses rivaux tournent désormais sur son moteur. Même Microsoft a renoncé au sien." },
  "Gravity_of_Earth": { en: "You weigh least on a mountain in Peru, and most on the Arctic Ocean.", fr: "C'est sur une montagne du Pérou que vous pesez le moins. Et le plus, sur l'océan Arctique." },
  "Great_Barrier_Reef": { en: "How do whole reefs, spread over kilometres, all spawn on the very same nights?", fr: "Comment des récifs entiers, étalés sur des kilomètres, pondent-ils tous les mêmes nuits ?" },
  "Great_Law_of_Peace": { en: "A constitution centuries older than the United States, and not written on paper.", fr: "Une constitution bien plus ancienne que les États-Unis, et pas écrite sur du papier." },
  "Great_Mosque_of_Djenné": { en: "This building would dissolve in the rain if the whole town didn't show up.", fr: "Ce bâtiment fondrait sous la pluie si toute la ville ne venait pas chaque année." },
  "Great_Pyramid_of_Giza": { en: "Its four sides find true north to within a tenth of a degree. Nobody had a compass.", fr: "Ses quatre faces visent le nord vrai à un dixième de degré près. Sans boussole." },
  "Great_Wall_of_China": { en: "The mortar holding the Ming walls together was mixed with something you could eat.", fr: "Le mortier des murailles Ming contient un ingrédient qui se mange. Lequel ?" },
  "Great_Zimbabwe": { en: "Rhodesia's government censored archaeologists who said Africans built this city.", fr: "Le régime rhodésien censurait les archéologues qui l'attribuaient à des Africains." },
  "Gunpowder": { en: "An early Taoist text warns alchemists never to mix these powders. Houses had burned down.", fr: "Un texte taoïste met en garde : ne mélangez jamais ces poudres. Des maisons y sont passées." },
  "HTTP": { en: "The web's own protocol gives the server no memory of you. Yet sites know you anyway.", fr: "Le web repose sur un protocole sans mémoire. Comment les sites vous reconnaissent-ils ?" },
  "Hangul": { en: "In 1504 a king turned against this alphabet: someone had criticised him in it.", fr: "En 1504, un roi s'en prend à cet alphabet : on l'y avait critiqué." },
  "Hannibal": { en: "As a child, at an altar, he was made to swear he would never be a friend of Rome.", fr: "Enfant, devant l'autel, on lui fit jurer de n'être jamais l'ami de Rome." },
  "Hanseatic_League": { en: "A club of merchant towns went to war with the King of Denmark. The towns won.", fr: "Une ligue de villes marchandes a fait la guerre au roi du Danemark. Et l'a gagnée." },
  "Heart": { en: "Nothing tells your heart to beat. It makes its own electricity.", fr: "Rien n'ordonne à votre cœur de battre : il fabrique lui-même son électricité." },
  "Herbivore": { en: "A cow does not digest grass. Something else living inside it does that work.", fr: "Une vache ne digère pas l'herbe. D'autres organismes, à l'intérieur, s'en chargent pour elle." },
  "Hexadecimal": { en: "Before 'hexadecimal', this system had another name. It was quietly dropped.", fr: "Avant « hexadécimal », ce système portait un autre nom. On l'a discrètement abandonné." },
  "Honey": { en: "A retreating Greek army ate the local honey. Nobody could stand up for days.", fr: "Une armée grecque en retraite mangea le miel du coin. Plus personne ne tenait debout." },
  "Honey_bee": { en: "A returning bee dances on the comb. The angle of her dance is a map.", fr: "Une butineuse rentre et danse sur le rayon. L'angle de sa danse est une carte." },
  "House_of_Wisdom": { en: "Some Greek works survive only because someone in Baghdad translated them. The originals are gone.", fr: "Certains textes grecs n'existent plus qu'en arabe : l'original a disparu, la traduction non." },
  "Human_skin": { en: "About a thousand species of bacteria live on your skin. Hardly any harm you.", fr: "Environ mille espèces de bactéries vivent sur votre peau. Presque aucune ne vous nuit." },
  "Human_tooth": { en: "Your body makes something harder than bone — and can never grow it back.", fr: "Votre corps fabrique une matière plus dure que l'os. Il ne saura jamais la refaire." },
  "Hundred_Years'_War": { en: "England lost in 1453. Its kings kept the title King of France for three more centuries.", fr: "L'Angleterre perd en 1453. Ses rois se diront rois de France trois siècles de plus." },
  "Hydrogen": { en: "In the whole periodic table, one atom alone has no neutron. Why that one?", fr: "Dans tout le tableau périodique, un seul atome ne contient aucun neutron. Pourquoi lui ?" },
  "Ibn_Battuta": { en: "He left home at twenty-one to make the pilgrimage. He was gone for twenty-four years.", fr: "Parti à vingt et un ans pour le pèlerinage, il ne rentre que vingt-quatre ans plus tard." },
  "Ice": { en: "Physicists still do not agree on why ice is slippery.", fr: "Pourquoi la glace glisse-t-elle ? Les physiciens n'ont toujours pas tranché." },
  "Inca_road_system": { en: "Its bridges were woven from grass, and had to be rebuilt every other year.", fr: "Ses ponts étaient tressés en herbe et devaient être refaits tous les deux ans." },
  "Inclined_plane": { en: "Two Greek mathematicians tried to explain why a ramp helps. Both got it wrong.", fr: "Pourquoi une rampe allège-t-elle l'effort ? Deux mathématiciens grecs s'y sont cassé les dents." },
  "Indian_Ocean": { en: "Sailors here waited for the wind to change direction. It always did, on schedule.", fr: "Ici, les marins attendaient que le vent change de sens. Il le faisait, ponctuellement." },
  "Industrial_Revolution": { en: "The cotton feeding the new mills was grown by enslaved people an ocean away.", fr: "Le coton des nouvelles filatures était cultivé par des esclaves, un océan plus loin." },
  "Influence_of_William_Shakespeare": { en: "Eighteen of his plays survive only because two fellow actors printed them after his death.", fr: "Sans deux comédiens, dix-huit de ses pièces auraient disparu avec lui." },
  "Insect": { en: "Insects have no lungs. That single fact caps how big any of them can get.", fr: "Les insectes n'ont pas de poumons. Cela suffit à plafonner leur taille." },
  "Iron": { en: "The biggest stars fuse their way up the periodic table — until they hit iron. Then they die.", fr: "Les grandes étoiles fusionnent les éléments jusqu'au fer. Ensuite, elles meurent." },
  "Istanbul": { en: "In everyday speech people rarely used this city's name. They just said 'the City'.", fr: "Au quotidien, on prononçait rarement son nom : on disait « la Ville », et tous comprenaient." },
  "James_Watt": { en: "He defined horsepower to sell steam engines — by timing a real horse at a mill wheel.", fr: "Il a défini le cheval-vapeur pour vendre ses machines, en chronométrant un vrai cheval." },
  "Justinian_I": { en: "Two monks brought the secret of silk to his court, hidden inside hollow canes.", fr: "Deux moines rapportèrent à sa cour le secret de la soie, caché dans des cannes creuses." },
  "Kairouan": { en: "Local tradition says seven visits to this mosque equal one pilgrimage to Mecca.", fr: "Sept visites à cette mosquée valent un pèlerinage à La Mecque, dit la tradition." },
  "Kangaroo": { en: "One mother produces two different milks at the same time, from different teats.", fr: "Une mère produit deux laits différents en même temps, par deux mamelles distinctes." },
  "L'Anse_aux_Meadows": { en: "We know the exact year the Norse cut this timber: 1021. Tree rings gave it away.", fr: "On connaît l'année exacte où les Vikings ont coupé ce bois : 1021. Les cernes l'ont dit." },
  "La_Paz": { en: "Why do the wealthy here live at the bottom of the city, not on the heights?", fr: "Pourquoi les riches vivent-ils ici en bas de la ville, et non sur les hauteurs ?" },
  "Lake_Baikal": { en: "Seals live in this lake. Nobody is sure how they got here from the sea.", fr: "Des phoques vivent dans ce lac. Personne ne sait comment ils y sont arrivés." },
  "Lake_Victoria": { en: "A predatory fish was introduced here to boost the catch. Around 200 native species are gone.", fr: "Un poisson prédateur, lâché ici pour doper la pêche : environ 200 espèces locales ont disparu." },
  "Landlocked_country": { en: "The world's most populous landlocked country had a coastline within living memory.", fr: "Le pays enclavé le plus peuplé du monde avait encore une côte à la fin du XXe siècle." },
  "Leptis_Magna": { en: "Part of this North African city now stands in an English royal park.", fr: "Une partie de cette cité africaine se dresse aujourd'hui dans un parc royal anglais." },
  "Lesotho": { en: "Why does South Africa pay this mountain kingdom to send its water downhill?", fr: "Pourquoi l'Afrique du Sud paie-t-elle ce royaume de montagne pour son eau ?" },
  "Light-year": { en: "Astronomers writing for each other rarely use light-years. They prefer a bigger unit.", fr: "Entre eux, les astronomes n'emploient guère l'année-lumière. Ils ont une unité plus grande." },
  "Lion": { en: "Lions are not only African. A wild population survives in one Indian state.", fr: "Le lion n'est pas qu'africain : une population sauvage subsiste dans un seul État indien." },
  "List_of_bones_of_the_human_skeleton": { en: "More than half of all your bones are in your hands and feet. Why so many?", fr: "Plus de la moitié de vos os se trouvent dans vos mains et vos pieds. Pourquoi ?" },
  "List_of_islands_by_area": { en: "The world's most populous island doesn't even make the top ten by size.", fr: "L'île la plus peuplée du monde n'est même pas dans les dix plus vastes." },
  "Machu_Picchu": { en: "Quechua families were already farming these terraces when its 'discoverer' arrived.", fr: "Des familles quechuas cultivaient déjà ces terrasses quand son « découvreur » est arrivé." },
  "Macintosh_128K": { en: "The design team signed the inside of the case, where no owner would ever look.", fr: "L'équipe a signé l'intérieur du boîtier, là où aucun acheteur ne regarderait jamais." },
  "Magna_Carta": { en: "Of its sixty-three clauses, three are still law in England. The rest are gone.", fr: "Sur ses soixante-trois articles, trois sont encore en vigueur. Lesquels ?" },
  "Majapahit": { en: "An empire named after a fruit — because the first settlers found it bitter.", fr: "Un empire qui doit son nom à un fruit : les premiers défricheurs l'ont trouvé amer." },
  "Mansa_Musa": { en: "He said his predecessor sailed west into the Atlantic with 2,000 ships and never returned.", fr: "Selon son récit, son prédécesseur partit vers l'ouest avec 2 000 navires. On ne l'a jamais revu." },
  "Marie_Curie": { en: "Her notebooks are still radioactive. You need protective clothing to read them.", fr: "Ses carnets sont toujours radioactifs : il faut une tenue de protection pour les consulter." },
  "Marrakesh": { en: "UNESCO protects a square in this city — not for its buildings, but for its storytellers.", fr: "L'UNESCO protège ici une place, non pour ses murs mais pour ses conteurs." },
  "Masinissa": { en: "He fought for Carthage first. Then his cavalry hit Hannibal's rear at Zama and ended it.", fr: "Il servit d'abord Carthage. Puis, à Zama, sa cavalerie prit Hannibal à revers et tout bascula." },
  "Mass–energy_equivalence": { en: "Heat a cup of coffee and it weighs more. Not by much, but genuinely more.", fr: "Chauffez une tasse de café : elle pèse plus lourd. À peine — mais vraiment." },
  "Maya_script": { en: "A Soviet linguist found the key, having never seen a Maya site. The West dismissed him.", fr: "Un linguiste soviétique en a trouvé la clé sans avoir vu de site maya. L'Occident l'a rejeté." },
  "Mayflower": { en: "Plymouth was not built on empty ground. The village already there had a name.", fr: "Plymouth ne fut pas bâtie sur une terre vide : le village d'avant avait un nom." },
  "Mercury_(planet)": { en: "Closest to the Sun, and still not the hottest planet. Why not?", fr: "La plus proche du Soleil, et pourtant pas la plus chaude. Pourquoi ?" },
  "Milky_Way": { en: "Nobody has ever photographed our galaxy from outside. So how do we know?", fr: "Personne n'a jamais photographié notre galaxie de l'extérieur. Comment la connaît-on ?" },
  "Mitochondrion": { en: "Part of every one of your cells was once something else entirely.", fr: "Une partie de chacune de vos cellules fut autrefois un être à part entière." },
  "Moai": { en: "How do you move a statue of many tonnes with no wheels or animals?", fr: "Comment déplacer une statue de plusieurs tonnes sans roue ni animal de trait ?" },
  "Mona_Lisa": { en: "The thief who walked out with it in 1911 had helped build its glass case.", fr: "En 1911, le grand public n'y prêtait guère attention. Puis elle a disparu du Louvre." },
  "Mount_Everest": { en: "The rock at the very top of the world holds fossils of sea creatures.", fr: "Comment des fossiles marins se retrouvent-ils au sommet du monde ?" },
  "Mount_Fuji": { en: "Women were barred from this mountain until 1872. One had climbed it in 1832.", fr: "Au-dessus de la 8e station, le sommet du Fuji fait partie du domaine d'un sanctuaire." },
  "Mount_Kilimanjaro": { en: "Tropical glaciers sit on this summit. Nearly 85% of the ice has gone since 1912.", fr: "Ce volcan n'est pas éteint : des fumerolles s'échappent encore de son cratère." },
  "Nairobi_National_Park": { en: "Why would a country set fire to twelve tons of its own ivory?", fr: "Le parc n'est clôturé que sur trois côtés. Le quatrième reste ouvert. Pourquoi ?" },
  "Netherlands": { en: "Its parliament, cabinet and supreme court all sit in a city that is not the capital.", fr: "Sa douzième province n'a été ni conquise ni achetée : elle a été fabriquée." },
  "Newton_(unit)": { en: "Your bathroom scale cannot measure kilograms. It measures something else and converts.", fr: "Votre pèse-personne est incapable de mesurer des kilos. Il mesure autre chose." },
  "Nile": { en: "Upper Egypt sits at the bottom of the map. The river decided which end is up.", fr: "Sur la carte, la Haute-Égypte est tout en bas. C'est le fleuve qui a tranché." },
  "Ninety-five_Theses": { en: "The most famous hammer blow in European history may never have happened.", fr: "Le coup de marteau le plus célèbre d'Europe n'a peut-être jamais été donné." },
  "Nitrogen_fixation": { en: "Nearly half the nitrogen in your body was made usable inside a factory.", fr: "Près de la moitié de l'azote de votre corps est passée par un procédé industriel." },
  "Nocturnality": { en: "Many early mammals only came out at night. What was hunting in the daylight?", fr: "Beaucoup de mammifères primitifs ne sortaient que la nuit. Qui chassait le jour ?" },
  "North_Pole": { en: "Earth has more than one North Pole, and one of them is drifting toward Siberia.", fr: "La Terre a plusieurs pôles Nord. L'un d'eux dérive vers la Sibérie." },
  "Nubian_pyramids": { en: "More than forty of these pyramids were demolished by one treasure hunter in the 1830s.", fr: "Plus de quarante de ces pyramides ont été détruites par un seul chasseur de trésors." },
  "Obelisk_of_Axum": { en: "The tallest stele here probably fell as it was raised. It has lain broken ever since.", fr: "Le ramener en Éthiopie a demandé trois vols et la réfection d'une piste d'atterrissage." },
  "Octopus": { en: "Two thirds of this animal's neurons are nowhere near its brain.", fr: "Les deux tiers de ses neurones ne sont pas dans sa tête. Où sont-ils donc ?" },
  "Odyssey": { en: "The hero of this epic is nowhere to be seen for its first four books.", fr: "Le héros n'apparaît qu'au chant V. Que raconte-t-on pendant les quatre premiers ?" },
  "Ohm": { en: "The law named after him got such a cold reception that he resigned his position.", fr: "Sa loi fut si froidement accueillie qu'il démissionna de son poste." },
  "Olympus_Mons": { en: "Stand on this volcano's summit and you would not notice you were on a mountain.", fr: "Au sommet de ce volcan, on ne s'apercevrait même pas qu'on est sur une montagne." },
  "One_Hundred_Years_of_Solitude": { en: "While he wrote it, his wife bought their food on credit and owed nine months' rent.", fr: "Pendant qu'il l'écrivait, sa femme achetait à crédit et devait neuf mois de loyer." },
  "One_Thousand_and_One_Nights": { en: "Her stories were not entertainment. Each unfinished one bought her another morning.", fr: "Chaque conte interrompu à l'aube lui offrait un jour de vie supplémentaire." },
  "PH": { en: "Nobody is sure what the 'p' in pH actually stands for. Chemists still argue.", fr: "Personne ne sait vraiment ce que signifie le « p » de pH. Le débat dure encore." },
  "Pacific_Ocean": { en: "There is a spot in this ocean where the nearest humans are sometimes in orbit.", fr: "Il existe ici un point où les humains les plus proches sont parfois en orbite." },
  "Panama_Canal": { en: "Head for the Pacific through this canal and you come out further east than you went in.", fr: "En traversant vers le Pacifique, on ressort plus à l'est qu'on n'est entré. Comment ?" },
  "Peace_of_Westphalia": { en: "Neither side would sit in the other's city, so the treaty was negotiated in two towns.", fr: "Chaque camp refusait d'aller chez l'autre : la paix a été négociée dans deux villes." },
  "Penicillin": { en: "The first man ever injected with it was recovering when the supply ran out. He died.", fr: "Le premier homme à en recevoir une injection guérissait. Puis le stock s'est épuisé." },
  "Persepolis": { en: "The fire that destroyed this palace may be the reason its archive survived.", fr: "L'incendie qui a détruit ce palais est peut-être ce qui a sauvé ses archives." },
  "Petra": { en: "The urn carved above the Treasury is scarred with bullet holes. It is solid rock.", fr: "L'urne sculptée au-dessus du Trésor est criblée de balles. Elle est en pierre massive." },
  "Phoenician_alphabet": { en: "The first letter of your alphabet began as a drawing of an ox's head.", fr: "« Alphabet » vient de deux mots phéniciens : le bœuf et la maison." },
  "Photosynthesis": { en: "A tree's wood did not come out of the soil. So where did it come from?", fr: "Le bois d'un arbre ne sort pas de la terre. D'où vient-il alors ?" },
  "Pi": { en: "In 1897 an American state legislature came close to voting pi into a different value.", fr: "Jetez des aiguilles sur un parquet, comptez celles qui croisent une rainure : vous obtenez π." },
  "Piano": { en: "More than 200 strings inside, and nowhere near that many notes. Where do the extras go?", fr: "Près de vingt tonnes de tension tirent sur le cadre d'un piano à queue. Et il tient." },
  "Pompeii": { en: "The famous 'bodies' of Pompeii are plaster, poured into the hollows the bodies left.", fr: "Les corps figés de Pompéi ne sont pas des corps : c'est du plâtre coulé dans un vide." },
  "Pretoria": { en: "This city sits inside a municipality that carries a different name. The argument isn't over.", fr: "Soixante-dix mille arbres violets font sa réputation. Aucun n'est originaire d'Afrique." },
  "Prime_number": { en: "Multiplying two big primes is easy. Undoing it is so hard that we hide secrets behind it.", fr: "3 et 5, 11 et 13 : ces couples de premiers s'arrêtent-ils un jour ? Personne ne l'a prouvé." },
  "Printing_press": { en: "Europe's press gets the credit. A book printed in Korea with metal type beat it by 78 years.", fr: "Le plus ancien livre imprimé en caractères métalliques est coréen, et date de 1377." },
  "Pueblo_Bonito": { en: "Chaco's great houses took 200,000 trees. No wheels, no draft animals. How did they arrive?", fr: "Deux cent mille arbres acheminés sans roue ni bête de trait. Comment fait-on ça ?" },
  "QWERTY": { en: "The story that this layout was built to slow typists down may not be true at all.", fr: "Et si ce clavier avait été dessiné pour les télégraphistes, et non pour les dactylos ?" },
  "Queen_Victoria": { en: "She proposed to Albert herself, five days after he arrived. Why was that her job?", fr: "Un homme a tenté de tirer sur elle. Son pistolet était chargé de papier et de tabac." },
  "Quipu": { en: "An empire kept its records on knotted string. Nobody can read all of it yet.", fr: "Un empire tenait ses archives sur des cordes nouées. Personne ne sait encore tout lire." },
  "Ray_Tomlinson": { en: "Email wasn't his job. He told a colleague: don't tell anyone we're working on this.", fr: "Le courrier électronique n'était pas sa mission. « N'en parle à personne », dit-il alors." },
  "Rayleigh_scattering": { en: "Violet light scatters even more than blue. So why isn't the sky violet?", fr: "Le violet est encore plus diffusé que le bleu. Pourquoi le ciel n'est-il pas violet ?" },
  "Renaissance": { en: "Greek manuscripts reached Renaissance Italy in the luggage of refugees. Fleeing what?", fr: "Des livres grecs sont arrivés en Italie dans les bagages de réfugiés. Ils fuyaient quoi ?" },
  "Rideau_Canal": { en: "This canal was dug so British boats could dodge American guns. That war never came.", fr: "Jusqu'à mille ouvriers y sont morts, surtout du paludisme. Au Canada." },
  "Rock-Hewn_Churches,_Lalibela": { en: "The stream running past these churches is called the Jordan. Someone chose that name.", fr: "Le ruisseau qui coule entre ces églises s'appelle le Jourdain. Ce n'est pas un hasard." },
  "Roman_roads": { en: "Roman engineers would rather cut a road through a hill than curve around it. Why?", fr: "Le courrier impérial couvrait 80 km par jour sur ces routes. Sans moteur, comment ?" },
  "Root": { en: "Most plants don't hunt for water alone. They hire a fungus and pay it in sugar.", fr: "Dans la mangrove, des racines poussent vers le haut, hors de l'eau. Elles respirent." },
  "Rosetta_Stone": { en: "Everyone knows what this stone did. Almost nobody knows what it says.", fr: "On sait ce que cette pierre a permis. Pas ce qu'elle raconte." },
  "Rust": { en: "Rust takes up more room than the iron it replaced. That is how it prises bridges apart.", fr: "À Delhi, un pilier de fer de 1 600 ans résiste encore à la rouille. Pourquoi ?" },
  "SOS": { en: "It isn't three letters. It's one unbroken signal that only looks like S, O and S.", fr: "En 1999, il a cessé d'être le signal de détresse officiel. Par quoi l'a-t-on remplacé ?" },
  "Sahara": { en: "More than 30,000 rock carvings in the Sahara show river animals — crocodiles among them.", fr: "Plus de 30 000 gravures rupestres du Sahara montrent des animaux de rivière. Des crocodiles." },
  "Saltwater_crocodile": { en: "Nothing alive bites harder. Yet a few layers of duct tape hold those jaws shut.", fr: "590 km en 25 jours, presque sans nager. Ce crocodile a une méthode." },
  "Samurai": { en: "The famous samurai code was largely written down after the samurai stopped fighting.", fr: "Le fameux code des samouraïs a surtout été écrit une fois les guerres finies." },
  "Sardinia": { en: "Nearly 7,000 stone towers still stand on this island. No one agrees what they were for.", fr: "Près de 7 000 tours de pierre se dressent sur cette île. Personne ne sait à quoi elles servaient." },
  "Saturn": { en: "A hexagon sits on Saturn's north pole, each side longer than Earth is wide. Why?", fr: "Cette planète est moins dense que l'eau. Assez pour flotter, si la baignoire existait." },
  "Scurvy": { en: "The cure was proved in a shipboard trial in 1747. The navy acted on it in 1795.", fr: "Au XVIIIe siècle, il tuait plus de marins britanniques que les canons ennemis." },
  "Self-portraits_by_Rembrandt": { en: "Some paintings long known as his self-portraits turned out to be his students' work.", fr: "Rembrandt s'est peint à tous les âges. Certains de ces visages ne sont pas de sa main." },
  "Sequoia_sempervirens": { en: "The tallest living thing on Earth has a name, and an address kept secret.", fr: "Le plus haut être vivant de la Terre a un nom — et une adresse tenue secrète." },
  "Sequoyah": { en: "He could not read a single language when he invented a way to write one.", fr: "Il ne savait lire aucune langue quand il inventa le moyen d'en écrire une." },
  "Serfdom": { en: "Reach a chartered town and dodge capture for a year and a day, and you were free.", fr: "Gagner une ville franche, échapper aux recherches un an et un jour : et l'on était libre." },
  "Sexagesimal": { en: "Why is a second called a 'second'? Something else was cut first.", fr: "Pourquoi une « seconde » porte-t-elle ce nom ? Qu'a-t-on divisé en premier ?" },
  "Silicon": { en: "Chipmakers purify silicon almost perfectly, then deliberately dirty it again. Why?", fr: "On purifie le silicium à l'extrême, puis on le salit exprès. Pourquoi ?" },
  "Silk_Road": { en: "Nobody who travelled this road ever called it the Silk Road. The name dates to 1877.", fr: "Aucun voyageur de cette route ne l'a appelée « route de la soie » : le nom date de 1877." },
  "Sistine_Chapel_ceiling": { en: "He wrote a poem about how much this job hurt, and sketched himself buckled under it.", fr: "Il a écrit un poème sur la douleur de ce travail, et s'est dessiné tordu sous le plafond." },
  "Sodium_bicarbonate": { en: "The same powder that lifts a cake is injected into patients in hospitals. Why?", fr: "La poudre qui fait lever un gâteau s'injecte aussi à l'hôpital. Pourquoi ?" },
  "Sodium_chloride": { en: "One half of table salt explodes in water. The other was a First World War gas.", fr: "Un des éléments du sel explose dans l'eau ; l'autre servit de gaz de combat en 1915." },
  "Solomon_R._Guggenheim_Museum": { en: "Twenty-one artists signed a letter against this museum before it opened. Why?", fr: "Vingt et un artistes ont signé une lettre contre ce musée avant son ouverture. Pourquoi ?" },
  "Songhai_Empire": { en: "It sent a thousand cattle to break the enemy line. They came back the other way.", fr: "Mille bêtes lancées contre la ligne ennemie : le troupeau a fait demi-tour." },
  "Sound": { en: "Why does your recorded voice sound wrong to you and normal to everyone else?", fr: "Pourquoi ne reconnaissez-vous pas votre voix enregistrée, alors que tout le monde la reconnaît ?" },
  "Speed_of_sound": { en: "The crack of a whip is not leather hitting anything. So what is it?", fr: "Le claquement d'un fouet n'est pas le cuir qui frappe. Alors, d'où vient-il ?" },
  "Srivijaya": { en: "This empire ruled the sea lanes for centuries, then vanished from history until 1918.", fr: "Cet empire régna des siècles sur les mers, puis disparut de l'histoire jusqu'en 1918." },
  "Stephenson's_Rocket": { en: "Ten machines entered the contest of 1829. Only one of them finished.", fr: "Dix machines inscrites à l'épreuve de 1829. Une seule est allée au bout." },
  "Stockholm_archipelago": { en: "New land keeps rising out of the sea here. There is no volcano anywhere near.", fr: "Ici, de nouvelles terres sortent de la mer, et aucun volcan dans les parages." },
  "Strait_of_Gibraltar": { en: "Close this strait and the Mediterranean would dry up. It has happened before.", fr: "Fermez ce détroit et la Méditerranée s'assèche. C'est déjà arrivé." },
  "Suez_Canal": { en: "Fifteen ships sat stuck here for eight years. Their crews staged their own Olympics.", fr: "Quinze navires bloqués ici pendant huit ans. Les équipages ont organisé leurs Jeux olympiques." },
  "Sun": { en: "The Sun's outer atmosphere is far hotter than its surface. Nobody knows why.", fr: "L'atmosphère externe du Soleil est bien plus chaude que sa surface. Personne ne sait pourquoi." },
  "Sunlight": { en: "Sit in a sunny window all day and your skin still makes no vitamin D. Why?", fr: "Une journée entière derrière une vitre ensoleillée : zéro vitamine D. Pourquoi ?" },
  "Swahili_coast": { en: "How did a coastal traders' language become a working language of the African Union?", fr: "Comment la langue de ces marchands est-elle devenue langue de travail de l'Union africaine ?" },
  "Sydney_Opera_House": { en: "For four years nobody could build this roof. The answer was hiding in a single sphere.", fr: "Pendant quatre ans, personne ne savait bâtir ce toit. La solution : une seule sphère." },
  "Symphony_No._9_(Beethoven)": { en: "The composer of this symphony never heard it. He was in the room.", fr: "Le compositeur de cette symphonie ne l'a jamais entendue. Il était pourtant dans la salle." },
  "Taghaza": { en: "Two empires spent fifty years fighting over a village with no trees and no food.", fr: "Deux empires se sont battus cinquante ans pour un village sans arbres ni nourriture." },
  "Taíno": { en: "History books called them extinct. Six in ten Puerto Ricans carry their DNA today.", fr: "Les livres les disaient éteints. Six Portoricains sur dix portent encore leur ADN." },
  "Terracotta_Army": { en: "Eight thousand soldiers guard a tomb nobody has opened in fifty years of digging.", fr: "Huit mille soldats gardent un tombeau toujours pas ouvert, cinquante ans après." },
  "The_Canon_of_Medicine": { en: "A thousand years ago, this book already listed seven rules for testing a drug.", fr: "Il y a mille ans, ce livre énonçait déjà sept règles pour tester un médicament." },
  "The_Great_Wave_off_Kanagawa": { en: "The blue this print is famous for was a chemical newly shipped in from Europe.", fr: "Le bleu qui a rendu cette estampe célèbre était un pigment chimique importé d'Europe." },
  "The_Scream": { en: "A pencil note on this painting calls the painter a madman. The handwriting is his.", fr: "Une note au crayon sur ce tableau traite le peintre de fou. L'écriture est la sienne." },
  "The_Starry_Night": { en: "The painter called this canvas a failure in a letter to a friend.", fr: "Le peintre a qualifié cette toile d'échec dans une lettre à un ami." },
  "The_Tale_of_Genji": { en: "A thousand years on, nobody knows the real name of the woman who wrote it.", fr: "De l'autrice, il ne reste qu'un surnom de cour : son vrai nom est perdu." },
  "Things_Fall_Apart": { en: "His handwritten manuscript sat forgotten under dust in a London typing office for months.", fr: "Il est devenu écrivain après un roman anglais qui montrait les Nigérians en bouffons." },
  "Three_Sisters_(agriculture)": { en: "Some nations plant a fourth sister beside the three. What is she there for?", fr: "Une quatrième sœur existe : le tournesol, planté à la bordure nord du jardin. Pourquoi là ?" },
  "Tideway": { en: "Twice a day the current in London's river stops, turns round and runs inland.", fr: "Au cœur de Londres, le fleuve peut monter et descendre de sept mètres. Deux fois par jour." },
  "Tifinagh": { en: "Its oldest inscriptions usually run upwards — from the bottom of the line to the top.", fr: "Ses plus vieilles inscriptions se lisent souvent vers le haut. Pourquoi écrire en montant ?" },
  "Tiger": { en: "Most cats avoid deep water. This one crosses rivers eight kilometres wide.", fr: "Deux taches blanches derrière les oreilles. Il s'en sert pour parler." },
  "Timbuktu": { en: "In 2016 the court at The Hague jailed a man for destroying buildings here. A first.", fr: "En 2016, La Haye a condamné un homme pour avoir détruit des bâtiments ici. Une première." },
  "Time_in_France": { en: "France ran on Greenwich time until the war. It has never gone back.", fr: "Un des fuseaux horaires français ne compte pas un seul habitant. Lequel ?" },
  "Time_in_Russia": { en: "Until 2018 a train leaving Vladivostok departed on Moscow's clock, seven hours away.", fr: "En 2010, la Russie a supprimé deux fuseaux horaires. Elle les a rétablis quatre ans plus tard." },
  "Tokyo": { en: "Tokyo stopped being a city in 1943. It has been something else ever since.", fr: "Tokyo administre une île perdue à 1 850 km dans le Pacifique. Comment est-ce possible ?" },
  "Tooth_enamel": { en: "If enamel is see-through, where does the colour of your teeth come from?", fr: "Pourquoi le corps détruit-il les cellules qui fabriquent l'émail avant même que la dent perce ?" },
  "Tornado": { en: "Which country records the most tornadoes for its size? Not the United States.", fr: "L'échelle qui classe les tornades ne mesure pas le vent : elle mesure les dégâts." },
  "Turing_test": { en: "In Turing's first version of the game there is no machine: you must tell a man from a woman.", fr: "Turing avait fixé une échéance : l'an 2000. Et un seuil : tromper le juge trois fois sur dix." },
  "Tutankhamun": { en: "The best-known pharaoh in the world was erased from Egypt's own king lists.", fr: "Le pharaon le plus connu au monde avait été effacé des listes royales égyptiennes." },
  "Ulugh_Beg": { en: "He ruled Samarkand and mapped 994 stars without a telescope. His own son had him killed.", fr: "Un sextant de 40 mètres, en partie creusé dans le sol. Pourquoi enterrer un instrument ?" },
  "Units_of_information": { en: "Why does a brand-new one-terabyte drive show up as only 931 gigabytes?", fr: "Il existe une unité officielle, le kibioctet, que presque personne n'utilise. Pourquoi ?" },
  "University_of_al-Qarawiyyin": { en: "Why does Morocco's oldest university carry the name of a city in Tunisia?", fr: "En 1396, Ibn Khaldoun a offert son propre manuscrit à sa bibliothèque. Que garde-t-elle encore ?" },
  "Vatican_City": { en: "A whole country fits inside one city, and still found room for a railway.", fr: "Un pays entier tient dans une seule ville, et il y a pourtant une gare." },
  "Victoria_Falls": { en: "For part of the year, swimmers sit in a rock pool right on the lip of the drop.", fr: "Certaines nuits de pleine lune, un arc-en-ciel se forme ici. Sans le moindre soleil." },
  "Violin": { en: "Without pine resin rubbed on the hair, a bow slides over the string and barely sounds.", fr: "Pendant des siècles, les cordes du violon ne sortaient pas d'un atelier mais d'un abattoir." },
  "Washington_Monument": { en: "Why does the Washington Monument change colour 150 feet up?", fr: "En 1854, une pierre offerte par le pape a été détruite ici, en pleine nuit. Par qui ?" },
  "Wellington": { en: "Why did New Zealand let commissioners from Australia choose the site of its capital?", fr: "Une partie du centre-ville repose sur un fond de port qu'un séisme a soulevé en 1855." },
  "White_blood_cell": { en: "Some of them fight by bursting open and throwing their own DNA over the invader.", fr: "Le pus n'est pas de la saleté. Ce sont vos propres cellules, tombées au combat." },
  "Women's_suffrage_in_New_Zealand": { en: "The first country where women could vote still would not let them stand.", fr: "Premier pays où les femmes ont voté. Pas le premier où elles pouvaient être élues." },
  "Wreck_of_the_Titanic": { en: "The navy funded the robot that found the wreck. First it had to map two nuclear submarines.", fr: "L'épave est rongée par une bactérie qui porte le nom du navire. Combien de temps lui reste-t-il ?" },
  "Wright_brothers": { en: "The first powered aeroplane was paid for, and built, by a bicycle shop.", fr: "Le premier avion motorisé a été payé et construit par un magasin de vélos." },
  "Yam_(route)": { en: "The empire is long gone. Russian still calls a coachman by the word it left behind.", fr: "Le mot russe qui désigne le cocher vient d'un empire disparu depuis six siècles." },
  "Yuan_dynasty": { en: "This dynasty's astronomers fixed the year at 365.2425 days. Europe got there 300 years later.", fr: "Un empereur de cette dynastie a supprimé les pièces : on ne payait plus qu'en papier." },
  "Zheng_He": { en: "There is a tomb for him in Nanjing. There is no body in it.", fr: "Le chef des flottes impériales chinoises était un eunuque musulman, capturé enfant." }
};
