// © 2026 Qpio. All rights reserved. Not covered by the MIT LICENSE.
// Terms of use: /CONTENT-LICENCE.md · Machine use reserved: /ai.txt
//
// THE HOOKS — beat two of the loop (Charter VAL-13).
//
// Not facts. A fact closes the gap; a hook opens it. "The Bolivian Navy
// patrols Lake Titicaca" informs — "Why does a landlocked country have a
// navy?" pulls. A hook that answers itself has no reason to be tapped.
//
// en / fr are written separately, not translated: a French reader should feel
// the same pull, which sometimes needs a different angle.

window.CURIO_HOOKS = {
  "ARPANET": { en: "The internet's first message was cut short, and the fragment became the message.", fr: "Le premier message d'internet fut coupé net ; ce fragment est resté dans l'histoire." },
  "Abdelkader_ibn_Muhieddine": { en: "He fought France for sixteen years. Then France gave him a medal. Why?", fr: "Il a combattu la France seize ans. La France l'a ensuite décoré. Pourquoi ?" },
  "Aboriginal_Australians": { en: "How many separate languages fit on one continent lived in for 50,000 years?", fr: "Combien de langues distinctes tiennent sur un continent habité depuis 50 000 ans ?" },
  "Absolute_zero": { en: "Physics allows a lowest possible temperature, and forbids anyone from reaching it.", fr: "La physique fixe une température minimale, puis interdit à quiconque de l'atteindre." },
  "Ada_Lovelace": { en: "The first program was written for a computer that was never built.", fr: "Le premier programme fut écrit pour une machine qui n'a jamais existé." },
  "African_bush_elephant": { en: "A trunk contains no bone at all. Count its muscles against your entire body.", fr: "Une trompe ne contient aucun os. Comparez ses muscles à ceux de votre corps entier." },
  "Al-Khwarizmi": { en: "One Baghdad scholar's name and one of his book titles both became English words.", fr: "Son nom a donné un mot français ; le titre de son livre, un autre." },
  "Alaska_Purchase": { en: "In 1867 someone sold Alaska. The buyer's own newspapers called it an act of folly.", fr: "En 1867, un empire a vendu l'Alaska. La presse de l'acheteur a crié à la folie." },
  "Allotropes_of_carbon": { en: "How can one element be the hardest mineral there is and one of the softest?", fr: "Comment un même élément peut-il être le minéral le plus dur et l'un des plus tendres ?" },
  "Amazon_River": { en: "Add the next seven rivers on Earth together. This one still carries more water.", fr: "Additionnez les sept fleuves suivants du monde : celui-ci charrie encore plus d'eau." },
  "Amelia_Earhart": { en: "She set out for Paris. A failing aircraft decided otherwise.", fr: "Elle visait Paris. Un avion en perdition en a décidé autrement." },
  "Ancient_Olympic_Games": { en: "What could persuade warring Greek cities to stop fighting, on schedule, every four years?", fr: "Qu'est-ce qui pouvait suspendre les guerres grecques, à date fixe, tous les quatre ans ?" },
  "Andes": { en: "The Himalayas win on height. Measure the other direction and they are not close.", fr: "L'Himalaya gagne en hauteur. Mesurez dans l'autre sens : il n'est plus dans la course." },
  "Angel_Falls": { en: "The world's tallest waterfall is named after a pilot who got stuck on top of it.", fr: "La plus haute chute du monde porte le nom d'un pilote resté coincé à son sommet." },
  "Angkor_Wat": { en: "The largest religious monument on Earth started out worshipping a different god.", fr: "Le plus grand monument religieux du monde a commencé par honorer un tout autre dieu." },
  "Antarctica": { en: "There is a place here where rain has not fallen since before our species existed.", fr: "Ici, un lieu n'a pas vu la pluie depuis bien avant l'apparition de notre espèce." },
  "Apollo_11": { en: "The footprints they left up there will outlast every monument on Earth.", fr: "Les empreintes laissées là-haut survivront à tous les monuments de la Terre." },
  "Arctic_tern": { en: "One bird has arranged its life so that winter never happens to it.", fr: "Un oiseau a organisé sa vie pour que l'hiver ne lui arrive jamais." },
  "Ashoka": { en: "An emperor won a war, then spent his reign apologising for it in stone.", fr: "Un empereur gagne une guerre, puis passe son règne à s'en excuser dans la pierre." },
  "Atacama_Desert": { en: "NASA sends Mars equipment to this place on Earth. The soil is the reason.", fr: "La NASA teste ici du matériel destiné à Mars. Le sol en est la raison." },
  "Athenian_democracy": { en: "How democratic is a democracy where most of the people cannot vote?", fr: "Quelle démocratie est-ce, quand la plupart des habitants n'ont pas le droit de vote ?" },
  "Atomic_nucleus": { en: "Blow one atom up to the size of a stadium. How big is the nucleus?", fr: "Agrandissez un atome à la taille d'un stade. Quelle taille fait le noyau ?" },
  "Augustus": { en: "He was not born with the name history remembers. It was awarded to him.", fr: "Le nom que retient l'histoire n'est pas celui de sa naissance. On le lui a décerné." },
  "Bat": { en: "Pick a mammal species at random. There is a real chance it flies.", fr: "Prenez une espèce de mammifère au hasard. Il n'est pas rare qu'elle vole." },
  "Battle_of_Adwa": { en: "In 1896 the Scramble for Africa ran into an army that won.", fr: "En 1896, la ruée vers l'Afrique s'est heurtée à une armée qui a gagné." },
  "Battle_of_Ain_Jalut": { en: "In 1260 the Mongol advance stopped. The army that stopped it began as slaves.", fr: "En 1260, l'avancée mongole s'arrête. L'armée qui la stoppe était née de l'esclavage." },
  "Benin_Bronzes": { en: "Europeans saw these castings and decided Africans could not have made them.", fr: "Devant ces bronzes, les Européens ont conclu que des Africains n'avaient pas pu les faire." },
  "Binary_number": { en: "Every number, word and photograph you own is written with two symbols.", fr: "Chaque nombre, mot et photo que vous possédez s'écrit avec deux symboles." },
  "Black_Death": { en: "The survivors came out of it better paid. That was not a coincidence.", fr: "Les survivants en sont sortis mieux payés. Ce n'était pas un hasard." },
  "Blue_whale": { en: "A calf of this species puts on about ninety kilos a day. On milk alone.", fr: "Le petit de cette espèce prend quelque quatre-vingt-dix kilos par jour. Uniquement au lait." },
  "Boiling_point": { en: "Climb high enough and boiling water stops being hot enough to cook.", fr: "Assez haut en altitude, l'eau bout sans pouvoir cuire quoi que ce soit." },
  "Bolivian_Navy": { en: "Why does a country with no coastline still maintain a navy?", fr: "Pourquoi un pays sans littoral entretient-il encore une marine de guerre ?" },
  "Brahmagupta": { en: "The first person to write down rules for zero got one of them wrong.", fr: "Le premier à écrire les règles du zéro s'est trompé sur l'une d'elles." },
  "Brasília": { en: "Look at this city from above and it is not shaped like a city.", fr: "Vue du ciel, cette ville n'a pas la forme d'une ville." },
  "Bristlecone_pine": { en: "A tree alive today was already old when the pyramids were building sites.", fr: "Un arbre encore vivant était déjà vieux quand les pyramides étaient des chantiers." },
  "Byte": { en: "Its odd spelling was chosen so a single typo could not ruin it.", fr: "Son orthographe étrange fut choisie pour qu'une faute de frappe ne le trahisse pas." },
  "Cahokia": { en: "For a while the largest city north of Mexico stood in Illinois. Then it emptied.", fr: "La plus grande ville au nord du Mexique s'élevait en Illinois. Puis elle s'est vidée." },
  "Cairo": { en: "This capital may be named after a planet that happened to be rising.", fr: "Cette capitale doit peut-être son nom à une planète qui se levait ce jour-là." },
  "Can't_Buy_Me_Love": { en: "This song reached number one while the same band held the four places below it.", fr: "Ce titre fut numéro un, et le même groupe occupait les quatre places juste en dessous." },
  "Canada–United_States_border": { en: "The world's longest border is not just a line on a map. Loggers maintain it.", fr: "La plus longue frontière du monde est entretenue par des bûcherons. Pourquoi ?" },
  "Canberra": { en: "This capital exists because two other cities refused to let each other win.", fr: "Cette capitale n'existe que parce que deux autres villes refusaient de se céder." },
  "Carthage": { en: "Legend says a queen took only the land one oxhide could cover — and got a hill.", fr: "Une peau de bœuf, disent les récits, suffit à une reine pour fonder une ville." },
  "Celesta": { en: "Tchaikovsky hid this instrument from rival composers until opening night. Then everyone heard it.", fr: "Tchaïkovski a caché cet instrument à ses rivaux jusqu'à la première. Puis on l'a entendu." },
  "Central_processing_unit": { en: "It performs billions of operations a second while understanding only two things.", fr: "Des milliards d'opérations par seconde, et il ne comprend que deux choses." },
  "Challenger_Deep": { en: "Drop Everest into this place and its summit would still be underwater.", fr: "Jetez l'Everest ici : son sommet resterait encore sous l'eau." },
  "Cheetah": { en: "This animal out-accelerates most sports cars, and cannot keep it up for a minute.", fr: "Cet animal accélère plus vite qu'une sportive — et ne tient pas une minute." },
  "Chinampa": { en: "How do you feed a capital city built in the middle of a lake?", fr: "Comment nourrir une capitale bâtie au milieu d'un lac ?" },
  "Chinguetti": { en: "A town the desert is burying still keeps manuscripts older than the printing press.", fr: "Une ville que le sable enterre conserve des manuscrits plus vieux que l'imprimerie." },
  "Chlorophyll": { en: "The yellow in an autumn leaf was already there all summer, hidden.", fr: "Le jaune des feuilles d'automne était déjà là tout l'été, simplement caché." },
  "Christopher_Columbus": { en: "He crossed four times and died still insisting he had reached Asia.", fr: "Quatre traversées, et il est mort convaincu d'avoir atteint l'Asie." },
  "Chromosome": { en: "Science got this basic number about our own bodies wrong for thirty years.", fr: "Pendant trente ans, la science s'est trompée sur un chiffre de notre corps." },
  "Cleopatra": { en: "Egypt's most famous queen spoke a language her own dynasty never bothered to learn.", fr: "La reine la plus célèbre d'Égypte parlait une langue que sa dynastie n'avait jamais apprise." },
  "Code_of_Hammurabi": { en: "Why carve your laws on a two-metre stone where everyone could see them?", fr: "Pourquoi graver ses lois sur une stèle de deux mètres, à la vue de tous ?" },
  "Common_ostrich": { en: "Something inside this bird's head is bigger than its brain. You can see it.", fr: "Quelque chose, dans la tête de cet oiseau, dépasse son cerveau. Cela se voit." },
  "Computer_mouse": { en: "Sixty years on, we still call it by a nickname from its first lab.", fr: "Soixante ans après, on l'appelle encore par le surnom né dans son premier laboratoire." },
  "Cuneiform": { en: "The world's oldest tablets are not stories. They are not prayers either.", fr: "Les plus vieilles tablettes du monde ne racontent rien et ne prient personne." },
  "Cyrus_Cylinder": { en: "A clay barrel from 539 BCE sits, in replica, at the United Nations. Why?", fr: "Un cylindre d'argile de 539 av. J.-C. trône, en copie, à l'ONU. Pourquoi ?" },
  "DNA": { en: "How do you fold two metres of thread into one invisible cell?", fr: "Comment ranger deux mètres de fil dans une cellule invisible à l'œil ?" },
  "Danube": { en: "No other river on Earth passes through this many national capitals. Name them.", fr: "Aucun autre fleuve au monde ne traverse autant de capitales. Sauriez-vous les nommer ?" },
  "Dead_Sea": { en: "Swimmers here cannot sink, and nothing swims beside them. The two facts are one.", fr: "Ici, les nageurs ne coulent pas — et rien ne nage à côté d'eux. Même cause." },
  "Diamond": { en: "Every natural diamond reached the surface by volcano. Nothing else could lift one.", fr: "Chaque diamant naturel est remonté par un volcan. Rien d'autre ne pouvait le porter." },
  "Diomede_Islands": { en: "Two islands sit four kilometres apart. Nearly a whole day separates them.", fr: "Deux îles distantes de quatre kilomètres. Presque une journée entière les sépare." },
  "Dmitri_Mendeleev": { en: "He left holes in his table and described what would one day fill them.", fr: "Il a laissé des trous dans son tableau en décrivant ce qui les remplirait." },
  "Dresden_Codex": { en: "Almost every Maya book was burned. Three or four survived. This is one.", fr: "Presque tous les livres mayas ont brûlé. Trois ou quatre restent. Voici l'un d'eux." },
  "Dry_ice": { en: "It smokes for hours and leaves no puddle behind. Where does it go?", fr: "Elle fume pendant des heures et ne laisse aucune flaque. Où passe-t-elle ?" },
  "ENIAC": { en: "Everyone remembers the machine. Almost nobody remembers its six programmers.", fr: "On se souvient de la machine. Personne ne se souvient de qui la programmait." },
  "Earth's_rotation": { en: "The length of a day is not fixed. It has been quietly growing.", fr: "La durée d'un jour n'est pas fixe : elle s'allonge discrètement." },
  "Eiffel_Tower": { en: "This tower is never quite in the same place twice. Blame the weather.", fr: "Cette tour n'est jamais tout à fait au même endroit. La météo en décide." },
  "Electron": { en: "The lightest thing in an atom decides almost everything the atom does.", fr: "La particule la plus légère de l'atome décide presque tout son comportement." },
  "Epic_of_Gilgamesh": { en: "In 1872 a translator read one clay tablet aloud in London and caused a sensation.", fr: "En 1872, la lecture d'une seule tablette a bouleversé Londres. Que disait-elle ?" },
  "Fahrenheit": { en: "Two temperature scales disagree everywhere except at one exact number.", fr: "Deux échelles de température se contredisent partout, sauf à un seul degré." },
  "Fall_of_Constantinople": { en: "The Roman Empire did not end in Rome, or in the fifth century.", fr: "L'Empire romain ne s'est éteint ni à Rome, ni au Ve siècle." },
  "Femur": { en: "How much of your height is really just one single bone?", fr: "Quelle part de votre taille tient en réalité dans un seul os ?" },
  "Fibonacci_sequence": { en: "A sequence from a medieval rabbit puzzle keeps reappearing in pine cones.", fr: "Une suite née d'un problème de lapins réapparaît dans les pommes de pin." },
  "Flag_of_Canada": { en: "People keep decoding the eleven points on this leaf. There is nothing to decode.", fr: "On cherche encore un sens aux onze pointes de cette feuille. Il n'y en a pas." },
  "Flag_of_Mexico": { en: "The bird on this flag was not chosen for beauty. It marked a spot.", fr: "L'oiseau de ce drapeau n'a pas été choisi pour sa beauté : il marquait un lieu." },
  "Flag_of_Nepal": { en: "This is the one flag nobody can draw freehand. The constitution supplies the geometry.", fr: "Voici le seul drapeau qu'on ne peut dessiner à main levée. La constitution fournit la géométrie." },
  "Frida_Kahlo": { en: "She painted her own face again and again. A mirror above a bed explains why.", fr: "Elle a peint son visage encore et encore. Un miroir au-dessus d'un lit l'explique." },
  "Fundamental_interaction": { en: "One of nature's four forces is so feeble it embarrasses the others.", fr: "L'une des quatre forces de la nature est d'une faiblesse embarrassante." },
  "Geography_of_Saudi_Arabia": { en: "There is no river anywhere in this country. Its cities still drink every day.", fr: "Aucun fleuve ne coule nulle part dans ce pays. Ses villes boivent pourtant chaque jour." },
  "Ghana": { en: "A new country chose the name of an empire that never stood on its land.", fr: "Un pays neuf a pris le nom d'un empire qui n'a jamais occupé son territoire." },
  "Ghana_Empire": { en: "These kings never mined an ounce of gold. They taxed everyone who carried it.", fr: "Ces rois n'ont jamais extrait une once d'or : ils taxaient ceux qui en transportaient." },
  "Gold": { en: "How far can one gram of gold be stretched before it tears?", fr: "Jusqu'où peut-on étirer un seul gramme d'or avant qu'il ne cède ?" },
  "Gravity_of_Earth": { en: "Your weight changes depending on where you stand. The scale is not broken.", fr: "Votre poids change selon l'endroit où vous montez sur la balance. Elle n'est pas cassée." },
  "Great_Barrier_Reef": { en: "Every one of its builders is smaller than your fingernail. The result is visible from orbit.", fr: "Chacun de ses bâtisseurs est plus petit qu'un ongle. Le résultat se voit depuis l'orbite." },
  "Great_Law_of_Peace": { en: "A constitution centuries older than the United States, and not written on paper.", fr: "Une constitution bien plus ancienne que les États-Unis, et pas écrite sur du papier." },
  "Great_Mosque_of_Djenn%C3%A9": { en: "This building would dissolve in the rain if the whole town didn't show up.", fr: "Ce bâtiment fondrait sous la pluie si toute la ville ne venait pas chaque année." },
  "Great_Pyramid_of_Giza": { en: "How long did a single tomb hold the world's height record?", fr: "Combien de temps un seul tombeau a-t-il détenu le record de hauteur mondial ?" },
  "Great_Wall_of_China": { en: "Everyone repeats one thing about this wall. Astronauts disagree.", fr: "Tout le monde répète la même chose sur cette muraille. Les astronautes disent le contraire." },
  "Great_Zimbabwe": { en: "Millions of granite blocks, no mortar, and colonial officials who refused to believe it.", fr: "Des millions de blocs de granit, sans mortier — et des colons qui refusaient d'y croire." },
  "Gunpowder": { en: "What were Chinese alchemists actually trying to make when they invented gunpowder?", fr: "Que cherchaient réellement les alchimistes chinois lorsqu'ils ont inventé la poudre noire ?" },
  "HTTP": { en: "The web's core protocol and its first browser came from the same person.", fr: "Le protocole du web et le tout premier navigateur sortent de la même tête." },
  "Hangul": { en: "Korea's alphabet was designed. Its letters are drawings of your own mouth.", fr: "L'alphabet coréen a été conçu : ses lettres dessinent la forme de votre bouche." },
  "Hannibal": { en: "He camped in Italy for fifteen years and never took Rome. What stopped him?", fr: "Il campa quinze ans en Italie sans jamais prendre Rome. Qu'est-ce qui l'en a empêché ?" },
  "Hanseatic_League": { en: "Nearly two hundred towns ran a trading empire without ever becoming a country.", fr: "Près de deux cents villes ont bâti un empire commercial sans jamais former un État." },
  "Heart": { en: "How many times has your heart beaten since you started reading this sentence?", fr: "Combien de fois votre cœur a-t-il battu depuis le début de cette phrase ?" },
  "Herbivore": { en: "A cow does not digest grass. Something else living inside it does that work.", fr: "Une vache ne digère pas l'herbe. D'autres organismes, à l'intérieur, s'en chargent pour elle." },
  "Hexadecimal": { en: "Web colours are written with exactly six characters. That number is not arbitrary.", fr: "Les couleurs du web s'écrivent en six caractères. Ce nombre n'a rien d'arbitraire." },
  "Honey": { en: "Archaeologists opened a jar three thousand years old. The contents were still edible.", fr: "Des archéologues ont ouvert un pot vieux de trois mille ans. Le contenu se mangeait." },
  "Honey_bee": { en: "Count the spoonfuls in a jar of honey, then count the lifetimes behind them.", fr: "Comptez les cuillerées dans un pot de miel, puis les vies qu'elles ont coûtées." },
  "House_of_Wisdom": { en: "Some Greek works survive only because someone in Baghdad translated them. The originals are gone.", fr: "Certains textes grecs n'existent plus qu'en arabe : l'original a disparu, la traduction non." },
  "Human_skin": { en: "Your largest organ is the one you can see. How much of it is dead?", fr: "Votre plus grand organe est celui que vous voyez. Quelle part en est déjà morte ?" },
  "Human_tooth": { en: "Four of your teeth arrive years late, to a mouth with no space.", fr: "Quatre de vos dents arrivent avec des années de retard, sans place pour elles." },
  "Hundred_Years'_War": { en: "Its name gets the arithmetic wrong. It gets the word 'war' wrong too.", fr: "Son nom se trompe sur le compte des années, et sur le mot « guerre »." },
  "Hydrogen": { en: "Why did the universe make so much of this one element and so little else?", fr: "Pourquoi l'univers a-t-il fabriqué tant de cet élément et si peu de tout le reste ?" },
  "Ibn_Battuta": { en: "Everyone in Europe learns Marco Polo's name. Someone else travelled nearly five times further.", fr: "L'Europe retient Marco Polo. Un autre a parcouru près de cinq fois plus de chemin." },
  "Ice": { en: "Nearly every substance sinks into its own melt. Water breaks the rule.", fr: "Presque toute matière coule dans son propre liquide. L'eau refuse." },
  "Inca_road_system": { en: "Its bridges were woven from grass, and had to be rebuilt every other year.", fr: "Ses ponts étaient tressés en herbe et devaient être refaits tous les deux ans." },
  "Inclined_plane": { en: "A ramp lets you lift what you never could. Nothing is free.", fr: "Une rampe soulève ce que vos bras ne peuvent pas. Rien n'est gratuit." },
  "Indian_Ocean": { en: "Sailors here waited for the wind to change direction. It always did, on schedule.", fr: "Ici, les marins attendaient que le vent change de sens. Il le faisait, ponctuellement." },
  "Industrial_Revolution": { en: "The new machines needed small fingers. That decided who worked Britain's cotton mills.", fr: "Les nouvelles machines réclamaient de petits doigts. Cela a décidé qui travaillerait dans les filatures." },
  "Influence_of_William_Shakespeare": { en: "You used one of his inventions today, and it was not a play.", fr: "Vous avez utilisé l'une de ses inventions aujourd'hui, et ce n'était pas une pièce." },
  "Insect": { en: "Six legs, three parts. By that rule, the creature in your bath fails.", fr: "Six pattes, trois parties. À ce compte-là, la bête de votre baignoire n'en est pas." },
  "Iron": { en: "The metal in a nail is also what keeps this planet's shield switched on.", fr: "Le métal d'un simple clou est aussi ce qui protège la planète entière." },
  "Istanbul": { en: "This city was the capital of two vanished empires. It is the capital of nothing now.", fr: "Cette ville fut la capitale de deux empires disparus. Elle n'est plus capitale de rien." },
  "James_Watt": { en: "His name is on every light bulb. He did not invent the engine.", fr: "Son nom figure sur chaque ampoule. Il n'a pourtant pas inventé la machine à vapeur." },
  "Justinian_I": { en: "A riot at the racetrack burned down his capital. He rebuilt it bigger.", fr: "Une émeute née à l'hippodrome a incendié sa capitale. Il l'a rebâtie plus grande." },
  "Kairouan": { en: "Legend says a general pitched camp in a thicket. It became a city of scholars.", fr: "Un camp militaire planté dans un fourré, dit la légende. Il en naquit une ville savante." },
  "Kangaroo": { en: "A newborn of this animal is the size of a jellybean, and climbs unaided.", fr: "Le nouveau-né de cet animal a la taille d'un bonbon. Et il grimpe tout seul." },
  "L'Anse_aux_Meadows": { en: "Eight buildings on a Newfoundland shore moved a date back five hundred years.", fr: "Huit bâtiments sur une côte de Terre-Neuve ont reculé une date de cinq siècles." },
  "La_Paz": { en: "Visitors here need days before they can climb stairs without stopping. A government works anyway.", fr: "Ici, les visiteurs mettent des jours à monter un escalier sans s'arrêter. Un gouvernement y siège." },
  "Lake_Baikal": { en: "Drain every one of North America's Great Lakes. This single lake still wins.", fr: "Videz les cinq Grands Lacs d'Amérique du Nord. Ce lac unique l'emporte encore." },
  "Lake_Victoria": { en: "A river that ends in Egypt starts by leaving this lake through one narrow gap.", fr: "Un fleuve qui se jette en Égypte commence en quittant ce lac par une seule sortie." },
  "Landlocked_country": { en: "Some countries are landlocked twice over. Only two on Earth manage it.", fr: "Certains pays sont enclavés deux fois. Deux seulement y parviennent sur Terre." },
  "Leptis_Magna": { en: "Part of this North African city now stands in an English royal park.", fr: "Une partie de cette cité africaine se dresse aujourd'hui dans un parc royal anglais." },
  "Lesotho": { en: "No road out of this country goes anywhere but downhill, and into one neighbour.", fr: "Aucune route ne quitte ce pays autrement qu'en descendant — et vers un seul voisin." },
  "Light-year": { en: "Light laps the Earth seven times a second. Now try measuring a light-year.", fr: "La lumière fait sept fois le tour de la Terre en une seconde. Mesurez une année-lumière." },
  "Lion": { en: "Every other big cat lives alone. One species built a society around its sisters.", fr: "Tous les autres grands félins vivent seuls. Une espèce a bâti une société de sœurs." },
  "List_of_bones_of_the_human_skeleton": { en: "You had more bones as a baby. Where did the rest go?", fr: "Bébé, vous en aviez davantage. Où sont passés les autres ?" },
  "List_of_islands_by_area": { en: "An island bigger than Greenland exists. It simply is not allowed to be one.", fr: "Une île plus grande que le Groenland existe. On refuse de l'appeler île." },
  "Machu_Picchu": { en: "No mortar holds these walls together. So what does?", fr: "Aucun mortier ne tient ces murs. Alors qu'est-ce qui les tient ?" },
  "Macintosh_128K": { en: "The ideas that made this computer famous were invented by another company.", fr: "Les idées qui ont rendu cet ordinateur célèbre venaient d'une autre entreprise." },
  "Magna_Carta": { en: "England's most famous charter was cancelled by the Pope that very summer.", fr: "La charte anglaise la plus célèbre fut annulée par le pape le même été." },
  "Majapahit": { en: "A minister vowed no rest until the archipelago was one. Did he manage it?", fr: "Un ministre jura de ne pas se reposer avant d'unir l'archipel. Y est-il parvenu ?" },
  "Mansa_Musa": { en: "Why do the chroniclers blame one pilgrim for what happened to Cairo's gold?", fr: "Pourquoi les chroniqueurs rendent-ils un seul pèlerin responsable du cours de l'or au Caire ?" },
  "Marie_Curie": { en: "She holds a Nobel record that has stood unbroken for over a century.", fr: "Elle détient un record Nobel que personne n'a égalé depuis plus d'un siècle." },
  "Marrakesh": { en: "An empire run from this city reached from the Senegal River into central Spain.", fr: "Depuis cette ville, un empire s'étendait du fleuve Sénégal jusqu'au cœur de l'Espagne." },
  "Masinissa": { en: "At an age when most kings were long dead, he was still commanding cavalry.", fr: "À un âge où les rois sont morts depuis longtemps, il chargeait encore à cheval." },
  "Mass–energy_equivalence": { en: "Why does the world's most famous equation contain a squared speed?", fr: "Pourquoi l'équation la plus célèbre du monde contient-elle une vitesse au carré ?" },
  "Maya_script": { en: "Scholars could read Egyptian hieroglyphs for a century before they could read this.", fr: "On lisait les hiéroglyphes égyptiens depuis un siècle avant de savoir lire celle-ci." },
  "Mayflower": { en: "Plymouth was not built on empty ground. The village already there had a name.", fr: "Plymouth ne fut pas bâtie sur une terre vide : le village d'avant avait un nom." },
  "Mercury_(planet)": { en: "Closest to the Sun, and still not the hottest planet. Why not?", fr: "La plus proche du Soleil, et pourtant pas la plus chaude. Pourquoi ?" },
  "Milky_Way": { en: "Nobody has ever photographed our galaxy from outside. So how do we know?", fr: "Personne n'a jamais photographié notre galaxie de l'extérieur. Comment la connaît-on ?" },
  "Mitochondrion": { en: "Part of every one of your cells was once something else entirely.", fr: "Une partie de chacune de vos cellules fut autrefois un être à part entière." },
  "Moai": { en: "How do you move a statue of many tonnes with no wheels or animals?", fr: "Comment déplacer une statue de plusieurs tonnes sans roue ni animal de trait ?" },
  "Mona_Lisa": { en: "Look at the most famous face in art. Something ordinary is missing from it.", fr: "Regardez le visage le plus célèbre de l'art. Il lui manque quelque chose d'ordinaire." },
  "Mosaic_(web_browser)": { en: "Why did the web only become worth looking at in 1993?", fr: "Pourquoi le web n'est-il devenu regardable qu'à partir de 1993 ?" },
  "Mount_Everest": { en: "The height of this mountain in your school atlas is already out of date.", fr: "L'altitude imprimée dans votre atlas scolaire vieillit un peu plus chaque année." },
  "Mount_Fuji": { en: "Japan's most painted mountain is not sleeping. It is only between eruptions.", fr: "La montagne la plus peinte du Japon ne dort pas. Elle attend son tour." },
  "Mount_Kilimanjaro": { en: "No mountain range holds this peak up. It stands alone near the equator, wearing ice.", fr: "Aucune chaîne ne soutient ce sommet. Il se dresse seul près de l'équateur, coiffé de glace." },
  "Nairobi_National_Park": { en: "A wild lion, and skyscrapers behind it, in one photograph. No zoo is involved.", fr: "Un lion sauvage, des gratte-ciel derrière lui, sur la même photo. Aucun zoo là-dedans." },
  "Netherlands": { en: "A quarter of this country sits below sea level. Somebody had to make it.", fr: "Un quart de ce pays se trouve sous le niveau de la mer. Quelqu'un l'a fabriqué." },
  "Newton_(unit)": { en: "What does one single unit of force actually feel like in your hand?", fr: "À quoi ressemble une seule unité de force posée au creux de la main ?" },
  "Nile": { en: "Upper Egypt sits at the bottom of the map. The river decided which end is up.", fr: "Sur la carte, la Haute-Égypte est tout en bas. C'est le fleuve qui a tranché." },
  "Ninety-five_Theses": { en: "A Latin text for scholars. Two weeks later, an entire region had read it.", fr: "Un texte latin pour universitaires. Deux semaines plus tard, toute une région l'avait lu." },
  "Nitrogen_fixation": { en: "Most of every breath you take is a gas your body cannot use.", fr: "L'essentiel de chaque inspiration est un gaz que votre corps ne sait pas utiliser." },
  "Nocturnality": { en: "Why do some animals' eyes glow back at you in a torch beam?", fr: "Pourquoi certains yeux d'animaux renvoient-ils la lumière d'une lampe torche ?" },
  "North_Pole": { en: "You can stand at the North Pole. You cannot build anything there.", fr: "On peut se tenir au pôle Nord. On ne peut rien y construire." },
  "Nubian_pyramids": { en: "Why are the world's most numerous pyramids so much steeper than Egypt's?", fr: "Pourquoi les pyramides les plus nombreuses au monde sont-elles bien plus pentues que celles d'Égypte ?" },
  "Obelisk_of_Axum": { en: "Who took this obelisk out of Ethiopia, and how long until it came home?", fr: "Qui a emporté cet obélisque hors d'Éthiopie, et combien de temps avant son retour ?" },
  "Octopus": { en: "This animal's blood is not red, and the reason is a different metal.", fr: "Le sang de cet animal n'est pas rouge. La faute à un autre métal." },
  "Odyssey": { en: "This poem does not start at the beginning. Ancient audiences expected nothing else.", fr: "Ce poème ne commence pas au début. Le public antique n'attendait rien d'autre." },
  "Ohm": { en: "Voltage, current, resistance. Fix any two of them and the third has no choice.", fr: "Tension, courant, résistance : fixez-en deux, la troisième n'a plus le choix." },
  "Olympus_Mons": { en: "Two Everests stacked on top of each other would not reach this summit.", fr: "Deux Everest empilés l'un sur l'autre n'atteindraient toujours pas ce sommet." },
  "One_Hundred_Years_of_Solitude": { en: "The author could not afford to post the whole manuscript, so he sent half.", fr: "L'auteur n'avait pas de quoi affranchir tout le manuscrit. Il n'en a posté que la moitié." },
  "One_Thousand_and_One_Nights": { en: "Two of the most famous stories in this collection were never part of it.", fr: "Deux des contes les plus célèbres de ce recueil n'y ont jamais figuré." },
  "PH": { en: "The difference between pH 4 and pH 6 is not two. It is far larger.", fr: "Entre pH 4 et pH 6, l'écart n'est pas de deux. Il est bien plus grand." },
  "Pacific_Ocean": { en: "Put every continent on Earth side by side. This ocean still wins.", fr: "Réunissez toutes les terres émergées du globe. Cet océan l'emporte encore." },
  "Panama_Canal": { en: "Ships crossing between two oceans have to climb a hill first. Then come down.", fr: "Pour passer d'un océan à l'autre, les navires doivent d'abord monter. Puis redescendre." },
  "Peace_of_Westphalia": { en: "Why do historians date the modern state to a single peace deal signed in 1648?", fr: "Pourquoi fait-on naître l'État moderne d'un traité signé en 1648 ?" },
  "Penicillin": { en: "A medicine that saved millions began with an untidy scientist's holiday.", fr: "Un médicament qui a sauvé des millions de vies doit tout à un laboratoire mal rangé." },
  "Persepolis": { en: "The best portrait of the Persian Empire is a staircase. It shows who came.", fr: "Le meilleur portrait de l'Empire perse est un escalier. Il montre qui venait." },
  "Petra": { en: "How do you build a city for thousands in a desert that barely rains?", fr: "Comment nourrir en eau une ville de milliers d'habitants dans un désert sans pluie ?" },
  "Phoenician_alphabet": { en: "The alphabet you are reading started out without something you use in every word.", fr: "Cet alphabet se passait d'une chose que vous employez dans chaque mot." },
  "Photosynthesis": { en: "A tree's wood did not come out of the soil. So where did it come from?", fr: "Le bois d'un arbre ne sort pas de la terre. D'où vient-il alors ?" },
  "Pi": { en: "Its digits run to a hundred trillion and counting. Most are never used.", fr: "On en connaît cent mille milliards de décimales. Presque aucune ne sert." },
  "Piano": { en: "This instrument's real name is a pair of opposites. Its rival could only manage one.", fr: "Le vrai nom de cet instrument est une paire de contraires. Son rival n'en offrait qu'un." },
  "Pompeii": { en: "The volcano that killed this town is the reason we can read its walls.", fr: "On sait ce que les habitants griffonnaient sur leurs murs. Grâce au volcan." },
  "Pretoria": { en: "Naming South Africa's capital city is a trick question. The answer is a compromise.", fr: "Demander la capitale de l'Afrique du Sud est un piège. La réponse date de 1910." },
  "Prime_number": { en: "Why does every whole number break into primes in exactly one way?", fr: "Pourquoi tout nombre entier se décompose-t-il en nombres premiers d'une seule façon ?" },
  "Printing_press": { en: "How many books can a continent print in fifty years, starting from none?", fr: "Combien de livres un continent imprime-t-il en cinquante ans, en partant de rien ?" },
  "Pueblo_Bonito": { en: "Its walls are lined up with something that is not on the ground.", fr: "Ses murs sont alignés sur quelque chose qui ne se trouve pas au sol." },
  "QWERTY": { en: "Type the word 'typewriter' and your fingers never leave one row.", fr: "Tapez « typewriter » : vos doigts ne changent pas une seule fois de rangée." },
  "Queen_Victoria": { en: "She was born fifth in line to the throne. Nobody expected her to reign.", fr: "À sa naissance, cinquième dans l'ordre de succession. Personne ne la voyait monter sur le trône." },
  "Quipu": { en: "An empire kept its records on knotted string. Nobody can read all of it yet.", fr: "Un empire tenait ses archives sur des cordes nouées. Personne ne sait encore tout lire." },
  "Ray_Tomlinson": { en: "Why does every email address on Earth contain the same odd little symbol?", fr: "Pourquoi toutes les adresses mail du monde contiennent-elles le même petit signe ?" },
  "Rayleigh_scattering": { en: "The same effect that makes the sky blue also makes sunsets red.", fr: "Un même phénomène rend le ciel bleu le jour et rouge le soir." },
  "Renaissance": { en: "The family that paid for Leonardo and Michelangelo made its money another way entirely.", fr: "La famille qui a payé Léonard et Michel-Ange avait fait fortune tout autrement." },
  "Rideau_Canal": { en: "Ottawa has a commuter route that only exists when it freezes. It holds a record.", fr: "Ottawa possède un axe de circulation qui n'existe que gelé. Il détient un record mondial." },
  "Rock-Hewn_Churches,_Lalibela": { en: "A king built a Jerusalem his people could reach without leaving Ethiopia.", fr: "Un roi a bâti une Jérusalem que ses fidèles atteignaient sans quitter l'Éthiopie." },
  "Roman_roads": { en: "How many kilometres of road does it take to hold an empire together?", fr: "Combien de kilomètres de route faut-il pour tenir un empire entier ?" },
  "Root": { en: "The part of a root that actually drinks is too small to see.", fr: "La partie de la racine qui boit vraiment est invisible à l'œil nu." },
  "Rosetta_Stone": { en: "Everyone knows what this stone did. Almost nobody knows what it says.", fr: "On sait ce que cette pierre a permis. Pas ce qu'elle raconte." },
  "Rust": { en: "Aluminium corrodes too, yet never rots away. Iron has no such luck.", fr: "L'aluminium s'oxyde aussi, mais ne se ronge jamais. Le fer, lui, y passe." },
  "SOS": { en: "The world's most famous distress call is not short for anything.", fr: "Le signal de détresse le plus connu au monde n'est l'abréviation de rien." },
  "Sahara": { en: "This desert would swallow a country you already think of as enormous. Guess which.", fr: "Ce désert avalerait un pays que vous croyez déjà immense. Lequel ?" },
  "Saltwater_crocodile": { en: "No living animal bites harder than this one. Sharks are not close.", fr: "Aucun animal vivant ne mord plus fort. Les requins n'en approchent pas." },
  "Samurai": { en: "The famous samurai code was largely written down after the samurai stopped fighting.", fr: "Le fameux code des samouraïs a surtout été écrit une fois les guerres finies." },
  "Sardinia": { en: "The Mediterranean's largest island and its runner-up fly the same flag. This is the smaller.", fr: "La plus grande île de Méditerranée et sa dauphine portent le même drapeau. Voici la seconde." },
  "Saturn": { en: "Saturn's rings run 280,000 kilometres across. Now guess how thick they are.", fr: "Les anneaux de Saturne s'étendent sur 280 000 kilomètres. Devinez leur épaisseur." },
  "Scurvy": { en: "It killed more sailors than storms and battle combined. The cure cost almost nothing.", fr: "Il tuait plus de marins que les tempêtes et les combats. Le remède ne coûtait rien." },
  "Self-portraits_by_Rembrandt": { en: "No photographs existed, yet we know exactly how this man aged. He saw to it.", fr: "Aucune photographie n'existait, et l'on sait pourtant comment cet homme a vieilli. Il y a veillé." },
  "Sequoia_sempervirens": { en: "The tallest living thing on Earth has a name, and an address kept secret.", fr: "Le plus haut être vivant de la Terre a un nom — et une adresse tenue secrète." },
  "Sequoyah": { en: "He could not read a single language when he invented a way to write one.", fr: "Il ne savait lire aucune langue quand il inventa le moyen d'en écrire une." },
  "Serfdom": { en: "For most medieval villagers, one thing was harder than farming: leaving.", fr: "Pour la plupart des villageois médiévaux, une chose était plus dure que labourer : partir." },
  "Sexagesimal": { en: "Why does an hour have sixty minutes instead of a round hundred?", fr: "Pourquoi une heure compte-t-elle soixante minutes, et non cent, bien plus commodes ?" },
  "Silicon": { en: "Chips are made from sand, and the hard part is taking things out.", fr: "Les puces sont faites de sable ; le plus dur est d'en retirer le reste." },
  "Silk_Road": { en: "Silk was the least dangerous thing that ever travelled this road.", fr: "La soie fut la marchandise la moins dangereuse à emprunter cette route." },
  "Sistine_Chapel_ceiling": { en: "Everyone pictures him lying on his back to paint this. Everyone pictures it wrong.", fr: "Chacun l'imagine allongé sur le dos pour peindre ce plafond. Chacun se trompe." },
  "Sodium_bicarbonate": { en: "The same powder that makes a toy volcano erupt also makes bread rise.", fr: "La poudre qui fait déborder le volcan de la fête fait aussi lever le pain." },
  "Sodium_chloride": { en: "Tip out some salt and look closely. The grains share one shape.", fr: "Versez du sel et regardez de près : les grains ont tous la même forme." },
  "Solomon_R._Guggenheim_Museum": { en: "You are meant to see this museum in reverse, starting at the very top.", fr: "Ce musée se visite à l'envers : on commence tout en haut. Pourquoi donc ?" },
  "Songhai_Empire": { en: "One of Africa's largest empires fell to an army that crossed the Sahara.", fr: "L'un des plus vastes empires d'Afrique est tombé face à une armée venue du désert." },
  "Sound": { en: "Every space battle you have ever watched got one thing badly wrong.", fr: "Toutes les batailles spatiales du cinéma se trompent sur un point précis." },
  "Speed_of_sound": { en: "The gap between a flash and its bang is a measuring tape.", fr: "L'écart entre l'éclair et le tonnerre est une règle graduée." },
  "Srivijaya": { en: "This empire ruled the sea lanes for centuries, then vanished from history until 1918.", fr: "Cet empire régna des siècles sur les mers, puis disparut de l'histoire jusqu'en 1918." },
  "Stephenson's_Rocket": { en: "Ten machines entered the contest of 1829. Only one of them finished.", fr: "Dix machines inscrites à l'épreuve de 1829. Une seule est allée au bout." },
  "Stockholm_archipelago": { en: "The capital occupies fourteen islands. Just offshore, nobody has finished counting the rest.", fr: "La capitale occupe quatorze îles. Juste au large, personne n'a fini de compter." },
  "Strait_of_Gibraltar": { en: "From a beach in Europe, on a clear day, you can watch Africa.", fr: "Depuis une plage d'Europe, par temps clair, on peut regarder l'Afrique." },
  "Suez_Canal": { en: "Two seas joined by one channel, and not a single lock. How?", fr: "Deux mers, un canal, pas une seule écluse. Comment est-ce seulement possible ?" },
  "Sun": { en: "The Sun loses millions of tonnes every second and has barely noticed.", fr: "Le Soleil perd des millions de tonnes par seconde sans même s'en apercevoir." },
  "Sunlight": { en: "You have never once seen the Sun as it is right now.", fr: "Vous n'avez jamais vu le Soleil tel qu'il est en cet instant." },
  "Swahili_coast": { en: "These traders never chose when to sail. The wind decided, twice a year.", fr: "Ces marchands ne choisissaient pas leur départ : le vent le fixait deux fois par an." },
  "Sydney_Opera_House": { en: "The architect walked off this building site and never saw the finished roof.", fr: "L'architecte a quitté ce chantier et n'a jamais vu le toit achevé." },
  "Symphony_No._9_(Beethoven)": { en: "The composer of this symphony never heard it. He was in the room.", fr: "Le compositeur de cette symphonie ne l'a jamais entendue. Il était pourtant dans la salle." },
  "Taghaza": { en: "A town where every meal had to arrive by camel, and somehow always did.", fr: "Une ville où chaque repas devait arriver à dos de chameau — et arrivait." },
  "Taíno": { en: "You use several everyday words from a language that colonisation wiped out.", fr: "Vous employez chaque jour des mots d'une langue que la colonisation a fait disparaître." },
  "Terracotta_Army": { en: "Eight thousand soldiers guard a tomb nobody has opened in fifty years of digging.", fr: "Huit mille soldats gardent un tombeau toujours pas ouvert, cinquante ans après." },
  "The_Canon_of_Medicine": { en: "How long can one textbook stay on a medical syllabus before doctors move on?", fr: "Combien de siècles un manuel de médecine peut-il rester au programme avant d'être abandonné ?" },
  "The_Great_Wave_off_Kanagawa": { en: "The wave is not the subject of this print. Look for what is.", fr: "La vague n'est pas le sujet de cette estampe. Cherchez ce qui l'est." },
  "The_Scream": { en: "There is more than one of this painting, and thieves have taken more than one.", fr: "Ce tableau existe en plusieurs exemplaires, et des voleurs en ont emporté plus d'un." },
  "The_Starry_Night": { en: "The night sky in this painting was not in front of the painter.", fr: "Le ciel de ce tableau ne se trouvait pas devant le peintre." },
  "The_Tale_of_Genji": { en: "Japan had a full novel by the year 1000. Its author's real name is unknown.", fr: "Le Japon avait un roman complet vers l'an mille. Le vrai nom de l'autrice reste inconnu." },
  "Things_Fall_Apart": { en: "The title of this novel is a quotation. The poet had never seen Africa.", fr: "Le titre de ce roman est une citation. Son auteur n'avait jamais vu l'Afrique." },
  "Three_Sisters_(agriculture)": { en: "Why plant three different crops in one mound instead of three tidy fields?", fr: "Pourquoi semer trois cultures dans la même butte plutôt qu'en trois champs bien rangés ?" },
  "Tideway": { en: "Twice a day London's river climbs two storeys, then walks back out again.", fr: "Deux fois par jour, le fleuve de Londres monte de deux étages, puis repart." },
  "Tifinagh": { en: "An alphabet with 2,500-year-old inscriptions is back in primary school classrooms.", fr: "Un alphabet dont les inscriptions ont 2 500 ans revient dans les salles de classe." },
  "Tiger": { en: "Shave a tiger and the stripes are still there. They are not fur.", fr: "Rasez un tigre : les rayures restent. Elles ne sont pas dans le pelage." },
  "Timbuktu": { en: "Timbuktu became European shorthand for nowhere. Its families were guarding libraries.", fr: "En Europe, Tombouctou signifie « le bout du monde ». Ses familles y gardaient des bibliothèques." },
  "Time_in_France": { en: "No country on Earth runs more time zones than France. Paris explains only one.", fr: "Aucun pays ne compte autant de fuseaux horaires que la France. Paris n'en explique qu'un." },
  "Time_in_Russia": { en: "Eleven time zones, and for decades the railway timetables refused to admit it.", fr: "Onze fuseaux horaires — et des gares qui, pendant des décennies, ont refusé de le reconnaître." },
  "Tokyo": { en: "For a thousand years the capital was elsewhere. This city's name still announces the move.", fr: "Pendant mille ans, la capitale fut ailleurs. Le nom de cette ville annonce encore le déménagement." },
  "Tooth_enamel": { en: "The hardest thing your body makes is the one thing it cannot repair.", fr: "La substance la plus dure de votre corps est la seule qu'il ne répare pas." },
  "Tornado": { en: "The strongest of these beats anything a hurricane has produced. Radar had to measure it.", fr: "Le plus violent d'entre eux dépasse tout ouragan connu. Seul un radar a pu le mesurer." },
  "Turing_test": { en: "He asked whether machines can think, then decided it was the wrong question.", fr: "Il demande si les machines pensent, puis juge la question mal posée." },
  "Tutankhamun": { en: "The best-known pharaoh in the world was erased from Egypt's own king lists.", fr: "Le pharaon le plus connu au monde avait été effacé des listes royales égyptiennes." },
  "Ulugh_Beg": { en: "How closely can you measure the length of a year without a telescope?", fr: "Jusqu'où peut-on mesurer la durée d'une année sans le moindre télescope ?" },
  "Units_of_information": { en: "A terabyte holds a million megabytes. Data centres already needed a bigger word.", fr: "Un téraoctet vaut un million de mégaoctets. Les centres de données comptent déjà plus grand." },
  "University_of_al-Qarawiyyin": { en: "It had been teaching for two centuries before Europe's first university opened its doors.", fr: "Elle enseignait depuis deux siècles quand la première université d'Europe a ouvert ses portes." },
  "Vatican_City": { en: "A whole country fits inside one city, and still found room for a railway.", fr: "Un pays entier tient dans une seule ville, et il y a pourtant une gare." },
  "Victoria_Falls": { en: "People fifty kilometres away can see the smoke from this waterfall. Nothing is burning.", fr: "À cinquante kilomètres, on aperçoit la fumée de cette chute. Aucun feu ne brûle." },
  "Violin": { en: "Four strings, and no frets to tell you where the notes are. Deliberately.", fr: "Quatre cordes, et aucune frette pour indiquer où sont les notes. C'est voulu." },
  "Washington_Monument": { en: "The tip of this monument is a metal we now throw away.", fr: "Sa pointe est faite d'un métal qu'aujourd'hui on jette à la poubelle." },
  "Wellington": { en: "The world's southernmost capital was not the country's first choice. Gold changed the decision.", fr: "La capitale la plus australe du monde n'était pas la première. C'est l'or qui a tout changé." },
  "White_blood_cell": { en: "Your body's entire defence force is outnumbered a thousand to one.", fr: "Toute votre armée de défense est en infériorité de mille contre un." },
  "Women's_suffrage_in_New_Zealand": { en: "The first country where women could vote still would not let them stand.", fr: "Premier pays où les femmes ont voté. Pas le premier où elles pouvaient être élues." },
  "Wreck_of_the_Titanic": { en: "The ship sank in 1912. It then stayed lost for another seventy-three years.", fr: "Le navire a coulé en 1912. Il est resté introuvable pendant soixante-treize ans." },
  "Wright_brothers": { en: "The first powered aeroplane was paid for, and built, by a bicycle shop.", fr: "Le premier avion motorisé a été payé et construit par un magasin de vélos." },
  "Yam_(route)": { en: "How fast could news cross the world's largest empire on horseback?", fr: "À quelle vitesse une nouvelle traversait-elle le plus vaste empire du monde, à cheval ?" },
  "Yuan_dynasty": { en: "Modern Beijing still follows a street grid drawn up by an emperor from the steppe.", fr: "Pékin suit encore aujourd'hui un plan tracé par un empereur venu des steppes." },
  "Zheng_He": { en: "An admiral sailed home with an animal the court decided was mythical.", fr: "Un amiral rapporta un animal que la cour prit pour une créature de légende." }
};
