// © 2026 Qpio. All rights reserved. Not covered by the MIT LICENSE.
// Terms of use: /CONTENT-LICENCE.md · Machine use reserved: /ai.txt
//
// QUESTION INTELLIGENCE V1 — CALIBRATION SAMPLE (30 questions).
//
// Each entry is question-shaped and carries the original fields VERBATIM from
// src/questions.js (bank_index points at the source row; id is the app's own
// qid). tools/intelligence.test.js re-verifies the echo against the live bank
// on every run, so a later wording edit fails loudly instead of silently
// detaching intelligence from its question.
//
// `note` is the internal scoring rationale — calibration material for the
// human review, not production copy. See docs/QI_CALIBRATION_V1.md.
//
// Scores are editorial metadata, not validated measurements.
window.CURIO_QI_CALIBRATION = [
  // 01 · anchor · Great Pyramid
  { id: "q1ree1ha", bank_index: 0,
    cat: "History",
    region: "Africa",
    diff: 1,
    kids: true,
    q: "Which ancient wonder still stands today?",
    options: ["Hanging Gardens of Babylon","Great Pyramid of Giza","Colossus of Rhodes","Lighthouse of Alexandria"],
    answer: 1,
    fact: "The Great Pyramid was the tallest human-made structure on Earth for ~3,800 years.",
    src: "https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza",
    intelligence: {"archetypes":["anchor"],"curiosity":{"curiosity_gap":2,"surprise":2,"familiarity_anchor":5,"human_pull":2,"connection":3,"discovery":1,"perspective_shift":1},"tension":{"familiarity":5,"novelty":1,"optimality":3},"resource_depth":{"depth":4,"density":5,"diversity":5,"resonance":4,"experiential":5,"next_step":2},"closure":{"risk":3},"rabbit_hole":{"depth":3,"branches":["history","archaeology","architecture","place"],"entities":["Great_Pyramid_of_Giza","Khufu","Giza_pyramid_complex","Seven_Wonders_of_the_Ancient_World"]}},
    note: "Canonical anchor. Everyone starts knowing the pyramids; \"still standing\" leaves one small door open (why did the others vanish?). Resonance 4: Giza/Cairo resources follow naturally from the question itself." },
  // 02 · anchor · first person on the Moon
  { id: "q75g66a", bank_index: 10,
    cat: "History",
    region: "Global",
    diff: 1,
    kids: true,
    q: "Who was the first person to walk on the Moon, in 1969?",
    options: ["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","Michael Collins"],
    answer: 0,
    fact: "The Moon has no wind or rain, so the astronauts' boot prints could stay crisp for millions of years.",
    src: "https://en.wikipedia.org/wiki/Apollo_11",
    intelligence: {"archetypes":["anchor"],"curiosity":{"curiosity_gap":1,"surprise":1,"familiarity_anchor":5,"human_pull":2,"connection":3,"discovery":1,"perspective_shift":1},"tension":{"familiarity":5,"novelty":1,"optimality":2},"resource_depth":{"depth":3,"density":5,"diversity":5,"resonance":3,"experiential":4,"next_step":2},"closure":{"risk":4},"rabbit_hole":{"depth":2,"branches":["science","technology","people"],"entities":["Apollo_11","Neil_Armstrong","Buzz_Aldrin","NASA"]}},
    note: "Pure recall; the boot-print fact is the only spark. Named calibration case. High resource density but only moderate resonance — this exact question does not pull them in. Anchor for pacing." },
  // 03 · contradiction · Hundred Years’ War
  { id: "q1df007o", bank_index: 19,
    cat: "History",
    region: "Europe",
    diff: 3,
    q: "How many years did the Hundred Years' War between England and France actually last?",
    options: ["116 years","100 years","99 years","130 years"],
    answer: 0,
    fact: "Despite its name it ran 116 years (1337–1453) — a series of wars between England and France broken up by long truces.",
    src: "https://en.wikipedia.org/wiki/Hundred_Years%27_War",
    intelligence: {"archetypes":["contradiction","surprise"],"curiosity":{"curiosity_gap":3,"surprise":4,"familiarity_anchor":4,"human_pull":2,"connection":3,"discovery":2,"perspective_shift":2},"tension":{"familiarity":4,"novelty":2,"optimality":4},"resource_depth":{"depth":3,"density":4,"diversity":4,"resonance":3,"experiential":3,"next_step":3},"closure":{"risk":3},"rabbit_hole":{"depth":3,"branches":["history","politics","people","place"],"entities":["Hundred_Years'_War","Joan_of_Arc","House_of_Plantagenet","Battle_of_Agincourt"]}},
    note: "The rubber band in miniature: the name is familiar, the name is wrong (116 years). Optimality 4 — you know enough to care, not enough to be satisfied. Next step: so why did it keep stopping and starting?" },
  // 04 · surprise · Sudan has more pyramids than Egypt
  { id: "qfz82ti", bank_index: 22,
    cat: "History",
    region: "Africa",
    diff: 2,
    kids: true,
    q: "Which land, home to the ancient Kingdom of Kush, actually contains more ancient pyramids than Egypt?",
    options: ["Libya","Sudan","Ethiopia","Chad"],
    answer: 1,
    fact: "Sudan holds roughly 200 ancient pyramids — more than double Egypt's — steep, sharp-sided royal tombs for the kings and queens of Kush.",
    src: "https://en.wikipedia.org/wiki/Nubian_pyramids",
    intelligence: {"archetypes":["surprise","reveal","perspective_shift"],"curiosity":{"curiosity_gap":4,"surprise":5,"familiarity_anchor":4,"human_pull":2,"connection":4,"discovery":5,"perspective_shift":4},"tension":{"familiarity":4,"novelty":4,"optimality":5},"resource_depth":{"depth":4,"density":3,"diversity":4,"resonance":5,"experiential":4,"next_step":4},"closure":{"risk":1},"rabbit_hole":{"depth":4,"branches":["history","archaeology","architecture","place","culture"],"entities":["Nubian_pyramids","Kingdom_of_Kush","Meroë","Sudan"]}},
    note: "Strongest surprise-per-familiarity in the sample: pyramids are the anchor, \"more than Egypt\" is the stretch, and the Egypt-centric mental model of African antiquity visibly shifts. Density 3 (not 5): mainstream resources are thinner than for Egypt — honest scoring." },
  // 05 · portal · Battle of Adwa
  { id: "q19iny74", bank_index: 26,
    cat: "History",
    region: "Africa",
    diff: 2,
    q: "In 1896 Ethiopia defeated an invading European army at the Battle of Adwa, keeping its independence. Which country did it defeat?",
    options: ["Britain","France","Italy","Portugal"],
    answer: 2,
    fact: "Led by Emperor Menelik II and Empress Taytu Betul, Ethiopia routed the Italian army — a rare defeat of a European power in the Scramble for Africa.",
    src: "https://en.wikipedia.org/wiki/Battle_of_Adwa",
    deeper: ["Adwa became a rallying symbol of anti-colonial pride for Africans and people of African descent around the world.","Italy invaded again in 1935 and occupied Ethiopia, but was driven out by 1941; it never became a lasting colony."],
    intelligence: {"archetypes":["human_story","perspective_shift","portal"],"curiosity":{"curiosity_gap":4,"surprise":4,"familiarity_anchor":2,"human_pull":5,"connection":5,"discovery":5,"perspective_shift":5},"tension":{"familiarity":2,"novelty":5,"optimality":4},"resource_depth":{"depth":5,"density":3,"diversity":4,"resonance":5,"experiential":3,"next_step":5},"closure":{"risk":0},"rabbit_hole":{"depth":5,"branches":["history","politics","people","culture","place"],"entities":["Battle_of_Adwa","Menelik_II","Taytu_Betul","Ethiopian_Empire","Italian_Empire"]}},
    note: "The mandate’s own entity set. Perspective shift is maximal: the Scramble for Africa stops looking inevitable. Menelik + Taytu give it a human engine; \"what happened when Italy came back in 1935\" is the built-in next step." },
  // 06 · portal · Benin Bronzes
  { id: "qcmjvtg", bank_index: 27,
    cat: "History",
    region: "Africa",
    diff: 3,
    q: "The celebrated 'Benin Bronzes' — intricate cast plaques and heads — were made by the Kingdom of Benin, in what is now which country?",
    options: ["Republic of Benin","Ghana","Nigeria","Cameroon"],
    answer: 2,
    fact: "Cast in brass by the lost-wax method, the plaques lined the royal palace, recording the Edo kingdom's history in metal.",
    src: "https://en.wikipedia.org/wiki/Benin_Bronzes",
    deeper: ["British forces looted thousands of the works in 1897; many still sit in Western museums, though Nigeria has begun winning some back.","Their fine casting stunned Europeans and undercut false claims that such sophisticated art could not be African in origin."],
    intelligence: {"archetypes":["reveal","perspective_shift","portal"],"curiosity":{"curiosity_gap":4,"surprise":4,"familiarity_anchor":2,"human_pull":4,"connection":5,"discovery":5,"perspective_shift":5},"tension":{"familiarity":2,"novelty":5,"optimality":4},"resource_depth":{"depth":5,"density":4,"diversity":5,"resonance":5,"experiential":5,"next_step":5},"closure":{"risk":0},"rabbit_hole":{"depth":5,"branches":["art","history","politics","culture","people"],"entities":["Benin_Bronzes","Kingdom_of_Benin","Benin_City","British_Museum","Oba_of_Benin"]}},
    note: "The restitution debate keeps curiosity open by construction (closure 0). Experiential 5: the objects sit in named museums on three continents. Perspective shift: \"African art\" and \"museum\" both get reframed." },
  // 07 · reveal · Lalibela churches carved downward
  { id: "qqx4717", bank_index: 29,
    cat: "History",
    region: "Africa",
    diff: 3,
    q: "The 11 medieval churches of Lalibela in Ethiopia are famous because they were:",
    options: ["Built from imported marble","Carved downward out of solid rock","Made entirely of gold","Floated on a lake"],
    answer: 1,
    fact: "Carved top-down from single blocks of rock about 800 years ago as a 'New Jerusalem', they are still living churches of Ethiopian Orthodoxy.",
    src: "https://en.wikipedia.org/wiki/Rock-Hewn_Churches,_Lalibela",
    deeper: ["Trenches and tunnels link the churches, and features were named for holy sites, recreating Jerusalem in the Ethiopian highlands.","They were cut with hand tools like hammers and chisels; tradition says the work took about 24 years."],
    intelligence: {"archetypes":["reveal","portal"],"curiosity":{"curiosity_gap":4,"surprise":4,"familiarity_anchor":1,"human_pull":3,"connection":4,"discovery":5,"perspective_shift":3},"tension":{"familiarity":1,"novelty":5,"optimality":3},"resource_depth":{"depth":4,"density":3,"diversity":4,"resonance":5,"experiential":5,"next_step":4},"closure":{"risk":1},"rabbit_hole":{"depth":4,"branches":["architecture","religion","history","place","archaeology"],"entities":["Rock-Hewn_Churches,_Lalibela","Lalibela","Ethiopian_Orthodox_Tewahedo_Church"]}},
    note: "\"How do you carve a church downward out of one rock?\" is the engine. Familiarity anchor is near zero for a general reader — flagged as a boundary case: strong reveal, but the rubber band starts slack. Still living churches: visitable." },
  // 08 · reveal · Haudenosaunee Great Law of Peace
  { id: "q1x7chof", bank_index: 37,
    cat: "History",
    region: "Americas",
    diff: 3,
    q: "The Haudenosaunee (Iroquois) Confederacy united nations under its Great Law of Peace. How many nations did it originally bring together?",
    options: ["Five","Two","Nine","Thirteen"],
    answer: 0,
    fact: "The five founders were the Mohawk, Oneida, Onondaga, Cayuga and Seneca; the Tuscarora acceded in 1722, making it the Six Nations.",
    src: "https://en.wikipedia.org/wiki/Great_Law_of_Peace",
    deeper: ["The confederacy's emblem is a great eastern white pine, the Tree of Peace, standing for the nations joined as one.","Its Great Law was recorded not on paper but on wampum — belts of shell beads encoding the message in pictograms."],
    intelligence: {"archetypes":["reveal","perspective_shift","origin"],"curiosity":{"curiosity_gap":3,"surprise":3,"familiarity_anchor":2,"human_pull":3,"connection":4,"discovery":4,"perspective_shift":4},"tension":{"familiarity":2,"novelty":4,"optimality":3},"resource_depth":{"depth":4,"density":3,"diversity":4,"resonance":4,"experiential":3,"next_step":4},"closure":{"risk":2},"rabbit_hole":{"depth":4,"branches":["politics","history","people","culture"],"entities":["Haudenosaunee","Great_Law_of_Peace","Wampum","Tuscarora_people"]}},
    note: "Governance recorded in wampum, not writing — reframes where \"democracy\" has roots. The influence-on-the-US-Constitution debate is a live scholarly branch, which is why connection scores high." },
  // 09 · mystery · Terracotta Army (unopened tomb)
  { id: "q1a17two", bank_index: 40,
    cat: "History",
    region: "Asia",
    diff: 1,
    kids: true,
    q: "The Terracotta Army — thousands of life-sized clay soldiers — was buried to guard the tomb of which ruler?",
    options: ["Qin Shi Huang","Confucius","Kublai Khan","Sun Tzu"],
    answer: 0,
    fact: "Qin Shi Huang was China's first emperor, uniting its warring states in 221 BCE. No two of the roughly 8,000 terracotta soldiers share the same face.",
    src: "https://en.wikipedia.org/wiki/Terracotta_Army",
    deeper: ["The central tomb mound has never been dug up; ancient records tell of rivers of mercury inside, and soil tests there really do show unusually high mercury.","The clay warriors were once brightly painted, but the lacquer can flake off within minutes of meeting dry air after 2,000 years underground."],
    intelligence: {"archetypes":["anchor","mystery"],"curiosity":{"curiosity_gap":3,"surprise":3,"familiarity_anchor":4,"human_pull":3,"connection":4,"discovery":3,"perspective_shift":2},"tension":{"familiarity":4,"novelty":3,"optimality":4},"resource_depth":{"depth":4,"density":4,"diversity":5,"resonance":4,"experiential":5,"next_step":4},"closure":{"risk":2},"rabbit_hole":{"depth":4,"branches":["archaeology","history","art","place"],"entities":["Terracotta_Army","Qin_Shi_Huang","Mausoleum_of_the_First_Qin_Emperor","Xi'an"]}},
    note: "The question is an anchor; the deeper material converts it — the central tomb has never been excavated and the mercury-rivers legend matches soil tests. Genuine unresolved puzzle, rare in this corpus." },
  // 10 · origin · Hangul, a king’s alphabet for ordinary people
  { id: "q1e0h1gt", bank_index: 43,
    cat: "History",
    region: "Asia",
    diff: 2,
    kids: true,
    q: "Korea's own alphabet, Hangul, was created in the 1440s under which king?",
    options: ["Gwanggaeto","Sejong the Great","Taejo","Kublai Khan"],
    answer: 1,
    fact: "Hangul was made so ordinary people could read easily; the shapes of its consonants copy how the tongue and lips move to make each sound.",
    src: "https://en.wikipedia.org/wiki/Hangul",
    deeper: ["Many elite scholars scorned Hangul, preferring Chinese characters; it only became Korea's main script in the late 1800s. Koreans mark Hangul Day each October.","Because its letters map so neatly onto sounds, Hangul is often praised as one of the most logical and easy-to-learn writing systems ever created."],
    intelligence: {"archetypes":["origin","human_story","reveal"],"curiosity":{"curiosity_gap":3,"surprise":3,"familiarity_anchor":3,"human_pull":4,"connection":4,"discovery":4,"perspective_shift":3},"tension":{"familiarity":3,"novelty":3,"optimality":4},"resource_depth":{"depth":3,"density":3,"diversity":4,"resonance":4,"experiential":3,"next_step":3},"closure":{"risk":2},"rabbit_hole":{"depth":3,"branches":["culture","history","people"],"entities":["Hangul","Sejong_the_Great","Joseon"]}},
    note: "Origin with a human conflict core: designed for commoners, scorned by elites. The letter-shapes-mimic-mouth design is the connection branch into linguistics." },
  // 11 · connection · Al-Khwarizmi: algebra to algorithm
  { id: "quj1ju9", bank_index: 62,
    cat: "History",
    region: "MiddleEast",
    diff: 2,
    kids: true,
    q: "The word 'algebra' comes from a book written by which scholar of Baghdad's House of Wisdom?",
    options: ["Omar Khayyam","Ibn Sina","Al-Razi","Al-Khwarizmi"],
    answer: 3,
    fact: "The title word 'al-jabr' means 'restoration' — the step of balancing an equation by adding equal amounts to both sides; we now call the whole subject algebra.",
    src: "https://en.wikipedia.org/wiki/Al-Khwarizmi",
    deeper: ["The word 'algorithm' also comes from his name, which medieval Europe wrote in Latin as 'Algoritmi'.","He helped spread Hindu-Arabic numerals — the 0-9 digits the world still writes with today."],
    intelligence: {"archetypes":["connection","origin"],"curiosity":{"curiosity_gap":3,"surprise":4,"familiarity_anchor":3,"human_pull":2,"connection":5,"discovery":4,"perspective_shift":3},"tension":{"familiarity":3,"novelty":3,"optimality":4},"resource_depth":{"depth":4,"density":4,"diversity":4,"resonance":5,"experiential":2,"next_step":4},"closure":{"risk":1},"rabbit_hole":{"depth":4,"branches":["science","technology","history","culture"],"entities":["Al-Khwarizmi","Algebra","House_of_Wisdom","Algorithm"]}},
    note: "The deeper material carries the punch: \"algorithm\" is his name, Latinised. School maths and the phone in your pocket turn out to be one story — connection 5." },
  // 12 · reveal · Fatima al-Fihri founds al-Qarawiyyin
  { id: "qzduhel", bank_index: 75,
    cat: "History",
    region: "Africa",
    country: "Morocco",
    diff: 2,
    q: "The Qarawiyyin in Fes, Morocco — a mosque and centre of learning teaching since the 9th century — was founded, tradition holds, by whom?",
    options: ["Ibn Khaldun, the historian","Fatima al-Fihri, a merchant's daughter","Idris II, founder of Fes","An Almohad caliph"],
    answer: 1,
    fact: "UNESCO and Guinness World Records cite al-Qarawiyyin as the world's oldest continually operating higher-learning institution — built with Fatima's inheritance.",
    src: "https://en.wikipedia.org/wiki/University_of_al-Qarawiyyin",
    intelligence: {"archetypes":["reveal","human_story","origin"],"curiosity":{"curiosity_gap":4,"surprise":4,"familiarity_anchor":1,"human_pull":4,"connection":4,"discovery":5,"perspective_shift":4},"tension":{"familiarity":1,"novelty":5,"optimality":3},"resource_depth":{"depth":4,"density":3,"diversity":4,"resonance":5,"experiential":4,"next_step":4},"closure":{"risk":1},"rabbit_hole":{"depth":4,"branches":["history","religion","people","place","culture"],"entities":["University_of_al-Qarawiyyin","Fatima_al-Fihri","Fez,_Morocco"]}},
    note: "Quietly corrects the \"universities are a medieval-European invention\" default, with a woman’s inheritance as the engine. Low anchor, high stretch — same boundary family as Lalibela." },
  // 13 · trivia · photosynthesis gas
  { id: "q1sf7kzp", bank_index: 103,
    cat: "Science",
    sub: "Life Sciences",
    diff: 1,
    kids: true,
    q: "What gas do plants primarily absorb for photosynthesis?",
    options: ["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"],
    answer: 2,
    fact: "A large tree can absorb ~22 kg of CO2 per year and release enough oxygen for two people.",
    src: "https://en.wikipedia.org/wiki/Photosynthesis",
    intelligence: {"archetypes":["anchor"],"curiosity":{"curiosity_gap":0,"surprise":0,"familiarity_anchor":5,"human_pull":0,"connection":2,"discovery":0,"perspective_shift":0},"tension":{"familiarity":5,"novelty":0,"optimality":1},"resource_depth":{"depth":2,"density":5,"diversity":4,"resonance":2,"experiential":2,"next_step":1},"closure":{"risk":5},"rabbit_hole":{"depth":1,"branches":["science"],"entities":["Photosynthesis"]}},
    note: "Calibration floor. Perfectly useful kids’ recall question; curiosity loop closes the instant the answer lands. Density 5 (school resources abound) but resonance 2 — they do not follow from THIS question." },
  // 14 · origin · penicillin
  { id: "q1ji8txo", bank_index: 151,
    cat: "Science",
    sub: "Life Sciences",
    diff: 2,
    q: "Who discovered penicillin in 1928?",
    options: ["Louis Pasteur","Alexander Fleming","Joseph Lister","Robert Koch"],
    answer: 1,
    fact: "Alexander Fleming discovered penicillin in 1928 when mould drifting onto a lab dish killed the bacteria growing around it.",
    src: "https://en.wikipedia.org/wiki/Penicillin",
    deeper: ["It was a lucky accident — Fleming had left culture dishes out while away and returned to find a tell-tale clear ring around the mould.","Turning it into a usable medicine took another decade and the urgency of World War II, work led by Howard Florey and Ernst Chain."],
    intelligence: {"archetypes":["origin","human_story","surprise"],"curiosity":{"curiosity_gap":3,"surprise":3,"familiarity_anchor":4,"human_pull":4,"connection":4,"discovery":2,"perspective_shift":2},"tension":{"familiarity":4,"novelty":2,"optimality":3},"resource_depth":{"depth":4,"density":5,"diversity":5,"resonance":4,"experiential":3,"next_step":3},"closure":{"risk":2},"rabbit_hole":{"depth":3,"branches":["science","people","history"],"entities":["Penicillin","Alexander_Fleming","Howard_Florey","Ernst_Boris_Chain"]}},
    note: "The famous half (Fleming’s accident) is familiar; the under-told half (Florey/Chain’s wartime mass-production race) is the continuation. Discovery 2 not 4: the outline is already widely known." },
  // 15 · surprise · Diomede: 3.8 km apart, 21 hours apart
  { id: "q1l9aiel", bank_index: 193,
    cat: "Geography",
    sub: "Countries & Flags",
    diff: 2,
    q: "The Bering Strait separates Russia from which country?",
    options: ["Canada","Japan","United States","Norway"],
    answer: 2,
    fact: "Mid-strait, Russia's Big Diomede and America's Little Diomede sit just 3.8 km apart — yet the date line between them puts them about 21 hours apart.",
    src: "https://en.wikipedia.org/wiki/Diomede_Islands",
    deeper: ["That's why the pair are nicknamed Tomorrow Island (Big Diomede) and Yesterday Island (Little Diomede).","In winter an ice bridge can form between them — technically letting a person walk from the USA to Russia."],
    intelligence: {"archetypes":["surprise","connection"],"curiosity":{"curiosity_gap":4,"surprise":5,"familiarity_anchor":3,"human_pull":1,"connection":4,"discovery":4,"perspective_shift":3},"tension":{"familiarity":3,"novelty":4,"optimality":4},"resource_depth":{"depth":3,"density":3,"diversity":3,"resonance":4,"experiential":2,"next_step":4},"closure":{"risk":1},"rabbit_hole":{"depth":3,"branches":["place","politics","science","environment"],"entities":["Diomede_Islands","Bering_Strait","International_Date_Line","Beringia"]}},
    note: "Tomorrow Island / Yesterday Island. The absurdity is geographical, the branches are political (Cold War \"Ice Curtain\") and deep-historical (Beringia migration). Experiential 2: almost nobody can go." },
  // 16 · surprise · Bolivia’s landlocked navy
  { id: "q19gz2g9", bank_index: 196,
    cat: "Geography",
    sub: "Countries & Flags",
    diff: 3,
    q: "Which two South American countries are landlocked?",
    options: ["Bolivia and Paraguay","Peru and Bolivia","Paraguay and Uruguay","Ecuador and Venezuela"],
    answer: 0,
    fact: "Bolivia still maintains a navy — patrolling Lake Titicaca — having lost its entire coastline to Chile in the War of the Pacific (1879–83).",
    src: "https://en.wikipedia.org/wiki/Bolivian_Navy",
    deeper: ["Lake Titicaca, which Bolivia shares with Peru, is the highest navigable lake in the world.","The naval force was established in 1963, six decades after a 1904 treaty formalized the loss of Bolivia's coastline."],
    intelligence: {"archetypes":["surprise","contradiction","human_story"],"curiosity":{"curiosity_gap":4,"surprise":5,"familiarity_anchor":3,"human_pull":3,"connection":4,"discovery":5,"perspective_shift":3},"tension":{"familiarity":3,"novelty":4,"optimality":4},"resource_depth":{"depth":3,"density":3,"diversity":4,"resonance":5,"experiential":4,"next_step":4},"closure":{"risk":1},"rabbit_hole":{"depth":4,"branches":["place","history","politics","culture"],"entities":["Bolivian_Navy","War_of_the_Pacific","Lake_Titicaca","Bolivia"]}},
    note: "golinks.js’ own example of a pulling hook: \"Why does a landlocked country have a navy?\" The navy is national memory of a lost coast, kept afloat on the world’s highest navigable lake — visitable." },
  // 17 · anchor · Mona Lisa
  { id: "qrmkt8s", bank_index: 202,
    cat: "Arts",
    sub: "Painting & Sculpture",
    diff: 1,
    kids: true,
    q: "Who painted the Mona Lisa?",
    options: ["Michelangelo","Leonardo da Vinci","Raphael","Donatello"],
    answer: 1,
    fact: "The Mona Lisa has no visible eyebrows — a fashion of the era, or lost to cleaning.",
    src: "https://en.wikipedia.org/wiki/Mona_Lisa",
    intelligence: {"archetypes":["anchor"],"curiosity":{"curiosity_gap":1,"surprise":2,"familiarity_anchor":5,"human_pull":2,"connection":3,"discovery":1,"perspective_shift":1},"tension":{"familiarity":5,"novelty":1,"optimality":2},"resource_depth":{"depth":4,"density":5,"diversity":5,"resonance":3,"experiential":5,"next_step":2},"closure":{"risk":3},"rabbit_hole":{"depth":3,"branches":["art","history","people","place"],"entities":["Mona_Lisa","Leonardo_da_Vinci","Louvre"]}},
    note: "Named calibration case. Maximal familiarity, near-zero gap. The eyebrows fact mildly rewards attention. Density 5 / resonance 3 pair is the cleanest illustration that resource availability ≠ resource pull." },
  // 18 · anchor · The Starry Night
  { id: "q1384lkp", bank_index: 204,
    cat: "Arts",
    sub: "Painting & Sculpture",
    diff: 2,
    kids: true,
    q: "The Starry Night was painted by which artist?",
    options: ["Claude Monet","Vincent van Gogh","Paul Cézanne","Edvard Munch"],
    answer: 1,
    fact: "Van Gogh painted it from memory in an asylum, and sold only one painting in his lifetime.",
    src: "https://en.wikipedia.org/wiki/The_Starry_Night",
    intelligence: {"archetypes":["anchor","human_story"],"curiosity":{"curiosity_gap":2,"surprise":3,"familiarity_anchor":5,"human_pull":4,"connection":3,"discovery":2,"perspective_shift":3},"tension":{"familiarity":5,"novelty":2,"optimality":3},"resource_depth":{"depth":4,"density":5,"diversity":5,"resonance":4,"experiential":5,"next_step":3},"closure":{"risk":2},"rabbit_hole":{"depth":3,"branches":["art","people","place","culture"],"entities":["The_Starry_Night","Vincent_van_Gogh","Museum_of_Modern_Art"]}},
    note: "The question is recall; the fact does the human lifting (painted from memory in an asylum; one sale in a lifetime). Perspective 3: \"tortured genius\" is true here in a way the cliché usually is not." },
  // 19 · portal · Things Fall Apart
  { id: "q5fcmli", bank_index: 220,
    cat: "Arts",
    sub: "Literature & Poetry",
    diff: 3,
    q: "Which Nigerian writer's 1958 novel 'Things Fall Apart' became a classic of world literature?",
    options: ["Wole Soyinka","Chinua Achebe","Ben Okri","Buchi Emecheta"],
    answer: 1,
    fact: "Achebe took the title from a W.B. Yeats poem, 'The Second Coming'; the novel has been translated into more than 50 languages.",
    src: "https://en.wikipedia.org/wiki/Things_Fall_Apart",
    intelligence: {"archetypes":["portal","perspective_shift","human_story"],"curiosity":{"curiosity_gap":3,"surprise":3,"familiarity_anchor":2,"human_pull":4,"connection":5,"discovery":4,"perspective_shift":5},"tension":{"familiarity":2,"novelty":4,"optimality":3},"resource_depth":{"depth":4,"density":4,"diversity":5,"resonance":5,"experiential":2,"next_step":4},"closure":{"risk":1},"rabbit_hole":{"depth":4,"branches":["literature","history","culture","politics","people"],"entities":["Things_Fall_Apart","Chinua_Achebe","Igbo_people"]}},
    note: "A novel that moved the centre of who gets to narrate colonialism. Connection 5: literature, history, politics, language. Resonance 5: the book itself IS the resource the question points to." },
  // 20 · trivia · HTTP
  { id: "q1b1xutu", bank_index: 222,
    cat: "Tech",
    sub: "Internet & Web",
    diff: 1,
    q: "What does 'HTTP' stand for?",
    options: ["HyperText Transfer Protocol","High Transfer Text Program","Hyperlink Text Transit Path","Home Tool Transfer Protocol"],
    answer: 0,
    fact: "HTTP was invented by Tim Berners-Lee around 1989–91, along with the first web browser.",
    src: "https://en.wikipedia.org/wiki/HTTP",
    intelligence: {"archetypes":["anchor"],"curiosity":{"curiosity_gap":0,"surprise":0,"familiarity_anchor":4,"human_pull":0,"connection":2,"discovery":0,"perspective_shift":0},"tension":{"familiarity":4,"novelty":0,"optimality":1},"resource_depth":{"depth":2,"density":4,"diversity":3,"resonance":1,"experiential":0,"next_step":1},"closure":{"risk":5},"rabbit_hole":{"depth":1,"branches":["technology"],"entities":["HTTP"]}},
    note: "Definitional recall, loop closes instantly. Included as the Tech trivia floor — and as the deliberate contrast with #416: same domain, utterly different curiosity profile." },
  // 21 · surprise · octopus hearts
  { id: "q13rz2bd", bank_index: 244,
    cat: "Nature",
    sub: "Oceans & Rivers",
    diff: 2,
    kids: true,
    q: "How many hearts does an octopus have?",
    options: ["One","Two","Three","Four"],
    answer: 2,
    fact: "Two hearts pump blood to the gills, one to the body — and their blood is blue.",
    src: "https://en.wikipedia.org/wiki/Octopus",
    intelligence: {"archetypes":["surprise","anchor"],"curiosity":{"curiosity_gap":2,"surprise":4,"familiarity_anchor":3,"human_pull":0,"connection":3,"discovery":3,"perspective_shift":1},"tension":{"familiarity":3,"novelty":3,"optimality":3},"resource_depth":{"depth":3,"density":4,"diversity":4,"resonance":3,"experiential":3,"next_step":2},"closure":{"risk":3},"rabbit_hole":{"depth":2,"branches":["science","environment"],"entities":["Octopus","Cephalopod"]}},
    note: "A fun fact with a real door behind it: three hearts, blue blood, a third of neurons in the arms. But the question itself only asks the number — surprise without much stretch." },
  // 22 · human story · Katherine Johnson
  { id: "q1gbx2n2", bank_index: 331,
    cat: "Science",
    sub: "Mathematics",
    diff: 1,
    kids: true,
    q: "Before his 1962 orbit of Earth, astronaut John Glenn refused to fly until a mathematician had checked the computer's numbers by hand. For which organisation did she work?",
    options: ["NASA","The US Navy","IBM","The Smithsonian Institution"],
    answer: 0,
    fact: "Katherine Johnson had already worked out the trajectory for Alan Shepard's 1961 flight, the first American in space.",
    src: "https://en.wikipedia.org/wiki/Katherine_Johnson",
    intelligence: {"archetypes":["human_story","reveal"],"curiosity":{"curiosity_gap":4,"surprise":3,"familiarity_anchor":3,"human_pull":5,"connection":4,"discovery":4,"perspective_shift":4},"tension":{"familiarity":3,"novelty":3,"optimality":4},"resource_depth":{"depth":4,"density":4,"diversity":5,"resonance":5,"experiential":3,"next_step":4},"closure":{"risk":1},"rabbit_hole":{"depth":4,"branches":["people","science","technology","history","culture"],"entities":["Katherine_Johnson","John_Glenn","NASA","Hidden_Figures"]}},
    note: "Human pull maximal: trust placed in one person’s mind over the new machine. \"Who else computed unseen?\" is the natural next question — next_step 4." },
  // 23 · connection · Eratosthenes measures Earth
  { id: "qxv0kd6", bank_index: 332,
    cat: "Science",
    sub: "Mathematics",
    diff: 1,
    kids: true,
    q: "Around 240 BCE a scholar in Alexandria compared the shadows cast at noon in two Egyptian cities. What did he manage to measure?",
    options: ["The size of the whole Earth","The distance to the Sun","The height of the Great Pyramid","The depth of the Nile"],
    answer: 0,
    fact: "Eratosthenes' figure was within about 1% of the Earth's true circumference — and two of his mistakes happened to cancel out.",
    src: "https://en.wikipedia.org/wiki/Eratosthenes",
    intelligence: {"archetypes":["connection","surprise","origin"],"curiosity":{"curiosity_gap":4,"surprise":4,"familiarity_anchor":3,"human_pull":3,"connection":5,"discovery":4,"perspective_shift":4},"tension":{"familiarity":3,"novelty":4,"optimality":5},"resource_depth":{"depth":4,"density":4,"diversity":4,"resonance":5,"experiential":3,"next_step":4},"closure":{"risk":1},"rabbit_hole":{"depth":4,"branches":["science","history","place"],"entities":["Eratosthenes","Earth_circumference","Syene","Alexandria"]}},
    note: "Two shadows and a walk between cities yield the size of the planet, ~240 BCE. Experiential 3 is literal: schools still reproduce the measurement. Kills the \"everyone thought Earth was flat\" myth as a side effect." },
  // 24 · surprise · Florence Nightingale, statistician
  { id: "q7nu0r2", bank_index: 333,
    cat: "Science",
    sub: "Mathematics",
    diff: 1,
    kids: true,
    q: "Florence Nightingale is remembered as a nurse. In which other field was she a pioneer?",
    options: ["Statistics","Chemistry","Geology","Architecture"],
    answer: 0,
    fact: "She turned death records into diagrams to persuade officials, and in 1859 became the first woman elected to the Royal Statistical Society.",
    src: "https://en.wikipedia.org/wiki/Florence_Nightingale",
    intelligence: {"archetypes":["surprise","perspective_shift","human_story"],"curiosity":{"curiosity_gap":4,"surprise":5,"familiarity_anchor":4,"human_pull":4,"connection":4,"discovery":4,"perspective_shift":4},"tension":{"familiarity":4,"novelty":4,"optimality":5},"resource_depth":{"depth":3,"density":4,"diversity":4,"resonance":5,"experiential":2,"next_step":4},"closure":{"risk":1},"rabbit_hole":{"depth":3,"branches":["people","science","history"],"entities":["Florence_Nightingale","Polar_area_diagram","Crimean_War"]}},
    note: "The famous-person-unknown-work pattern. Everyone has the lamp; almost nobody has the rose diagram that arguably saved more lives than the nursing. Textbook rubber band (optimality 5)." },
  // 25 · human story · Berners-Lee gives the Web away
  { id: "q1p6tb48", bank_index: 416,
    cat: "Tech",
    sub: "Internet & Web",
    diff: 1,
    kids: true,
    q: "Who invented the World Wide Web, and gave it away rather than patenting it?",
    options: ["Tim Berners-Lee","Bill Gates","Steve Jobs","Mark Zuckerberg"],
    answer: 0,
    fact: "He built it at CERN, a physics laboratory, so scientists could share documents — and released it with no patent and no royalties.",
    src: "https://en.wikipedia.org/wiki/Tim_Berners-Lee",
    intelligence: {"archetypes":["human_story","origin","perspective_shift"],"curiosity":{"curiosity_gap":3,"surprise":4,"familiarity_anchor":3,"human_pull":4,"connection":4,"discovery":3,"perspective_shift":3},"tension":{"familiarity":3,"novelty":3,"optimality":4},"resource_depth":{"depth":3,"density":4,"diversity":4,"resonance":4,"experiential":1,"next_step":3},"closure":{"risk":2},"rabbit_hole":{"depth":3,"branches":["technology","people","history","economics"],"entities":["Tim_Berners-Lee","World_Wide_Web","CERN"]}},
    note: "The un-patent is the story: a fortune declined so the thing could belong to everyone. Quiet counterfactual shadow (what if he had charged?) without being a counterfactual question." },
  // 26 · portal · Joy Buolamwini audits face recognition
  { id: "q8x9qj8", bank_index: 428,
    cat: "Tech",
    sub: "Artificial Intelligence",
    diff: 2,
    kids: true,
    q: "Joy Buolamwini tested commercial face-recognition systems. Whose faces did they get wrong most often?",
    options: ["Darker-skinned women","Older men","People wearing glasses","Young children"],
    answer: 0,
    fact: "In the 2018 Gender Shades study with Timnit Gebru, errors reached 34.7% for darker-skinned women and under 1% for lighter-skinned men.",
    src: "https://en.wikipedia.org/wiki/Joy_Buolamwini",
    intelligence: {"archetypes":["human_story","contradiction","portal"],"curiosity":{"curiosity_gap":4,"surprise":4,"familiarity_anchor":2,"human_pull":5,"connection":5,"discovery":5,"perspective_shift":5},"tension":{"familiarity":2,"novelty":5,"optimality":4},"resource_depth":{"depth":5,"density":4,"diversity":5,"resonance":5,"experiential":2,"next_step":5},"closure":{"risk":0},"rabbit_hole":{"depth":5,"branches":["technology","people","politics","culture","science"],"entities":["Joy_Buolamwini","Algorithmic_Justice_League","Facial_recognition_system"]}},
    note: "Proof the rubric works on contemporary tech, not only history. The white-mask detail is human pull at maximum; \"the machine is neutral\" is the contradicted assumption. Book, TED talk, film, and a live policy fight behind it." },
  // 27 · surprise · egg-laying mammals
  { id: "q1akvwoc", bank_index: 472,
    cat: "Nature",
    sub: "Mammals",
    diff: 1,
    kids: true,
    q: "Which of these mammals lays eggs?",
    options: ["The platypus","The otter","The beaver","The water vole"],
    answer: 0,
    fact: "A platypus hunts with eyes, ears and nose shut — its bill senses the faint electric fields of prey buried in the mud.",
    src: "https://en.wikipedia.org/wiki/Platypus",
    intelligence: {"archetypes":["surprise","anchor"],"curiosity":{"curiosity_gap":2,"surprise":3,"familiarity_anchor":4,"human_pull":0,"connection":3,"discovery":2,"perspective_shift":2},"tension":{"familiarity":4,"novelty":2,"optimality":3},"resource_depth":{"depth":2,"density":4,"diversity":4,"resonance":3,"experiential":3,"next_step":2},"closure":{"risk":3},"rabbit_hole":{"depth":2,"branches":["science","environment"],"entities":["Monotreme","Platypus","Echidna"]}},
    note: "Kids’ favourite. The classification bend (a mammal that lays eggs) is a small but genuine perspective shift — what defines a category when a member breaks the rule?" },
  // 28 · human story · Sembène turns to cinema
  { id: "qn7cmmo", bank_index: 517,
    cat: "Arts",
    sub: "Stage & Screen",
    diff: 3,
    kids: false,
    q: "Senegal's Ousmane Sembène was already a novelist when he turned to cinema. Why did he switch?",
    options: ["Film could reach people who did not read","Novels had been banned across Senegal","The French government asked him to switch","He lost his sight and could no longer write"],
    answer: 0,
    fact: "His 1966 film 'Black Girl' was the first feature released by a director from sub-Saharan Africa; he called cinema 'the people's night school'.",
    src: "https://en.wikipedia.org/wiki/Ousmane_Semb%C3%A8ne",
    intelligence: {"archetypes":["human_story","perspective_shift","origin"],"curiosity":{"curiosity_gap":4,"surprise":4,"familiarity_anchor":1,"human_pull":5,"connection":4,"discovery":5,"perspective_shift":4},"tension":{"familiarity":1,"novelty":5,"optimality":3},"resource_depth":{"depth":4,"density":3,"diversity":4,"resonance":5,"experiential":3,"next_step":4},"closure":{"risk":0},"rabbit_hole":{"depth":4,"branches":["art","culture","history","people","politics"],"entities":["Ousmane_Sembène","Senegal","African_cinema"]}},
    note: "A successful novelist changes medium because film can reach people who cannot read — medium choice as moral choice. The \"why\" is the whole question; closure 0 because every answer opens the films themselves." },
  // 29 · connection · Along the River During the Qingming Festival
  { id: "q1tqekq3", bank_index: 526,
    cat: "Arts",
    sub: "Painting & Sculpture",
    diff: 3,
    kids: false,
    q: "Zhang Zeduan's 'Along the River During the Qingming Festival' was painted in what format?",
    options: ["A handscroll more than five metres long","A fresco painted across a temple ceiling","A folding screen covered in gold leaf","A wall of glazed ceramic tiles"],
    answer: 0,
    fact: "Its 25 cm-high strip holds 814 people, 60 animals and 28 boats; writers have called this Song dynasty scroll 'China's Mona Lisa'.",
    src: "https://en.wikipedia.org/wiki/Along_the_River_During_the_Qingming_Festival",
    intelligence: {"archetypes":["connection","reveal","surprise"],"curiosity":{"curiosity_gap":3,"surprise":3,"familiarity_anchor":1,"human_pull":2,"connection":4,"discovery":5,"perspective_shift":3},"tension":{"familiarity":1,"novelty":5,"optimality":3},"resource_depth":{"depth":4,"density":3,"diversity":4,"resonance":4,"experiential":4,"next_step":3},"closure":{"risk":1},"rabbit_hole":{"depth":4,"branches":["art","history","culture","place"],"entities":["Along_the_River_During_the_Qingming_Festival","Zhang_Zeduan","Song_dynasty"]}},
    note: "814 people in a 25 cm-high strip. \"China’s Mona Lisa\" is a bridge — and itself worth questioning, which is a connection branch, not a flaw." },
  // 30 · reveal · Salar de Uyuni
  { id: "q1edfn1q", bank_index: 673,
    cat: "Geography",
    sub: "Cities & Places",
    diff: 2,
    kids: true,
    q: "The world's largest salt flat, the Salar de Uyuni, lies in which country?",
    options: ["Bolivia","Chile","Namibia","Iran"],
    answer: 0,
    fact: "It is so flat, under a metre of variation across 10,582 square kilometres, and so bright that satellites are calibrated against it, roughly five times more usefully than against the open ocean.",
    src: "https://en.wikipedia.org/wiki/Salar_de_Uyuni",
    intelligence: {"archetypes":["reveal","surprise"],"curiosity":{"curiosity_gap":3,"surprise":4,"familiarity_anchor":2,"human_pull":1,"connection":3,"discovery":5,"perspective_shift":2},"tension":{"familiarity":2,"novelty":4,"optimality":3},"resource_depth":{"depth":3,"density":3,"diversity":4,"resonance":4,"experiential":5,"next_step":3},"closure":{"risk":2},"rabbit_hole":{"depth":3,"branches":["place","science","environment"],"entities":["Salar_de_Uyuni","Bolivia","Lithium"]}},
    note: "Satellites calibrate against it — that is the discovery. The lithium branch (half the world’s supply under the salt) is the natural next step." },
];
