// Curio "Fact or Fake?" statement bank.
// Each: s (statement), truth (true = real, false = fake), explain (correction
// or context — names the misinformation trick for fakes), src (citation URL),
// cat (feeds the Brain Map), kids (kid-suitable flag).
// v1 set is editor-verified (famous, unambiguous misconceptions and truths);
// the agent pipeline will expand it with fact-checked additions later.
window.CURIO_STATEMENTS = [
  // ---- FAKES (common misconceptions) ----
  { s: "Humans only use 10% of their brains.", truth: false, cat: "Science", kids: true,
    explain: "Fake. Brain scans show we use virtually all of it, just not all at once. The myth spreads because it sounds hopeful — a hidden reserve of 'untapped potential'.",
    src: "https://en.wikipedia.org/wiki/Ten_percent_of_the_brain_myth" },
  { s: "Bats are blind.", truth: false, cat: "Nature", kids: true,
    explain: "Fake. All bats can see; many also 'see' with echolocation. The phrase 'blind as a bat' turned a catchy saying into a believed fact.",
    src: "https://en.wikipedia.org/wiki/Bat" },
  { s: "Vikings wore helmets with horns on them.", truth: false, cat: "History", kids: true,
    explain: "Fake. No horned Viking helmet has ever been found. The image was invented for an 1876 opera and stuck — a myth born from art, not history.",
    src: "https://en.wikipedia.org/wiki/Horned_helmet" },
  { s: "A goldfish has a memory of only a few seconds.", truth: false, cat: "Nature", kids: true,
    explain: "Fake. Goldfish remember things for months and can learn routines. The myth survives by being repeated so often it feels obviously true.",
    src: "https://en.wikipedia.org/wiki/Goldfish" },
  { s: "Napoleon Bonaparte was unusually short.", truth: false, cat: "History", kids: false,
    explain: "Fake. He was about average height for his era (~1.68 m). British wartime cartoons mocked him as tiny, and French vs. English inches confused the record.",
    src: "https://en.wikipedia.org/wiki/Napoleon" },
  { s: "Lightning never strikes the same place twice.", truth: false, cat: "Science", kids: true,
    explain: "Fake. Tall spots get hit repeatedly — the Empire State Building is struck about 20–25 times a year. A comforting proverb mistaken for physics.",
    src: "https://en.wikipedia.org/wiki/Lightning" },
  { s: "Cut an earthworm in half and you get two living worms.", truth: false, cat: "Nature", kids: true,
    explain: "Fake. At best the head end may survive and regrow a tail; the tail end dies. A schoolyard myth that oversimplifies how regeneration works.",
    src: "https://en.wikipedia.org/wiki/Earthworm" },
  { s: "Albert Einstein failed mathematics at school.", truth: false, cat: "Science", kids: false,
    explain: "Fake. Einstein excelled at maths and mastered calculus by 15. The myth is popular because it flatters anyone struggling — 'even Einstein failed'.",
    src: "https://en.wikipedia.org/wiki/Albert_Einstein" },

  // ---- REALS (surprising but true) ----
  { s: "An octopus has three hearts and blue blood.", truth: true, cat: "Nature", kids: true,
    explain: "Real. Two hearts pump blood to the gills, one to the body, and a copper-based pigment makes the blood blue instead of red.",
    src: "https://en.wikipedia.org/wiki/Octopus" },
  { s: "Honey can still be edible after thousands of years.", truth: true, cat: "Nature", kids: true,
    explain: "Real. Its low moisture and natural acidity block microbes — honey found sealed in ancient Egyptian tombs was reportedly still good to eat.",
    src: "https://en.wikipedia.org/wiki/Honey" },
  { s: "Oxford University is older than the Aztec Empire.", truth: true, cat: "History", kids: false,
    explain: "Real. Teaching at Oxford began by around 1096; the Aztecs founded Tenochtitlan in 1325. Europe's oldest English-speaking university predates the Aztec capital.",
    src: "https://en.wikipedia.org/wiki/University_of_Oxford" },
  { s: "A day on Venus lasts longer than a year on Venus.", truth: true, cat: "Science", kids: false,
    explain: "Real. Venus spins so slowly that one rotation takes 243 Earth days, while it orbits the Sun in about 225 — the day outlasts the year.",
    src: "https://en.wikipedia.org/wiki/Venus" },
  { s: "Africa is the only continent in all four hemispheres.", truth: true, cat: "Geography", kids: true,
    explain: "Real. The equator and the prime meridian both cross Africa, placing parts of it in the northern, southern, eastern and western hemispheres at once.",
    src: "https://en.wikipedia.org/wiki/Africa" },
  { s: "A banana is botanically a berry, but a strawberry is not.", truth: true, cat: "Nature", kids: true,
    explain: "Real. Botanically a berry grows from one flower with seeds inside — that fits bananas. A strawberry forms from many ovaries, so it isn't a true berry.",
    src: "https://en.wikipedia.org/wiki/Berry_(botany)" },
  { s: "Sound travels faster through water than through air.", truth: true, cat: "Science", kids: true,
    explain: "Real. Sound moves about four times faster in water (~1,480 m/s) than in air (~343 m/s), because water's tightly packed molecules pass the vibration along quicker.",
    src: "https://en.wikipedia.org/wiki/Speed_of_sound" },
  { s: "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.", truth: true, cat: "History", kids: false,
    explain: "Real. The Great Pyramid rose around 2560 BCE, Cleopatra around 30 BCE, and Apollo 11 in 1969 — she sits nearer our era than the pyramid's.",
    src: "https://en.wikipedia.org/wiki/Cleopatra" },
  { s: "Bananas are naturally radioactive.", truth: true, cat: "Science", kids: false,
    explain: "True. Bananas contain potassium-40, a radioactive isotope. The dose is tiny and harmless (the body keeps potassium balanced), but it is genuine radiation.",
    src: "https://en.wikipedia.org/wiki/Banana_equivalent_dose" },
  { s: "Glass is a slow-flowing liquid, which is why old windows are thicker at the bottom.", truth: false, cat: "Science", kids: false,
    explain: "False. Solid glass doesn't flow (medieval glass moves ~1 nm per billion years). Old panes were made uneven; the 'thick bottom' just looks like proof of flow.",
    src: "https://en.wikipedia.org/wiki/Glass" },
  { s: "Antarctica is the largest desert on Earth.", truth: true, cat: "Geography", kids: true,
    explain: "True. A desert is defined by low precipitation, not heat. Antarctica gets very little, and at ~14.2 million km2 it is the biggest desert, larger than the Sahara.",
    src: "https://en.wikipedia.org/wiki/Desert" },
  { s: "Russia spans eleven time zones.", truth: true, cat: "Geography", kids: false,
    explain: "True. Russia is so wide it observes 11 time zones, from UTC+2 in Kaliningrad to UTC+12 in Kamchatka, though most Russians live on Moscow time.",
    src: "https://en.wikipedia.org/wiki/Time_in_Russia" },
  { s: "The Great Wall of China is the only human-made structure visible from space with the naked eye.", truth: false, cat: "Geography", kids: true,
    explain: "False. The wall is too narrow to spot unaided from orbit and impossible from the Moon; astronauts confirm this. Endless repetition makes it sound authoritative.",
    src: "https://en.wikipedia.org/wiki/Great_Wall_of_China" },
  { s: "Measured from base to summit, Mount Everest is the tallest mountain on Earth.", truth: false, cat: "Geography", kids: false,
    explain: "False. Everest is highest above sea level, but Hawaii's Mauna Kea rises higher base-to-peak (~10 km, mostly underwater). The trick swaps 'highest' for 'tallest.'",
    src: "https://en.wikipedia.org/wiki/Mauna_Kea" },
  { s: "The Mona Lisa has no visible eyebrows or eyelashes.", truth: true, cat: "Arts", kids: true,
    explain: "True. The famous face shows no clear brows or lashes today, likely faded or lost to old cleanings, and possibly plucked per Renaissance fashion.",
    src: "https://en.wikipedia.org/wiki/Mona_Lisa" },
  { s: "Van Gogh's The Starry Night depicts the view from his asylum bedroom window.", truth: true, cat: "Arts", kids: false,
    explain: "True. He painted it in June 1889 at the Saint-Paul asylum in Saint-Remy, showing the pre-dawn view from his east-facing bedroom window, with an imaginary village added.",
    src: "https://en.wikipedia.org/wiki/The_Starry_Night" },
  { s: "Mozart composed the melody of 'Twinkle, Twinkle, Little Star.'", truth: false, cat: "Arts", kids: true,
    explain: "False. The tune is an anonymous French melody, 'Ah! vous dirai-je, maman', first published in 1761. Mozart only wrote piano variations on it in the 1780s. His fame makes people credit him with the whole song.",
    src: "https://en.wikipedia.org/wiki/Ah!_vous_dirai-je,_maman" },
  { s: "Napoleon's soldiers shot off the Great Sphinx's nose with a cannon.", truth: false, cat: "Arts", kids: false,
    explain: "False. Drawings from 1737 show the nose already gone, decades before Napoleon. It was likely chiselled off around 1378. A vivid villain beats a dull real cause.",
    src: "https://en.wikipedia.org/wiki/Great_Sphinx_of_Giza" },
  { s: "The world's first webcam was created to watch a coffee pot.", truth: true, cat: "Tech", kids: false,
    explain: "True. In 1991 Cambridge researchers aimed a camera at their coffee pot to avoid trips to an empty machine, the Trojan Room coffee pot, later the first cam online.",
    src: "https://en.wikipedia.org/wiki/Trojan_Room_coffee_pot" },
  { s: "The first computer mouse had a hand-carved wooden shell.", truth: true, cat: "Tech", kids: false,
    explain: "True. Douglas Engelbart's 1960s prototype, built with engineer Bill English, was a wooden shell with two metal wheels, patented in 1970.",
    src: "https://en.wikipedia.org/wiki/Douglas_Engelbart" },
  { s: "The QWERTY keyboard layout was designed to slow typists down.", truth: false, cat: "Tech", kids: false,
    explain: "False. Historians find no evidence of deliberate slowdown; the layout aimed to stop typebars jamming, which made typing faster, not slower. The 'sabotage' tale spreads because it sounds like a clever secret.",
    src: "https://en.wikipedia.org/wiki/QWERTY" },
  { s: "Thomas Edison invented the light bulb.", truth: false, cat: "Tech", kids: false,
    explain: "False. Incandescent lamps existed decades earlier (Swan, de la Rue, others). Edison built the first practical bulb and lighting system, so history credits the famous name.",
    src: "https://en.wikipedia.org/wiki/Incandescent_light_bulb" },
  { s: "Wombats produce cube-shaped poop.", truth: true, cat: "Nature", kids: true,
    explain: "True. A wombat's intestine has stiffer and stretchier zones that mould droppings into cubes, which stack without rolling away, handy for marking territory.",
    src: "https://en.wikipedia.org/wiki/Wombat" },
  { s: "Bulls charge because the colour red makes them angry.", truth: false, cat: "Nature", kids: true,
    explain: "False. Cattle are red-green colourblind; it's the cape's movement, not its colour, that provokes a charge. The bullfighter's red cape makes the myth feel obvious.",
    src: "https://en.wikipedia.org/wiki/Cattle" },
];
