// © 2026 Qpio. GENERATED by curio-hq/tools/check_watch_doors.js — do not hand-edit.
//
// WATCH DOORS WITH NOTHING BEHIND THEM.
//
// CEO, 7 Sep 2026, on the first question of his own review screen: "the
// youtube link is incorrect". He was right, and it was not one link.
//
// Every Watch door is a search inside a vetted channel. The link check asked
// "does the address answer" and got 200 every time, so it passed. Asking the
// different question — IS THERE A VIDEO — gives a different answer: 266 of
// the 760 land on an empty shelf. The British Museum is the worst of it, being
// handed West African instruments, Mesoamerican farming and Indian mathematics,
// none of which it has filmed.
//
// A door that leads nowhere is worse than no door, so these are switched off.
// They show greyed, exactly like a missing Visit, which is also the honest
// signal: it says where a real video is worth finding.
//
// Re-derived by: node tools/check_watch_doors.js --all
window.CURIO_WATCH_EMPTY = ["Q004","Q005","Q007","Q012","Q013","Q015","Q019","Q022","Q026","Q027","Q029","Q030","Q032","Q033","Q034","Q035","Q036","Q037","Q039","Q043","Q044","Q047","Q048","Q049","Q054","Q057","Q059","Q060","Q061","Q063","Q064","Q065","Q066","Q069","Q072","Q073","Q074","Q075","Q076","Q078","Q079","Q080","Q081","Q082","Q085","Q086","Q087","Q088","Q091","Q095","Q096","Q097","Q099","Q101","Q103","Q112","Q115","Q118","Q121","Q127","Q129","Q142","Q153","Q207","Q210","Q214","Q217","Q218","Q220","Q221","Q222","Q225","Q230","Q235","Q237","Q242","Q332","Q334","Q335","Q336","Q340","Q341","Q344","Q346","Q347","Q349","Q350","Q351","Q352","Q353","Q354","Q355","Q357","Q358","Q359","Q360","Q365","Q366","Q367","Q368","Q376","Q377","Q379","Q381","Q382","Q384","Q386","Q390","Q393","Q395","Q397","Q399","Q400","Q402","Q403","Q404","Q405","Q407","Q408","Q409","Q410","Q416","Q417","Q418","Q422","Q425","Q429","Q436","Q438","Q439","Q440","Q441","Q444","Q445","Q446","Q447","Q448","Q450","Q453","Q454","Q456","Q457","Q458","Q459","Q460","Q461","Q462","Q463","Q464","Q465","Q466","Q467","Q469","Q470","Q471","Q472","Q513","Q514","Q515","Q517","Q518","Q519","Q522","Q523","Q529","Q530","Q531","Q532","Q533","Q534","Q535","Q536","Q539","Q540","Q542","Q544","Q546","Q547","Q549","Q550","Q551","Q552","Q554","Q555","Q557","Q561","Q571","Q572","Q574","Q575","Q576","Q577","Q578","Q579","Q580","Q581","Q583","Q584","Q585","Q587","Q588","Q590","Q596","Q605","Q609","Q615","Q616","Q617","Q618","Q621","Q622","Q623","Q627","Q628","Q629","Q632","Q633","Q634","Q639","Q641","Q645","Q648","Q652","Q653","Q654","Q655","Q656","Q657","Q658","Q660","Q689","Q690","Q691","Q693","Q697","Q698","Q699","Q700","Q701","Q705","Q710","Q712","Q713","Q714","Q715","Q716","Q717","Q718","Q719","Q729","Q730","Q731","Q732","Q733","Q734","Q738","Q739","Q740","Q741","Q744","Q746","Q749","X0070","X0072","X0075","X0078"];
