// © 2026 Qpio. GENERATED by curio-hq/tools/inventory/apply_decisions.js — do not hand-edit.
//
// THE VIDEO THE FOUNDER CHOSE, PER QUESTION AND PER LANGUAGE.
//
// Written from the HQ review ledger (curio-hq/03-Engine/question-intelligence/
// inventory/decisions.json): every entry here is a choice he made on the review
// page under his own login, and git holds when and which. "any" is a video with
// no talking, right for every language including ones not added yet.
//
// A question in CHOSEN gets exactly that video. A language in DECLINED was
// looked at and none of the candidates was good enough, so the Watch door
// stays greyed there — a decision, not a gap.
//
// Re-derived by: node curio-hq/tools/inventory/apply_decisions.js
window.CURIO_WATCH_CHOSEN = {
 "Q181": {
  "en": "https://www.youtube.com/watch?v=FTZR6iPJaoc"
 },
 "Q123": {
  "en": "https://www.youtube.com/watch?v=0RRVV4Diomg"
 },
 "Q348": {
  "en": "https://www.youtube.com/watch?v=wXB-V_Keiu8"
 },
 "Q315": {
  "en": "https://www.youtube.com/watch?v=d5OsCUOwRLE"
 },
 "Q191": {
  "en": "https://youtu.be/zCx7_VzR1Ho",
  "fr": "https://youtu.be/pW-4JUCTBtg"
 },
 "N0890": {
  "en": "https://youtu.be/mC9tYJjmvYQ"
 },
 "Q267": {
  "en": "https://youtu.be/jhbv9ipmuYk"
 }
};
window.CURIO_WATCH_DECLINED = {};
