// © 2026 Qpio. GENERATED by curio-hq/tools/export_watch_choices.js — do not hand-edit.
//
// THE VIDEO THE FOUNDER CHOSE, PER QUESTION.
//
// CEO, 7 Sep 2026: "the workflow should allow to have several links so i can
// choose". The review screen offers several real videos with their view counts;
// this is where the one he picked ends up, and golinks.js serves it instead of
// searching.
//
// A question in CHOSEN gets exactly that video. A question in DECLINED was
// looked at and none of the candidates was good enough, so its Watch door stays
// greyed — which is a decision, not a gap, and is recorded as one.
//
// Re-derived by: node curio-hq/tools/export_watch_choices.js
window.CURIO_WATCH_CHOSEN = {};
window.CURIO_WATCH_DECLINED = [];
